// Gespräche zu Farben, Feiern, Garten und Verein (Ausbau 4).

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-colours',
    categoryId: 'cat-colours',
    title: 'Im Laden: zeigen, welches du meinst',
    blurb: 'Farbe, Größe, das da — die Sätze, mit denen man auf Dinge zeigt.',
    scene: 'shop',
    partnerName: 'Verkäufer',
    turns: [
      { id: 'fa1', speaker: 'partner', sv: 'Hej {name}! Söker du något särskilt?', de: 'Hallo {name}! Suchst du etwas Bestimmtes?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'söker', de: 'suchst' }, { sv: 'du', de: 'du' }, { sv: 'något', de: 'etwas' }, { sv: 'särskilt', de: 'Besonderes' }] },
      { id: 'fa2', speaker: 'you', sv: 'vad heter den på svenska?', de: 'wie heißt das auf Schwedisch?', chunkId: 'c-fa-vad' },
      { id: 'fa3', speaker: 'partner', sv: 'Den där? Det är en mugg.', de: 'Die da? Das ist eine Tasse.', decoding: [{ sv: 'den', de: 'die' }, { sv: 'där', de: 'dort' }, { sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'en', de: 'eine' }, { sv: 'mugg', de: 'Tasse' }] },
      { id: 'fa4', speaker: 'partner', sv: 'Vi har den i flera nyanser.', de: 'Wir haben sie in mehreren Tönen.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'den', de: 'sie' }, { sv: 'i', de: 'in' }, { sv: 'flera', de: 'mehreren' }, { sv: 'nyanser', de: 'Tönen' }] },
      { id: 'fa5', speaker: 'you', sv: 'vilken färg vill du ha?', de: 'welche Farbe willst du?', chunkId: 'c-fa-vilkenfarg' },
      { id: 'fa6', speaker: 'partner', sv: 'Haha, det är jag som frågar dig!', de: 'Haha, ich bin es, der dich fragt!', decoding: [{ sv: 'haha', de: 'haha' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'jag', de: 'ich' }, { sv: 'som', de: 'der' }, { sv: 'frågar', de: 'fragt' }, { sv: 'dig', de: 'dich' }] },
      { id: 'fa7', speaker: 'you', sv: 'den röda, tack', de: 'die rote, bitte', chunkId: 'c-fa-rod' },
      { id: 'fa8', speaker: 'partner', sv: 'Här. Vad tycker du?', de: 'Hier. Was meinst du?', decoding: [{ sv: 'här', de: 'hier' }, { sv: 'vad', de: 'was' }, { sv: 'tycker', de: 'meinst' }, { sv: 'du', de: 'du' }] },
      { id: 'fa9', speaker: 'you', sv: 'den är väldigt fin', de: 'sie ist sehr schön', chunkId: 'c-fa-fin' },
      { id: 'fa10', speaker: 'partner', sv: 'Vi har den i blått också.', de: 'Wir haben sie auch in Blau.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'den', de: 'sie' }, { sv: 'i', de: 'in' }, { sv: 'blått', de: 'Blau' }, { sv: 'också', de: 'auch' }] },
      { id: 'fa11', speaker: 'you', sv: 'jag gillar den blå', de: 'ich mag die blaue', chunkId: 'c-fa-bla' },
      { id: 'fa12', speaker: 'partner', sv: 'Den här är ganska ljus.', de: 'Diese hier ist ziemlich hell.', decoding: [{ sv: 'den', de: 'die' }, { sv: 'här', de: 'hier' }, { sv: 'är', de: 'ist' }, { sv: 'ganska', de: 'ziemlich' }, { sv: 'ljus', de: 'hell' }] },
      { id: 'fa13', speaker: 'you', sv: 'har ni den i mörkare?', de: 'habt ihr die in dunkler?', chunkId: 'c-fa-morkare' },
      { id: 'fa14', speaker: 'partner', sv: 'Ja, den sista i lagret. Varsågod.', de: 'Ja, die letzte im Lager. Bitte sehr.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'den', de: 'die' }, { sv: 'sista', de: 'letzte' }, { sv: 'i', de: 'im' }, { sv: 'lagret', de: 'Lager' }, { sv: 'varsågod', de: 'bitte sehr' }] },
      { id: 'fa15', speaker: 'you', sv: 'får jag se den?', de: 'darf ich sie sehen?', chunkId: 'c-fa-denhar' },
      { id: 'fa16', speaker: 'partner', sv: 'Bra val. Kassan är där borta.', de: 'Gute Wahl. Die Kasse ist da drüben.', decoding: [{ sv: 'bra', de: 'gute' }, { sv: 'val', de: 'Wahl' }, { sv: 'kassan', de: 'die Kasse' }, { sv: 'är', de: 'ist' }, { sv: 'där', de: 'dort' }, { sv: 'borta', de: 'drüben' }] },
    ],
  },
  {
    id: 'dlg-celebrate',
    categoryId: 'cat-celebrate',
    title: 'Geburtstag: gratulieren, anstoßen, Rede halten',
    blurb: 'Du kommst zur Feier — und hältst am Ende sogar ein paar Worte.',
    scene: 'home',
    partnerName: 'Geburtstagskind',
    turns: [
      { id: 'fe1', speaker: 'partner', sv: 'Hej {name}, vad kul att du kom!', de: 'Hallo {name}, wie schön, dass du gekommen bist!', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'vad', de: 'wie' }, { sv: 'kul', de: 'schön' }, { sv: 'att', de: 'dass' }, { sv: 'du', de: 'du' }, { sv: 'kom', de: 'kamst' }] },
      { id: 'fe2', speaker: 'you', sv: 'grattis på födelsedagen!', de: 'herzlichen Glückwunsch zum Geburtstag!', chunkId: 'c-fe-grattis' },
      { id: 'fe3', speaker: 'partner', sv: 'Tack så mycket!', de: 'Vielen Dank!', decoding: [{ sv: 'tack', de: 'danke' }, { sv: 'så', de: 'so' }, { sv: 'mycket', de: 'viel' }] },
      { id: 'fe4', speaker: 'you', sv: 'här är en present till dig', de: 'hier ist ein Geschenk für dich', chunkId: 'c-fe-present' },
      { id: 'fe5', speaker: 'partner', sv: 'Åh, det behövde du inte! Får jag öppna nu?', de: 'Oh, das hättest du nicht gemusst! Darf ich jetzt aufmachen?', decoding: [{ sv: 'åh', de: 'oh' }, { sv: 'det', de: 'das' }, { sv: 'behövde', de: 'brauchtest' }, { sv: 'du', de: 'du' }, { sv: 'inte', de: 'nicht' }, { sv: 'får', de: 'darf' }, { sv: 'jag', de: 'ich' }, { sv: 'öppna', de: 'öffnen' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'fe6', speaker: 'you', sv: 'hur gammal fyller du?', de: 'wie alt wirst du?', chunkId: 'c-fe-fyller' },
      { id: 'fe7', speaker: 'partner', sv: 'Fyrtio. Det känns konstigt att säga.', de: 'Vierzig. Es fühlt sich seltsam an, das zu sagen.', decoding: [{ sv: 'fyrtio', de: 'vierzig' }, { sv: 'det', de: 'es' }, { sv: 'känns', de: 'fühlt sich' }, { sv: 'konstigt', de: 'seltsam' }, { sv: 'att', de: 'zu' }, { sv: 'säga', de: 'sagen' }] },
      { id: 'fe8', speaker: 'partner', sv: 'Ta ett glas, alla har ett.', de: 'Nimm ein Glas, alle haben eins.', decoding: [{ sv: 'ta', de: 'nimm' }, { sv: 'ett', de: 'ein' }, { sv: 'glas', de: 'Glas' }, { sv: 'alla', de: 'alle' }, { sv: 'har', de: 'haben' }, { sv: 'ett', de: 'eins' }] },
      { id: 'fe9', speaker: 'you', sv: 'skål!', de: 'prost!', chunkId: 'c-fe-skal' },
      { id: 'fe10', speaker: 'partner', sv: 'Skål! Och sedan blir det något sött.', de: 'Prost! Und danach gibt es etwas Süßes.', decoding: [{ sv: 'skål', de: 'Schale' }, { sv: 'och', de: 'und' }, { sv: 'sedan', de: 'danach' }, { sv: 'blir', de: 'wird' }, { sv: 'det', de: 'es' }, { sv: 'något', de: 'etwas' }, { sv: 'sött', de: 'Süßes' }] },
      { id: 'fe11', speaker: 'you', sv: 'vill du ha tårta?', de: 'willst du Torte?', chunkId: 'c-fe-tarta' },
      { id: 'fe12', speaker: 'partner', sv: 'Det är min tårta, men ja tack!', de: 'Das ist meine Torte, aber ja bitte!', decoding: [{ sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'min', de: 'meine' }, { sv: 'tårta', de: 'Torte' }, { sv: 'men', de: 'aber' }, { sv: 'ja', de: 'ja' }, { sv: 'tack', de: 'bitte' }] },
      { id: 'fe13', speaker: 'you', sv: 'jag vill säga några ord', de: 'ich möchte ein paar Worte sagen', chunkId: 'c-fe-tal' },
      { id: 'fe14', speaker: 'partner', sv: 'Tyst allihop! Nu talar {name}.', de: 'Ruhe alle! Jetzt spricht {name}.', decoding: [{ sv: 'tyst', de: 'still' }, { sv: 'allihop', de: 'alle zusammen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'talar', de: 'spricht' }] },
      { id: 'fe15', speaker: 'you', sv: 'tack för att ni kom', de: 'danke, dass ihr gekommen seid', chunkId: 'c-fe-tack' },
      { id: 'fe16', speaker: 'partner', sv: 'Vilket fint tal! Skål för dig också.', de: 'Was für eine schöne Rede! Prost auch auf dich.', decoding: [{ sv: 'vilket', de: 'welch' }, { sv: 'fint', de: 'schön' }, { sv: 'tal', de: 'Rede' }, { sv: 'skål', de: 'Schale' }, { sv: 'för', de: 'für' }, { sv: 'dig', de: 'dich' }, { sv: 'också', de: 'auch' }] },
    ],
  },
  {
    id: 'dlg-garden',
    categoryId: 'cat-garden',
    title: 'Auf dem Balkon: gießen, pflanzen, ernten',
    blurb: 'Die Nachbarin gibt Tipps — und du redest über deine Tomaten.',
    scene: 'home',
    partnerName: 'Nachbarin',
    turns: [
      { id: 'ga1', speaker: 'partner', sv: 'Hej {name}! Det ser fint ut hos dig.', de: 'Hallo {name}! Bei dir sieht es schön aus.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'det', de: 'es' }, { sv: 'ser', de: 'sieht' }, { sv: 'fint', de: 'schön' }, { sv: 'ut', de: 'aus' }, { sv: 'hos', de: 'bei' }, { sv: 'dig', de: 'dir' }] },
      { id: 'ga2', speaker: 'you', sv: 'vi sitter på balkongen', de: 'wir sitzen auf dem Balkon', chunkId: 'c-ga-balkong' },
      { id: 'ga3', speaker: 'partner', sv: 'Bäst så här års. Hur går det med växterna?', de: 'Am besten um diese Jahreszeit. Wie läuft es mit den Pflanzen?', decoding: [{ sv: 'bäst', de: 'am besten' }, { sv: 'så', de: 'so' }, { sv: 'här', de: 'hier' }, { sv: 'års', de: 'des Jahres' }, { sv: 'hur', de: 'wie' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }, { sv: 'med', de: 'mit' }, { sv: 'växterna', de: 'den Pflanzen' }] },
      { id: 'ga4', speaker: 'you', sv: 'det växer bra i år', de: 'es wächst dieses Jahr gut', chunkId: 'c-ga-vaxer' },
      { id: 'ga5', speaker: 'partner', sv: 'Står de i sol hela dagen?', de: 'Stehen sie den ganzen Tag in der Sonne?', decoding: [{ sv: 'står', de: 'stehen' }, { sv: 'de', de: 'sie' }, { sv: 'i', de: 'in' }, { sv: 'sol', de: 'Sonne' }, { sv: 'hela', de: 'den ganzen' }, { sv: 'dagen', de: 'Tag' }] },
      { id: 'ga6', speaker: 'you', sv: 'det står i skuggan', de: 'es steht im Schatten', chunkId: 'c-ga-skugga' },
      { id: 'ga7', speaker: 'partner', sv: 'Klokt när det är så varmt.', de: 'Klug, wenn es so warm ist.', decoding: [{ sv: 'klokt', de: 'klug' }, { sv: 'när', de: 'wenn' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'så', de: 'so' }, { sv: 'varmt', de: 'warm' }] },
      { id: 'ga8', speaker: 'you', sv: 'jag måste vattna blommorna', de: 'ich muss die Blumen gießen', chunkId: 'c-ga-vattna' },
      { id: 'ga9', speaker: 'partner', sv: 'Gör det på kvällen, inte mitt på dagen.', de: 'Mach das abends, nicht mitten am Tag.', decoding: [{ sv: 'gör', de: 'mach' }, { sv: 'det', de: 'es' }, { sv: 'på', de: 'am' }, { sv: 'kvällen', de: 'Abend' }, { sv: 'inte', de: 'nicht' }, { sv: 'mitt', de: 'mitten' }, { sv: 'på', de: 'am' }, { sv: 'dagen', de: 'Tag' }] },
      { id: 'ga10', speaker: 'partner', sv: 'När satte du ner dem?', de: 'Wann hast du sie gesetzt?', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'satte', de: 'setztest' }, { sv: 'du', de: 'du' }, { sv: 'ner', de: 'nieder' }, { sv: 'dem', de: 'sie' }] },
      { id: 'ga11', speaker: 'you', sv: 'vi planterar i maj', de: 'wir pflanzen im Mai', chunkId: 'c-ga-planta' },
      { id: 'ga12', speaker: 'partner', sv: 'Precis rätt. Och tomaterna?', de: 'Genau richtig. Und die Tomaten?', decoding: [{ sv: 'precis', de: 'genau' }, { sv: 'rätt', de: 'richtig' }, { sv: 'och', de: 'und' }, { sv: 'tomaterna', de: 'die Tomaten' }] },
      { id: 'ga13', speaker: 'you', sv: 'vi skördar tomaterna snart', de: 'wir ernten bald die Tomaten', chunkId: 'c-ga-skorda' },
      { id: 'ga14', speaker: 'partner', sv: 'Säg till, jag byter gärna mot rabarber.', de: 'Sag Bescheid, ich tausche gern gegen Rhabarber.', decoding: [{ sv: 'säg', de: 'sag' }, { sv: 'till', de: 'zu' }, { sv: 'jag', de: 'ich' }, { sv: 'byter', de: 'tausche' }, { sv: 'gärna', de: 'gern' }, { sv: 'mot', de: 'gegen' }, { sv: 'rabarber', de: 'Rhabarber' }] },
      { id: 'ga15', speaker: 'you', sv: 'jag klipper gräset på lördag', de: 'ich mähe am Samstag den Rasen', chunkId: 'c-ga-klippa' },
      { id: 'ga16', speaker: 'partner', sv: 'Då gör jag det också. Ses där ute!', de: 'Dann mache ich das auch. Bis draußen!', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'gör', de: 'mache' }, { sv: 'jag', de: 'ich' }, { sv: 'det', de: 'es' }, { sv: 'också', de: 'auch' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'där', de: 'dort' }, { sv: 'ute', de: 'draußen' }] },
    ],
  },
  {
    id: 'dlg-forening',
    categoryId: 'cat-forening',
    title: 'Im Verein: Mitglied werden und mithelfen',
    blurb: 'Das schwedische Vereinsleben von innen — Beitrag, Vorstand, Abstimmung.',
    scene: 'office',
    partnerName: 'Vereinsvorsitzende',
    turns: [
      { id: 've1', speaker: 'partner', sv: 'Hej {name}, välkommen. Har du varit här förut?', de: 'Hallo {name}, willkommen. Warst du schon mal hier?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'välkommen', de: 'willkommen' }, { sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'varit', de: 'gewesen' }, { sv: 'här', de: 'hier' }, { sv: 'förut', de: 'vorher' }] },
      { id: 've2', speaker: 'you', sv: 'jag vill bli medlem', de: 'ich möchte Mitglied werden', chunkId: 'c-ve-medlem' },
      { id: 've3', speaker: 'partner', sv: 'Vad roligt! Det går snabbt.', de: 'Wie schön! Das geht schnell.', decoding: [{ sv: 'vad', de: 'wie' }, { sv: 'roligt', de: 'lustig' }, { sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'snabbt', de: 'schnell' }] },
      { id: 've4', speaker: 'you', sv: 'vad kostar medlemsavgiften?', de: 'wie hoch ist der Mitgliedsbeitrag?', chunkId: 'c-ve-avgift' },
      { id: 've5', speaker: 'partner', sv: 'Tvåhundra kronor om året. Barn gratis.', de: 'Zweihundert Kronen im Jahr. Kinder gratis.', decoding: [{ sv: 'tvåhundra', de: 'zweihundert' }, { sv: 'kronor', de: 'Kronen' }, { sv: 'om', de: 'in' }, { sv: 'året', de: 'dem Jahr' }, { sv: 'barn', de: 'Kinder' }, { sv: 'gratis', de: 'gratis' }] },
      { id: 've6', speaker: 'you', sv: 'anmälan är öppen nu', de: 'die Anmeldung ist jetzt offen', chunkId: 'c-ve-anmalan' },
      { id: 've7', speaker: 'partner', sv: 'Just det, du hittade sidan. Bra.', de: 'Genau, du hast die Seite gefunden. Gut.', decoding: [{ sv: 'just', de: 'gerade' }, { sv: 'det', de: 'das' }, { sv: 'du', de: 'du' }, { sv: 'hittade', de: 'fandest' }, { sv: 'sidan', de: 'die Seite' }, { sv: 'bra', de: 'gut' }] },
      { id: 've8', speaker: 'partner', sv: 'Vi behöver alltid fler händer.', de: 'Wir brauchen immer mehr Hände.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'behöver', de: 'brauchen' }, { sv: 'alltid', de: 'immer' }, { sv: 'fler', de: 'mehr' }, { sv: 'händer', de: 'Hände' }] },
      { id: 've9', speaker: 'you', sv: 'jag kan hjälpa till ideellt', de: 'ich kann ehrenamtlich mithelfen', chunkId: 'c-ve-hjalpa' },
      { id: 've10', speaker: 'partner', sv: 'Perfekt. Kom på nästa träff.', de: 'Perfekt. Komm zum nächsten Treffen.', decoding: [{ sv: 'perfekt', de: 'perfekt' }, { sv: 'kom', de: 'komm' }, { sv: 'på', de: 'auf' }, { sv: 'nästa', de: 'nächstes' }, { sv: 'träff', de: 'Treffen' }] },
      { id: 've11', speaker: 'you', sv: 'årsmötet är i mars', de: 'die Jahresversammlung ist im März', chunkId: 'c-ve-mote' },
      { id: 've12', speaker: 'partner', sv: 'Ja, och där bestäms det mesta.', de: 'Ja, und dort wird das meiste entschieden.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'och', de: 'und' }, { sv: 'där', de: 'dort' }, { sv: 'bestäms', de: 'wird bestimmt' }, { sv: 'det', de: 'das' }, { sv: 'mesta', de: 'meiste' }] },
      { id: 've13', speaker: 'you', sv: 'vi röstar om förslaget', de: 'wir stimmen über den Vorschlag ab', chunkId: 'c-ve-rosta' },
      { id: 've14', speaker: 'partner', sv: 'Alla medlemmar har en röst var.', de: 'Alle Mitglieder haben je eine Stimme.', decoding: [{ sv: 'alla', de: 'alle' }, { sv: 'medlemmar', de: 'Mitglieder' }, { sv: 'har', de: 'haben' }, { sv: 'en', de: 'eine' }, { sv: 'röst', de: 'Stimme' }, { sv: 'var', de: 'jede' }] },
      { id: 've15', speaker: 'you', sv: 'vem sitter i styrelsen?', de: 'wer sitzt im Vorstand?', chunkId: 'c-ve-styrelse' },
      { id: 've16', speaker: 'partner', sv: 'Fem stycken, och en plats är ledig.', de: 'Fünf Leute, und ein Platz ist frei.', decoding: [{ sv: 'fem', de: 'fünf' }, { sv: 'stycken', de: 'Stück' }, { sv: 'och', de: 'und' }, { sv: 'en', de: 'ein' }, { sv: 'plats', de: 'Platz' }, { sv: 'är', de: 'ist' }, { sv: 'ledig', de: 'frei' }] },
    ],
  },
];
