// Gespräche zu Zahnarzt, Studium, Umzug und Schwimmhalle (Ausbau 3).

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-dentist',
    categoryId: 'cat-dentist',
    title: 'Beim Zahnarzt: erklären, wo es weh tut',
    blurb: 'Vom ersten Satz im Stuhl bis zum nächsten Termin.',
    scene: 'clinic',
    partnerName: 'Zahnärztin',
    turns: [
      { id: 'ta1', speaker: 'partner', sv: 'Hej {name}, slå dig ner. Vad är problemet?', de: 'Hallo {name}, setz dich. Was ist das Problem?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'slå', de: 'schlage' }, { sv: 'dig', de: 'dich' }, { sv: 'ner', de: 'nieder' }, { sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'problemet', de: 'das Problem' }] },
      { id: 'ta2', speaker: 'you', sv: 'jag har tandvärk', de: 'ich habe Zahnschmerzen', chunkId: 'c-ta-tandvark' },
      { id: 'ta3', speaker: 'partner', sv: 'Kan du visa var?', de: 'Kannst du zeigen wo?', decoding: [{ sv: 'kan', de: 'kannst' }, { sv: 'du', de: 'du' }, { sv: 'visa', de: 'zeigen' }, { sv: 'var', de: 'wo' }] },
      { id: 'ta4', speaker: 'you', sv: 'det gör ont här nere', de: 'es tut hier unten weh', chunkId: 'c-ta-varmed' },
      { id: 'ta5', speaker: 'partner', sv: 'Jag ser. Reagerar den på något särskilt?', de: 'Ich sehe. Reagiert er auf etwas Bestimmtes?', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'ser', de: 'sehe' }, { sv: 'reagerar', de: 'reagiert' }, { sv: 'den', de: 'er' }, { sv: 'på', de: 'auf' }, { sv: 'något', de: 'etwas' }, { sv: 'särskilt', de: 'Besonderes' }] },
      { id: 'ta6', speaker: 'you', sv: 'tanden är känslig för kallt', de: 'der Zahn ist kälteempfindlich', chunkId: 'c-ta-kansligt' },
      { id: 'ta7', speaker: 'partner', sv: 'Det stämmer med bilden. Jag ser något litet.', de: 'Das passt zum Bild. Ich sehe etwas Kleines.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'stämmer', de: 'stimmt' }, { sv: 'med', de: 'mit' }, { sv: 'bilden', de: 'dem Bild' }, { sv: 'jag', de: 'ich' }, { sv: 'ser', de: 'sehe' }, { sv: 'något', de: 'etwas' }, { sv: 'litet', de: 'Kleines' }] },
      { id: 'ta8', speaker: 'you', sv: 'jag har ett hål', de: 'ich habe ein Loch', chunkId: 'c-ta-hal' },
      { id: 'ta9', speaker: 'partner', sv: 'Ja, ett litet. Vi fixar det idag.', de: 'Ja, ein kleines. Wir machen das heute.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'ett', de: 'ein' }, { sv: 'litet', de: 'kleines' }, { sv: 'vi', de: 'wir' }, { sv: 'fixar', de: 'richten' }, { sv: 'det', de: 'es' }, { sv: 'idag', de: 'heute' }] },
      { id: 'ta10', speaker: 'you', sv: 'kan jag få bedövning?', de: 'kann ich eine Betäubung bekommen?', chunkId: 'c-ta-bedovning' },
      { id: 'ta11', speaker: 'partner', sv: 'Självklart. Det tar en stund att verka.', de: 'Selbstverständlich. Es dauert eine Weile, bis sie wirkt.', decoding: [{ sv: 'självklart', de: 'selbstverständlich' }, { sv: 'det', de: 'es' }, { sv: 'tar', de: 'nimmt' }, { sv: 'en', de: 'eine' }, { sv: 'stund', de: 'Weile' }, { sv: 'att', de: 'zu' }, { sv: 'verka', de: 'wirken' }] },
      { id: 'ta12', speaker: 'partner', sv: 'Hur ofta sköter du tänderna?', de: 'Wie oft pflegst du die Zähne?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'ofta', de: 'oft' }, { sv: 'sköter', de: 'pflegst' }, { sv: 'du', de: 'du' }, { sv: 'tänderna', de: 'die Zähne' }] },
      { id: 'ta13', speaker: 'you', sv: 'jag borstar två gånger om dagen', de: 'ich putze zweimal am Tag', chunkId: 'c-ta-borsta' },
      { id: 'ta14', speaker: 'partner', sv: 'Bra. Använd tandtråd också.', de: 'Gut. Benutz auch Zahnseide.', decoding: [{ sv: 'bra', de: 'gut' }, { sv: 'använd', de: 'benutze' }, { sv: 'tandtråd', de: 'Zahnseide' }, { sv: 'också', de: 'auch' }] },
      { id: 'ta15', speaker: 'you', sv: 'när kan jag komma tillbaka?', de: 'wann kann ich wiederkommen?', chunkId: 'c-ta-nybesok' },
      { id: 'ta16', speaker: 'partner', sv: 'Om ett halvår. Vi hör av oss.', de: 'In einem halben Jahr. Wir melden uns.', decoding: [{ sv: 'om', de: 'in' }, { sv: 'ett', de: 'einem' }, { sv: 'halvår', de: 'halben Jahr' }, { sv: 'vi', de: 'wir' }, { sv: 'hör', de: 'hören' }, { sv: 'av', de: 'von' }, { sv: 'oss', de: 'uns' }] },
    ],
  },
  {
    id: 'dlg-studies',
    categoryId: 'cat-studies',
    title: 'Im Kursraum: Prüfung, Abgabe, Gruppenarbeit',
    blurb: 'Kurz vor der Vorlesung — und du bist im Rückstand.',
    scene: 'school',
    partnerName: 'Kurskollege',
    turns: [
      { id: 'st1', speaker: 'partner', sv: 'Hej {name}! Vi ses här varje vecka nu.', de: 'Hallo {name}! Wir sehen uns jetzt jede Woche hier.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'här', de: 'hier' }, { sv: 'varje', de: 'jede' }, { sv: 'vecka', de: 'Woche' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'st2', speaker: 'you', sv: 'jag går en kurs i svenska', de: 'ich mache einen Schwedischkurs', chunkId: 'c-st-kurs' },
      { id: 'st3', speaker: 'partner', sv: 'Jag också. Vet du när vi ska vara här?', de: 'Ich auch. Weißt du, wann wir hier sein sollen?', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'också', de: 'auch' }, { sv: 'vet', de: 'weißt' }, { sv: 'du', de: 'du' }, { sv: 'när', de: 'wann' }, { sv: 'vi', de: 'wir' }, { sv: 'ska', de: 'sollen' }, { sv: 'vara', de: 'sein' }, { sv: 'här', de: 'hier' }] },
      { id: 'st4', speaker: 'you', sv: 'föreläsningen börjar nio', de: 'die Vorlesung beginnt um neun', chunkId: 'c-st-forelasning' },
      { id: 'st5', speaker: 'partner', sv: 'Då hinner vi en kaffe. Hur ligger du till?', de: 'Dann schaffen wir einen Kaffee. Wie stehst du da?', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'hinner', de: 'schaffen' }, { sv: 'vi', de: 'wir' }, { sv: 'en', de: 'einen' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'hur', de: 'wie' }, { sv: 'ligger', de: 'liegst' }, { sv: 'du', de: 'du' }, { sv: 'till', de: 'zu' }] },
      { id: 'st6', speaker: 'you', sv: 'jag hinner inte med allt', de: 'ich schaffe nicht alles', chunkId: 'c-st-hinner' },
      { id: 'st7', speaker: 'partner', sv: 'Samma här. Vad är närmast i tiden?', de: 'Bei mir genauso. Was steht als Nächstes an?', decoding: [{ sv: 'samma', de: 'gleiche' }, { sv: 'här', de: 'hier' }, { sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'närmast', de: 'am nächsten' }, { sv: 'i', de: 'in' }, { sv: 'tiden', de: 'der Zeit' }] },
      { id: 'st8', speaker: 'you', sv: 'uppgiften ska lämnas in i morgon', de: 'die Aufgabe muss morgen abgegeben werden', chunkId: 'c-st-inlamning' },
      { id: 'st9', speaker: 'partner', sv: 'Oj. Och efter det?', de: 'Oh. Und danach?', decoding: [{ sv: 'oj', de: 'oh' }, { sv: 'och', de: 'und' }, { sv: 'efter', de: 'nach' }, { sv: 'det', de: 'dem' }] },
      { id: 'st10', speaker: 'you', sv: 'jag har tenta på fredag', de: 'ich habe Freitag Prüfung', chunkId: 'c-st-tenta' },
      { id: 'st11', speaker: 'partner', sv: 'Vi kan plugga ihop. Blir lättare så.', de: 'Wir können zusammen lernen. So wird es leichter.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'kan', de: 'können' }, { sv: 'plugga', de: 'büffeln' }, { sv: 'ihop', de: 'zusammen' }, { sv: 'blir', de: 'wird' }, { sv: 'lättare', de: 'leichter' }, { sv: 'så', de: 'so' }] },
      { id: 'st12', speaker: 'you', sv: 'vi jobbar i grupp', de: 'wir arbeiten in der Gruppe', chunkId: 'c-st-grupp' },
      { id: 'st13', speaker: 'partner', sv: 'Perfekt. Läraren kommer nu.', de: 'Perfekt. Die Lehrerin kommt jetzt.', decoding: [{ sv: 'perfekt', de: 'perfekt' }, { sv: 'läraren', de: 'die Lehrerin' }, { sv: 'kommer', de: 'kommt' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'st14', speaker: 'you', sv: 'får jag ställa en fråga?', de: 'darf ich eine Frage stellen?', chunkId: 'c-st-fraga' },
      { id: 'st15', speaker: 'partner', sv: 'Fråga du. Hon svarar gärna.', de: 'Frag ruhig. Sie antwortet gern.', decoding: [{ sv: 'fråga', de: 'frage' }, { sv: 'du', de: 'du' }, { sv: 'hon', de: 'sie' }, { sv: 'svarar', de: 'antwortet' }, { sv: 'gärna', de: 'gern' }] },
    ],
  },
  {
    id: 'dlg-moving',
    categoryId: 'cat-moving',
    title: 'Wohnungssuche: Besichtigung und Vertrag',
    blurb: 'Am Telefon mit der Vermieterin — und dann steht der Umzug an.',
    scene: 'office',
    partnerName: 'Vermieterin',
    turns: [
      { id: 'um1', speaker: 'partner', sv: 'Hej {name}, du ringde om annonsen?', de: 'Hallo {name}, du hast wegen der Anzeige angerufen?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'du', de: 'du' }, { sv: 'ringde', de: 'riefst an' }, { sv: 'om', de: 'über' }, { sv: 'annonsen', de: 'die Anzeige' }] },
      { id: 'um2', speaker: 'you', sv: 'jag söker en lägenhet', de: 'ich suche eine Wohnung', chunkId: 'c-um-soker' },
      { id: 'um3', speaker: 'partner', sv: 'Den här är ledig från första augusti.', de: 'Diese hier ist ab dem ersten August frei.', decoding: [{ sv: 'den', de: 'die' }, { sv: 'här', de: 'hier' }, { sv: 'är', de: 'ist' }, { sv: 'ledig', de: 'frei' }, { sv: 'från', de: 'von' }, { sv: 'första', de: 'ersten' }, { sv: 'augusti', de: 'August' }] },
      { id: 'um4', speaker: 'you', sv: 'hur många rum finns det?', de: 'wie viele Zimmer gibt es?', chunkId: 'c-um-rum' },
      { id: 'um5', speaker: 'partner', sv: 'Två rum och kök, fyrtio kvadrat.', de: 'Zwei Zimmer und Küche, vierzig Quadratmeter.', decoding: [{ sv: 'två', de: 'zwei' }, { sv: 'rum', de: 'Zimmer' }, { sv: 'och', de: 'und' }, { sv: 'kök', de: 'Küche' }, { sv: 'fyrtio', de: 'vierzig' }, { sv: 'kvadrat', de: 'Quadrat' }] },
      { id: 'um6', speaker: 'you', sv: 'vad kostar hyran?', de: 'wie hoch ist die Miete?', chunkId: 'c-um-hyra' },
      { id: 'um7', speaker: 'partner', sv: 'Nio tusen i månaden, värme ingår.', de: 'Neuntausend im Monat, Heizung inbegriffen.', decoding: [{ sv: 'nio', de: 'neun' }, { sv: 'tusen', de: 'tausend' }, { sv: 'i', de: 'im' }, { sv: 'månaden', de: 'Monat' }, { sv: 'värme', de: 'Wärme' }, { sv: 'ingår', de: 'ist enthalten' }] },
      { id: 'um8', speaker: 'you', sv: 'när är visningen?', de: 'wann ist die Besichtigung?', chunkId: 'c-um-visning' },
      { id: 'um9', speaker: 'partner', sv: 'På torsdag klockan sex. Passar det?', de: 'Am Donnerstag um sechs Uhr. Passt das?', decoding: [{ sv: 'på', de: 'am' }, { sv: 'torsdag', de: 'Donnerstag' }, { sv: 'klockan', de: 'die Uhr' }, { sv: 'sex', de: 'sechs' }, { sv: 'passar', de: 'passt' }, { sv: 'det', de: 'es' }] },
      { id: 'um10', speaker: 'partner', sv: 'Du var med på visningen — vill du ha den?', de: 'Du warst bei der Besichtigung dabei — willst du sie haben?', decoding: [{ sv: 'du', de: 'du' }, { sv: 'var', de: 'warst' }, { sv: 'med', de: 'dabei' }, { sv: 'på', de: 'auf' }, { sv: 'visningen', de: 'die Besichtigung' }, { sv: 'vill', de: 'willst' }, { sv: 'du', de: 'du' }, { sv: 'ha', de: 'haben' }, { sv: 'den', de: 'sie' }] },
      { id: 'um11', speaker: 'you', sv: 'jag skriver på kontraktet', de: 'ich unterschreibe den Vertrag', chunkId: 'c-um-kontrakt' },
      { id: 'um12', speaker: 'partner', sv: 'Fint! Då är den din. När kommer ni?', de: 'Schön! Dann gehört sie dir. Wann kommt ihr?', decoding: [{ sv: 'fint', de: 'schön' }, { sv: 'då', de: 'dann' }, { sv: 'är', de: 'ist' }, { sv: 'den', de: 'sie' }, { sv: 'din', de: 'deine' }, { sv: 'när', de: 'wann' }, { sv: 'kommer', de: 'kommt' }, { sv: 'ni', de: 'ihr' }] },
      { id: 'um13', speaker: 'you', sv: 'vi flyttar in på lördag', de: 'wir ziehen am Samstag ein', chunkId: 'c-um-flyttar' },
      { id: 'um14', speaker: 'partner', sv: 'Har ni hunnit förbereda allt?', de: 'Habt ihr alles vorbereiten können?', decoding: [{ sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'hunnit', de: 'geschafft' }, { sv: 'förbereda', de: 'vorbereiten' }, { sv: 'allt', de: 'alles' }] },
      { id: 'um15', speaker: 'you', sv: 'vi packar lådorna ikväll', de: 'wir packen heute Abend die Kisten', chunkId: 'c-um-lador' },
      { id: 'um16', speaker: 'partner', sv: 'Lycka till! Nycklarna får ni på lördag.', de: 'Viel Glück! Die Schlüssel bekommt ihr am Samstag.', decoding: [{ sv: 'lycka', de: 'Glück' }, { sv: 'till', de: 'zu' }, { sv: 'nycklarna', de: 'die Schlüssel' }, { sv: 'får', de: 'bekommt' }, { sv: 'ni', de: 'ihr' }, { sv: 'på', de: 'am' }, { sv: 'lördag', de: 'Samstag' }] },
    ],
  },
  {
    id: 'dlg-swim',
    categoryId: 'cat-swim',
    title: 'Schwimmhalle: duschen, Bahnen, Sauna',
    blurb: 'Der erste Besuch — mit den Regeln, die alle kennen außer dir.',
    scene: 'lake',
    partnerName: 'Bademeister',
    turns: [
      { id: 'si1', speaker: 'partner', sv: 'Hej {name}! Första gången här?', de: 'Hallo {name}! Das erste Mal hier?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'första', de: 'erste' }, { sv: 'gången', de: 'Mal' }, { sv: 'här', de: 'hier' }] },
      { id: 'si2', speaker: 'you', sv: 'vi går till simhallen', de: 'wir gehen ins Schwimmbad', chunkId: 'c-si-simhall' },
      { id: 'si3', speaker: 'partner', sv: 'Välkommen. En regel är viktig här.', de: 'Willkommen. Eine Regel ist hier wichtig.', decoding: [{ sv: 'välkommen', de: 'willkommen' }, { sv: 'en', de: 'eine' }, { sv: 'regel', de: 'Regel' }, { sv: 'är', de: 'ist' }, { sv: 'viktig', de: 'wichtig' }, { sv: 'här', de: 'hier' }] },
      { id: 'si4', speaker: 'you', sv: 'man måste duscha först', de: 'man muss zuerst duschen', chunkId: 'c-si-duscha' },
      { id: 'si5', speaker: 'partner', sv: 'Just det. Alla gör det, ingen tycker det är konstigt.', de: 'Genau. Alle machen das, niemand findet es seltsam.', decoding: [{ sv: 'just', de: 'gerade' }, { sv: 'det', de: 'das' }, { sv: 'alla', de: 'alle' }, { sv: 'gör', de: 'machen' }, { sv: 'det', de: 'es' }, { sv: 'ingen', de: 'niemand' }, { sv: 'tycker', de: 'meint' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'konstigt', de: 'seltsam' }] },
      { id: 'si6', speaker: 'partner', sv: 'Vad ska du göra idag?', de: 'Was willst du heute machen?', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'ska', de: 'sollst' }, { sv: 'du', de: 'du' }, { sv: 'göra', de: 'machen' }, { sv: 'idag', de: 'heute' }] },
      { id: 'si7', speaker: 'you', sv: 'jag simmar tjugo banor', de: 'ich schwimme zwanzig Bahnen', chunkId: 'c-si-bana' },
      { id: 'si8', speaker: 'partner', sv: 'Bra takt. Bana fyra är ledig.', de: 'Gutes Tempo. Bahn vier ist frei.', decoding: [{ sv: 'bra', de: 'gutes' }, { sv: 'takt', de: 'Takt' }, { sv: 'bana', de: 'Bahn' }, { sv: 'fyra', de: 'vier' }, { sv: 'är', de: 'ist' }, { sv: 'ledig', de: 'frei' }] },
      { id: 'si9', speaker: 'you', sv: 'hur djupt är det?', de: 'wie tief ist es?', chunkId: 'c-si-djupt' },
      { id: 'si10', speaker: 'partner', sv: 'Två meter i den änden, en meter i den andra.', de: 'Zwei Meter an dem Ende, ein Meter am anderen.', decoding: [{ sv: 'två', de: 'zwei' }, { sv: 'meter', de: 'Meter' }, { sv: 'i', de: 'an' }, { sv: 'den', de: 'dem' }, { sv: 'änden', de: 'Ende' }, { sv: 'en', de: 'ein' }, { sv: 'meter', de: 'Meter' }, { sv: 'i', de: 'an' }, { sv: 'den', de: 'dem' }, { sv: 'andra', de: 'anderen' }] },
      { id: 'si11', speaker: 'you', sv: 'har du en handduk?', de: 'hast du ein Handtuch?', chunkId: 'c-si-handduk' },
      { id: 'si12', speaker: 'partner', sv: 'Vi hyr ut dem i kassan, tjugo kronor.', de: 'Wir vermieten sie an der Kasse, zwanzig Kronen.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'hyr', de: 'mietet' }, { sv: 'ut', de: 'aus' }, { sv: 'dem', de: 'sie' }, { sv: 'i', de: 'an' }, { sv: 'kassan', de: 'der Kasse' }, { sv: 'tjugo', de: 'zwanzig' }, { sv: 'kronor', de: 'Kronen' }] },
      { id: 'si13', speaker: 'you', sv: 'ska vi bada bastu?', de: 'wollen wir in die Sauna?', chunkId: 'c-si-bastu' },
      { id: 'si14', speaker: 'partner', sv: 'Den är på åttio grader nu.', de: 'Sie ist jetzt auf achtzig Grad.', decoding: [{ sv: 'den', de: 'sie' }, { sv: 'är', de: 'ist' }, { sv: 'på', de: 'auf' }, { sv: 'åttio', de: 'achtzig' }, { sv: 'grader', de: 'Grad' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'si15', speaker: 'you', sv: 'det är för varmt för mig', de: 'es ist mir zu heiß', chunkId: 'c-si-varmt' },
      { id: 'si16', speaker: 'partner', sv: 'Sitt längst ner då. Det är svalare där.', de: 'Setz dich dann ganz unten hin. Da ist es kühler.', decoding: [{ sv: 'sitt', de: 'sitze' }, { sv: 'längst', de: 'ganz' }, { sv: 'ner', de: 'unten' }, { sv: 'då', de: 'dann' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'svalare', de: 'kühler' }, { sv: 'där', de: 'dort' }] },
    ],
  },
];
