// Gespräche zu Haustiere, Zelten, Musik und Nachbarn (Ausbau 2).

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-pets',
    categoryId: 'cat-pets',
    title: 'Im Treppenhaus: ein Hund und viele Fragen',
    blurb: 'Der Nachbar kommt mit dem Hund — und du redest zum ersten Mal mit ihm.',
    scene: 'street',
    partnerName: 'Hundebesitzer',
    turns: [
      { id: 'pe1', speaker: 'partner', sv: 'Hej {name}! Vi bor ju i samma hus.', de: 'Hallo {name}! Wir wohnen ja im selben Haus.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'vi', de: 'wir' }, { sv: 'bor', de: 'wohnen' }, { sv: 'ju', de: 'ja' }, { sv: 'i', de: 'in' }, { sv: 'samma', de: 'gleichen' }, { sv: 'hus', de: 'Haus' }] },
      { id: 'pe2', speaker: 'you', sv: 'får jag klappa den?', de: 'darf ich ihn streicheln?', chunkId: 'c-pe-klappa' },
      { id: 'pe3', speaker: 'partner', sv: 'Självklart.', de: 'Selbstverständlich.', decoding: [{ sv: 'självklart', de: 'selbstverständlich' }] },
      { id: 'pe4', speaker: 'you', sv: 'den bits inte', de: 'er beißt nicht', chunkId: 'c-pe-bits' },
      { id: 'pe5', speaker: 'partner', sv: 'Nej då, han är snäll. Har du själv något?', de: 'Nein, er ist lieb. Hast du selbst etwas?', decoding: [{ sv: 'nej', de: 'nein' }, { sv: 'då', de: 'denn' }, { sv: 'han', de: 'er' }, { sv: 'är', de: 'ist' }, { sv: 'snäll', de: 'nett' }, { sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'själv', de: 'selbst' }, { sv: 'något', de: 'etwas' }] },
      { id: 'pe6', speaker: 'you', sv: 'har du husdjur?', de: 'hast du Haustiere?', chunkId: 'c-pe-husdjur' },
      { id: 'pe7', speaker: 'partner', sv: 'Ja, den här. Och en katt hemma.', de: 'Ja, den hier. Und eine Katze daheim.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'den', de: 'den' }, { sv: 'här', de: 'hier' }, { sv: 'och', de: 'und' }, { sv: 'en', de: 'eine' }, { sv: 'katt', de: 'Katze' }, { sv: 'hemma', de: 'daheim' }] },
      { id: 'pe8', speaker: 'you', sv: 'jag har en hund', de: 'ich habe einen Hund', chunkId: 'c-pe-hund' },
      { id: 'pe9', speaker: 'partner', sv: 'Vad kul! Var är den nu?', de: 'Wie schön! Wo ist er jetzt?', decoding: [{ sv: 'vad', de: 'wie' }, { sv: 'kul', de: 'schön' }, { sv: 'var', de: 'wo' }, { sv: 'är', de: 'ist' }, { sv: 'den', de: 'er' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'pe10', speaker: 'you', sv: 'hunden måste ut', de: 'der Hund muss raus', chunkId: 'c-pe-ut' },
      { id: 'pe11', speaker: 'partner', sv: 'Vi går samma runda då. Och katten?', de: 'Dann gehen wir dieselbe Runde. Und die Katze?', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'går', de: 'gehen' }, { sv: 'samma', de: 'gleiche' }, { sv: 'runda', de: 'Runde' }, { sv: 'då', de: 'dann' }, { sv: 'och', de: 'und' }, { sv: 'katten', de: 'die Katze' }] },
      { id: 'pe12', speaker: 'you', sv: 'katten är inne', de: 'die Katze ist drinnen', chunkId: 'c-pe-katten' },
      { id: 'pe13', speaker: 'partner', sv: 'Klokt. Det regnar snart.', de: 'Klug. Es regnet bald.', decoding: [{ sv: 'klokt', de: 'klug' }, { sv: 'det', de: 'es' }, { sv: 'regnar', de: 'regnet' }, { sv: 'snart', de: 'bald' }] },
      { id: 'pe14', speaker: 'partner', sv: 'Vi ska bort i helgen, förresten.', de: 'Wir fahren übrigens am Wochenende weg.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'ska', de: 'sollen' }, { sv: 'bort', de: 'weg' }, { sv: 'i', de: 'am' }, { sv: 'helgen', de: 'Wochenende' }, { sv: 'förresten', de: 'übrigens' }] },
      { id: 'pe15', speaker: 'you', sv: 'vem passar katten?', de: 'wer schaut nach der Katze?', chunkId: 'c-pe-passar' },
      { id: 'pe16', speaker: 'partner', sv: 'Min syster. Men tack för att du frågar!', de: 'Meine Schwester. Aber danke, dass du fragst!', decoding: [{ sv: 'min', de: 'meine' }, { sv: 'syster', de: 'Schwester' }, { sv: 'men', de: 'aber' }, { sv: 'tack', de: 'danke' }, { sv: 'för', de: 'für' }, { sv: 'att', de: 'dass' }, { sv: 'du', de: 'du' }, { sv: 'frågar', de: 'fragst' }] },
    ],
  },
  {
    id: 'dlg-camping',
    categoryId: 'cat-camping',
    title: 'Am See: zelten nach Allemansrätten',
    blurb: 'Ihr sucht einen Platz für die Nacht — und klärt, was erlaubt ist.',
    scene: 'lake',
    partnerName: 'Wanderfreund',
    turns: [
      { id: 'ca1', speaker: 'partner', sv: 'Hej {name}, här ser det fint ut.', de: 'Hallo {name}, hier sieht es schön aus.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'här', de: 'hier' }, { sv: 'ser', de: 'sieht' }, { sv: 'det', de: 'es' }, { sv: 'fint', de: 'schön' }, { sv: 'ut', de: 'aus' }] },
      { id: 'ca2', speaker: 'you', sv: 'vi ska tälta i helgen', de: 'wir wollen am Wochenende zelten', chunkId: 'c-ca-talta' },
      { id: 'ca3', speaker: 'partner', sv: 'Får vi verkligen stanna här?', de: 'Dürfen wir wirklich hier bleiben?', decoding: [{ sv: 'får', de: 'dürfen' }, { sv: 'vi', de: 'wir' }, { sv: 'verkligen', de: 'wirklich' }, { sv: 'stanna', de: 'bleiben' }, { sv: 'här', de: 'hier' }] },
      { id: 'ca4', speaker: 'you', sv: 'här får man tälta', de: 'hier darf man zelten', chunkId: 'c-ca-farman' },
      { id: 'ca5', speaker: 'partner', sv: 'Är du säker? Marken tillhör ju någon.', de: 'Bist du sicher? Der Boden gehört ja jemandem.', decoding: [{ sv: 'är', de: 'bist' }, { sv: 'du', de: 'du' }, { sv: 'säker', de: 'sicher' }, { sv: 'marken', de: 'der Boden' }, { sv: 'tillhör', de: 'gehört' }, { sv: 'ju', de: 'ja' }, { sv: 'någon', de: 'jemand' }] },
      { id: 'ca6', speaker: 'you', sv: 'allemansrätten gäller här', de: 'das Jedermannsrecht gilt hier', chunkId: 'c-ca-allemans' },
      { id: 'ca7', speaker: 'partner', sv: 'Just det. En natt, och långt från huset.', de: 'Genau. Eine Nacht, und weit weg vom Haus.', decoding: [{ sv: 'just', de: 'gerade' }, { sv: 'det', de: 'das' }, { sv: 'en', de: 'eine' }, { sv: 'natt', de: 'Nacht' }, { sv: 'och', de: 'und' }, { sv: 'långt', de: 'weit' }, { sv: 'från', de: 'von' }, { sv: 'huset', de: 'dem Haus' }] },
      { id: 'ca8', speaker: 'partner', sv: 'Vad mer behöver vi innan det blir mörkt?', de: 'Was brauchen wir noch, bevor es dunkel wird?', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'mer', de: 'mehr' }, { sv: 'behöver', de: 'brauchen' }, { sv: 'vi', de: 'wir' }, { sv: 'innan', de: 'bevor' }, { sv: 'det', de: 'es' }, { sv: 'blir', de: 'wird' }, { sv: 'mörkt', de: 'dunkel' }] },
      { id: 'ca9', speaker: 'you', sv: 'vi behöver vatten', de: 'wir brauchen Wasser', chunkId: 'c-ca-vatten' },
      { id: 'ca10', speaker: 'partner', sv: 'Det finns en bäck bakom träden.', de: 'Hinter den Bäumen gibt es einen Bach.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'finns', de: 'gibt es' }, { sv: 'en', de: 'einen' }, { sv: 'bäck', de: 'Bach' }, { sv: 'bakom', de: 'hinter' }, { sv: 'träden', de: 'den Bäumen' }] },
      { id: 'ca11', speaker: 'you', sv: 'det blir kallt i natt', de: 'es wird heute Nacht kalt', chunkId: 'c-ca-kallt' },
      { id: 'ca12', speaker: 'partner', sv: 'Då gör vi upp eld en stund.', de: 'Dann machen wir eine Weile Feuer.', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'gör', de: 'machen' }, { sv: 'vi', de: 'wir' }, { sv: 'upp', de: 'auf' }, { sv: 'eld', de: 'Feuer' }, { sv: 'en', de: 'eine' }, { sv: 'stund', de: 'Weile' }] },
      { id: 'ca13', speaker: 'you', sv: 'elden måste släckas', de: 'das Feuer muss gelöscht werden', chunkId: 'c-ca-elden' },
      { id: 'ca14', speaker: 'partner', sv: 'Ja, helt. Och i morgon bitti?', de: 'Ja, ganz. Und morgen früh?', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'helt', de: 'ganz' }, { sv: 'och', de: 'und' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }, { sv: 'bitti', de: 'früh' }] },
      { id: 'ca15', speaker: 'you', sv: 'vi tar med skräpet hem', de: 'wir nehmen den Müll mit nach Hause', chunkId: 'c-ca-skrap' },
      { id: 'ca16', speaker: 'partner', sv: 'Precis så. Inget ska synas efteråt.', de: 'Genau so. Danach soll nichts zu sehen sein.', decoding: [{ sv: 'precis', de: 'genau' }, { sv: 'så', de: 'so' }, { sv: 'inget', de: 'nichts' }, { sv: 'ska', de: 'soll' }, { sv: 'synas', de: 'sichtbar sein' }, { sv: 'efteråt', de: 'danach' }] },
    ],
  },
  {
    id: 'dlg-music',
    categoryId: 'cat-music',
    title: 'Vor dem Konzert: Karten, Band, erste Reihe',
    blurb: 'Ihr trefft euch vor der Halle und redet euch warm.',
    scene: 'street',
    partnerName: 'Freundin',
    turns: [
      { id: 'mu1', speaker: 'partner', sv: 'Hej {name}! Äntligen.', de: 'Hallo {name}! Endlich.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'äntligen', de: 'endlich' }] },
      { id: 'mu2', speaker: 'you', sv: 'har du biljetterna?', de: 'hast du die Karten?', chunkId: 'c-mu-biljetter' },
      { id: 'mu3', speaker: 'partner', sv: 'I telefonen. Kolla, här.', de: 'Im Telefon. Schau, hier.', decoding: [{ sv: 'i', de: 'im' }, { sv: 'telefonen', de: 'dem Telefon' }, { sv: 'kolla', de: 'schau' }, { sv: 'här', de: 'hier' }] },
      { id: 'mu4', speaker: 'you', sv: 'konserten börjar åtta', de: 'das Konzert beginnt um acht', chunkId: 'c-mu-borjar' },
      { id: 'mu5', speaker: 'partner', sv: 'Vi har en halvtimme. Vill du stå nära?', de: 'Wir haben eine halbe Stunde. Willst du nah stehen?', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'en', de: 'eine' }, { sv: 'halvtimme', de: 'halbe Stunde' }, { sv: 'vill', de: 'willst' }, { sv: 'du', de: 'du' }, { sv: 'stå', de: 'stehen' }, { sv: 'nära', de: 'nah' }] },
      { id: 'mu6', speaker: 'you', sv: 'vi står långt fram', de: 'wir stehen weit vorne', chunkId: 'c-mu-fram' },
      { id: 'mu7', speaker: 'partner', sv: 'Bra. Vad tycker du om dem egentligen?', de: 'Gut. Was hältst du eigentlich von ihnen?', decoding: [{ sv: 'bra', de: 'gut' }, { sv: 'vad', de: 'was' }, { sv: 'tycker', de: 'meinst' }, { sv: 'du', de: 'du' }, { sv: 'om', de: 'über' }, { sv: 'dem', de: 'sie' }, { sv: 'egentligen', de: 'eigentlich' }] },
      { id: 'mu8', speaker: 'you', sv: 'bandet är jättebra', de: 'die Band ist super', chunkId: 'c-mu-bandet' },
      { id: 'mu9', speaker: 'partner', sv: 'Håller med. Och du själv då?', de: 'Stimme zu. Und du selbst?', decoding: [{ sv: 'håller', de: 'halte' }, { sv: 'med', de: 'mit' }, { sv: 'och', de: 'und' }, { sv: 'du', de: 'du' }, { sv: 'själv', de: 'selbst' }, { sv: 'då', de: 'denn' }] },
      { id: 'mu10', speaker: 'you', sv: 'jag spelar gitarr', de: 'ich spiele Gitarre', chunkId: 'c-mu-gitarr' },
      { id: 'mu11', speaker: 'partner', sv: 'Det visste jag inte! Sedan när?', de: 'Das wusste ich nicht! Seit wann?', decoding: [{ sv: 'det', de: 'das' }, { sv: 'visste', de: 'wusste' }, { sv: 'jag', de: 'ich' }, { sv: 'inte', de: 'nicht' }, { sv: 'sedan', de: 'seit' }, { sv: 'när', de: 'wann' }] },
      { id: 'mu12', speaker: 'you', sv: 'vilken musik gillar du?', de: 'welche Musik magst du?', chunkId: 'c-mu-gillar' },
      { id: 'mu13', speaker: 'partner', sv: 'Allt möjligt, men helst live.', de: 'Alles Mögliche, aber am liebsten live.', decoding: [{ sv: 'allt', de: 'alles' }, { sv: 'möjligt', de: 'Mögliche' }, { sv: 'men', de: 'aber' }, { sv: 'helst', de: 'am liebsten' }, { sv: 'live', de: 'live' }] },
      { id: 'mu14', speaker: 'partner', sv: 'De brukar be publiken hjälpa till.', de: 'Sie bitten das Publikum meistens mitzuhelfen.', decoding: [{ sv: 'de', de: 'sie' }, { sv: 'brukar', de: 'pflegen' }, { sv: 'be', de: 'bitten' }, { sv: 'publiken', de: 'das Publikum' }, { sv: 'hjälpa', de: 'helfen' }, { sv: 'till', de: 'zu' }] },
      { id: 'mu15', speaker: 'you', sv: 'kan du sjunga med?', de: 'kannst du mitsingen?', chunkId: 'c-mu-sjunga' },
      { id: 'mu16', speaker: 'partner', sv: 'Alla texter utantill. Kom nu!', de: 'Alle Texte auswendig. Komm jetzt!', decoding: [{ sv: 'alla', de: 'alle' }, { sv: 'texter', de: 'Texte' }, { sv: 'utantill', de: 'auswendig' }, { sv: 'kom', de: 'komm' }, { sv: 'nu', de: 'jetzt' }] },
    ],
  },
  {
    id: 'dlg-neighbours',
    categoryId: 'cat-neighbours',
    title: 'Im Haus: Waschküche, Müll und Lautstärke',
    blurb: 'Die Nachbarin klingelt — und hat gleich mehrere Anliegen.',
    scene: 'home',
    partnerName: 'Nachbarin',
    turns: [
      { id: 'na1', speaker: 'partner', sv: 'Hej {name}, stör jag?', de: 'Hallo {name}, störe ich?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'stör', de: 'störe' }, { sv: 'jag', de: 'ich' }] },
      { id: 'na2', speaker: 'you', sv: 'jag bor på tredje våningen', de: 'ich wohne im dritten Stock', chunkId: 'c-na-vaning' },
      { id: 'na3', speaker: 'partner', sv: 'Jag vet, jag bor under dig.', de: 'Ich weiß, ich wohne unter dir.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'vet', de: 'weiß' }, { sv: 'jag', de: 'ich' }, { sv: 'bor', de: 'wohne' }, { sv: 'under', de: 'unter' }, { sv: 'dig', de: 'dir' }] },
      { id: 'na4', speaker: 'partner', sv: 'Musiken hördes hela kvällen igår.', de: 'Die Musik war gestern den ganzen Abend zu hören.', decoding: [{ sv: 'musiken', de: 'die Musik' }, { sv: 'hördes', de: 'wurde gehört' }, { sv: 'hela', de: 'den ganzen' }, { sv: 'kvällen', de: 'Abend' }, { sv: 'igår', de: 'gestern' }] },
      { id: 'na5', speaker: 'you', sv: 'grannen klagade', de: 'der Nachbar hat sich beschwert', chunkId: 'c-na-grannen' },
      { id: 'na6', speaker: 'partner', sv: 'Det var jag, ja. Ingen fara.', de: 'Das war ich, ja. Kein Problem.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'jag', de: 'ich' }, { sv: 'ja', de: 'ja' }, { sv: 'ingen', de: 'keine' }, { sv: 'fara', de: 'Gefahr' }] },
      { id: 'na7', speaker: 'you', sv: 'kan du sänka volymen?', de: 'kannst du leiser machen?', chunkId: 'c-na-volym' },
      { id: 'na8', speaker: 'partner', sv: 'Haha, du menar dig själv. Men ja, tack.', de: 'Haha, du meinst dich selbst. Aber ja, danke.', decoding: [{ sv: 'haha', de: 'haha' }, { sv: 'du', de: 'du' }, { sv: 'menar', de: 'meinst' }, { sv: 'dig', de: 'dich' }, { sv: 'själv', de: 'selbst' }, { sv: 'men', de: 'aber' }, { sv: 'ja', de: 'ja' }, { sv: 'tack', de: 'danke' }] },
      { id: 'na9', speaker: 'partner', sv: 'En sak till: jag ville tvätta idag.', de: 'Noch eine Sache: ich wollte heute waschen.', decoding: [{ sv: 'en', de: 'eine' }, { sv: 'sak', de: 'Sache' }, { sv: 'till', de: 'noch' }, { sv: 'jag', de: 'ich' }, { sv: 'ville', de: 'wollte' }, { sv: 'tvätta', de: 'waschen' }, { sv: 'idag', de: 'heute' }] },
      { id: 'na10', speaker: 'you', sv: 'tvättstugan är bokad', de: 'die Waschküche ist gebucht', chunkId: 'c-na-tvattstuga' },
      { id: 'na11', speaker: 'partner', sv: 'Av dig? Då tar jag i morgon.', de: 'Von dir? Dann nehme ich morgen.', decoding: [{ sv: 'av', de: 'von' }, { sv: 'dig', de: 'dir' }, { sv: 'då', de: 'dann' }, { sv: 'tar', de: 'nehme' }, { sv: 'jag', de: 'ich' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }] },
      { id: 'na12', speaker: 'partner', sv: 'Vet du när sophämtningen kommer?', de: 'Weißt du, wann die Müllabfuhr kommt?', decoding: [{ sv: 'vet', de: 'weißt' }, { sv: 'du', de: 'du' }, { sv: 'när', de: 'wann' }, { sv: 'sophämtningen', de: 'die Müllabfuhr' }, { sv: 'kommer', de: 'kommt' }] },
      { id: 'na13', speaker: 'you', sv: 'soporna töms på fredag', de: 'der Müll wird freitags geleert', chunkId: 'c-na-sopor' },
      { id: 'na14', speaker: 'partner', sv: 'Perfekt. Och på lördag då?', de: 'Perfekt. Und am Samstag?', decoding: [{ sv: 'perfekt', de: 'perfekt' }, { sv: 'och', de: 'und' }, { sv: 'på', de: 'am' }, { sv: 'lördag', de: 'Samstag' }, { sv: 'då', de: 'denn' }] },
      { id: 'na15', speaker: 'you', sv: 'vi har städdag på lördag', de: 'wir haben Putztag am Samstag', chunkId: 'c-na-staddag' },
      { id: 'na16', speaker: 'partner', sv: 'Då ses vi i trapphuset. Behöver du något?', de: 'Dann sehen wir uns im Treppenhaus. Brauchst du etwas?', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'vi', de: 'wir' }, { sv: 'i', de: 'im' }, { sv: 'trapphuset', de: 'dem Treppenhaus' }, { sv: 'behöver', de: 'brauchst' }, { sv: 'du', de: 'du' }, { sv: 'något', de: 'etwas' }] },
      { id: 'na17', speaker: 'you', sv: 'får jag låna en borrmaskin?', de: 'darf ich eine Bohrmaschine leihen?', chunkId: 'c-na-lana' },
      { id: 'na18', speaker: 'partner', sv: 'Visst! Men inte efter åtta, tack.', de: 'Klar! Aber nicht nach acht, bitte.', decoding: [{ sv: 'visst', de: 'klar' }, { sv: 'men', de: 'aber' }, { sv: 'inte', de: 'nicht' }, { sv: 'efter', de: 'nach' }, { sv: 'åtta', de: 'acht' }, { sv: 'tack', de: 'bitte' }] },
    ],
  },
];
