// B2 — AUSBAU. Der Meilenstein, auf dem Sprache aufhört, Werkzeug zu sein:
// abwägen, verhandeln, erzählen, Nuancen treffen, Redewendungen verstehen.
//
// ⚠️ EHRLICH — und hier besonders: Auf B2 entscheidet Idiomatik, und genau die
// prüft in diesem Projekt niemand. Der Inhalt ist maschinell vorgeprüft (jedes
// Wort ist echtes Schwedisch), aber ob ein Schwede es SO sagen würde, steht
// nirgends bewiesen (docs/content-review-schwedisch.md). Bei den Redewendungen
// gilt das doppelt: sie sind fest, und eine Wendung, die um ein Wort daneben
// liegt, klingt nicht „fast richtig", sondern falsch.

import type { Area, Category, Chunk, Segment } from '../../domain/chunk';

export const areas: Area[] = [
  { id: 'area-language', title: 'Sprache & Feinheiten', blurb: 'Erzählen, Nuancen treffen, Redewendungen verstehen.', order: 11 },
];

export const categories: Category[] = [
  { id: 'cat-debate', areaId: 'area-society', title: 'Diskutieren & Abwägen', blurb: 'Einerseits, andererseits — und trotzdem zu einem Schluss kommen.', order: 2, cefr: 'B2' },
  { id: 'cat-environment', areaId: 'area-society', title: 'Umwelt & Gesellschaft', blurb: 'Klima, Steuern, Verantwortung — worüber in Schweden geredet wird.', order: 3, cefr: 'B2' },
  { id: 'cat-negotiate', areaId: 'area-society', title: 'Verhandeln', blurb: 'Preise, Bedingungen, Termine — und ein Kompromiss.', order: 4, cefr: 'B2' },
  { id: 'cat-story', areaId: 'area-language', title: 'Erzählen & Zusammenfassen', blurb: 'Etwas der Reihe nach erzählen und auf den Punkt bringen.', order: 1, cefr: 'B2' },
  { id: 'cat-nuance', areaId: 'area-language', title: 'Nuancen', blurb: 'Der feine Unterschied zwischen fast dasselbe und dasselbe.', order: 2, cefr: 'B2' },
  { id: 'cat-idioms', areaId: 'area-language', title: 'Redewendungen', blurb: 'Feste Wendungen, die man nicht Wort für Wort übersetzen darf.', order: 3, cefr: 'B2' },
];

export const chunks: Chunk[] = [
  // ── Diskutieren & Abwägen ─────────────────────────────────────────────────
  { id: 'c-aenasidan', categoryId: 'cat-debate', sv: 'å ena sidan är det billigt', de: 'einerseits ist es billig', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'ena', de: 'einer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'billigt', de: 'billig' }] },
  { id: 'c-aandrasidan', categoryId: 'cat-debate', sv: 'å andra sidan tar det tid', de: 'andererseits dauert es', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'andra', de: 'anderer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'tid', de: 'Zeit' }] },
  { id: 'c-stammerdelvis', categoryId: 'cat-debate', sv: 'det stämmer delvis', de: 'das stimmt teilweise', decoding: [{ sv: 'det', de: 'das' }, { sv: 'stämmer', de: 'stimmt' }, { sv: 'delvis', de: 'teilweise' }] },
  { id: 'c-forstardittperspektiv', categoryId: 'cat-debate', sv: 'jag förstår ditt perspektiv', de: 'ich verstehe deine Sichtweise', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'ditt', de: 'deine' }, { sv: 'perspektiv', de: 'Perspektive' }] },
  { id: 'c-latmigforklara', categoryId: 'cat-debate', sv: 'låt mig förklara', de: 'lass mich erklären', decoding: [{ sv: 'låt', de: 'lass' }, { sv: 'mig', de: 'mich' }, { sv: 'förklara', de: 'erklären' }] },
  { id: 'c-saenkeltardetinte', categoryId: 'cat-debate', sv: 'så enkelt är det inte', de: 'so einfach ist es nicht', decoding: [{ sv: 'så', de: 'so' }, { sv: 'enkelt', de: 'einfach' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }] },
  { id: 'c-aterkommatilldet', categoryId: 'cat-debate', sv: 'kan vi återkomma till det?', de: 'können wir darauf zurückkommen?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'återkomma', de: 'zurückkommen' }, { sv: 'till', de: 'zu' }, { sv: 'det', de: 'dem' }] },
  { id: 'c-daarvioverens', categoryId: 'cat-debate', sv: 'då är vi överens', de: 'dann sind wir uns einig', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'är', de: 'sind' }, { sv: 'vi', de: 'wir' }, { sv: 'överens', de: 'einig' }] },

  // ── Umwelt & Gesellschaft ─────────────────────────────────────────────────
  { id: 'c-tankapamiljon', categoryId: 'cat-environment', sv: 'vi måste tänka på miljön', de: 'wir müssen an die Umwelt denken', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'miljön', de: 'die Umwelt' }] },
  { id: 'c-klimatetforandras', categoryId: 'cat-environment', sv: 'klimatet förändras snabbt', de: 'das Klima verändert sich schnell', decoding: [{ sv: 'klimatet', de: 'das Klima' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'snabbt', de: 'schnell' }] },
  { id: 'c-intehallbart', categoryId: 'cat-environment', sv: 'det är inte hållbart i längden', de: 'das ist auf Dauer nicht tragfähig', decoding: [{ sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'inte', de: 'nicht' }, { sv: 'hållbart', de: 'haltbar' }, { sv: 'i', de: 'auf' }, { sv: 'längden', de: 'die Länge' }] },
  { id: 'c-utslappenmasteminska', categoryId: 'cat-environment', sv: 'utsläppen måste minska', de: 'die Emissionen müssen sinken', decoding: [{ sv: 'utsläppen', de: 'die Emissionen' }, { sv: 'måste', de: 'müssen' }, { sv: 'minska', de: 'sinken' }] },
  { id: 'c-samhalletforandras', categoryId: 'cat-environment', sv: 'samhället förändras hela tiden', de: 'die Gesellschaft verändert sich ständig', decoding: [{ sv: 'samhället', de: 'die Gesellschaft' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'hela', de: 'die ganze' }, { sv: 'tiden', de: 'die Zeit' }] },
  { id: 'c-skatternaarhoga', categoryId: 'cat-environment', sv: 'skatterna är höga här', de: 'die Steuern sind hier hoch', decoding: [{ sv: 'skatterna', de: 'die Steuern' }, { sv: 'är', de: 'sind' }, { sv: 'höga', de: 'hohe' }, { sv: 'här', de: 'hier' }] },
  { id: 'c-vitarcykeln', categoryId: 'cat-environment', sv: 'vi tar cykeln i stället', de: 'wir nehmen stattdessen das Fahrrad', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'cykeln', de: 'das Fahrrad' }, { sv: 'i', de: 'an' }, { sv: 'stället', de: 'der Stelle' }] },
  { id: 'c-vemtaransvar', categoryId: 'cat-environment', sv: 'vem tar ansvar för det?', de: 'wer übernimmt dafür die Verantwortung?', decoding: [{ sv: 'vem', de: 'wer' }, { sv: 'tar', de: 'nimmt' }, { sv: 'ansvar', de: 'Verantwortung' }, { sv: 'för', de: 'für' }, { sv: 'det', de: 'das' }] },

  // ── Verhandeln ────────────────────────────────────────────────────────────
  { id: 'c-forhandlaompriset', categoryId: 'cat-negotiate', sv: 'kan vi förhandla om priset?', de: 'können wir über den Preis verhandeln?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'förhandla', de: 'verhandeln' }, { sv: 'om', de: 'über' }, { sv: 'priset', de: 'den Preis' }] },
  { id: 'c-foreslarkompromiss', categoryId: 'cat-negotiate', sv: 'jag föreslår en kompromiss', de: 'ich schlage einen Kompromiss vor', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'föreslår', de: 'schlage vor' }, { sv: 'en', de: 'einen' }, { sv: 'kompromiss', de: 'Kompromiss' }] },
  { id: 'c-vilkavillkor', categoryId: 'cat-negotiate', sv: 'under vilka villkor?', de: 'unter welchen Bedingungen?', decoding: [{ sv: 'under', de: 'unter' }, { sv: 'vilka', de: 'welchen' }, { sv: 'villkor', de: 'Bedingungen' }] },
  { id: 'c-utanforbudgeten', categoryId: 'cat-negotiate', sv: 'det ligger utanför budgeten', de: 'das liegt außerhalb des Budgets', decoding: [{ sv: 'det', de: 'das' }, { sv: 'ligger', de: 'liegt' }, { sv: 'utanför', de: 'außerhalb' }, { sv: 'budgeten', de: 'des Budgets' }] },
  { id: 'c-narkannileverera', categoryId: 'cat-negotiate', sv: 'när kan ni leverera?', de: 'wann könnt ihr liefern?', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'kan', de: 'könnt' }, { sv: 'ni', de: 'ihr' }, { sv: 'leverera', de: 'liefern' }] },
  { id: 'c-viharettavtal', categoryId: 'cat-negotiate', sv: 'vi har ett avtal', de: 'wir haben eine Vereinbarung', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'ett', de: 'eine' }, { sv: 'avtal', de: 'Vereinbarung' }] },
  { id: 'c-mastetankapasaken', categoryId: 'cat-negotiate', sv: 'jag måste tänka på saken', de: 'ich muss darüber nachdenken', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'saken', de: 'die Sache' }] },
  { id: 'c-detgarjagmedpa', categoryId: 'cat-negotiate', sv: 'det går jag med på', de: 'darauf lasse ich mich ein', decoding: [{ sv: 'det', de: 'dem' }, { sv: 'går', de: 'gehe' }, { sv: 'jag', de: 'ich' }, { sv: 'med', de: 'mit' }, { sv: 'på', de: 'auf' }] },

  // ── Erzählen & Zusammenfassen ─────────────────────────────────────────────
  { id: 'c-borjadehelvanligt', categoryId: 'cat-story', sv: 'det började helt vanligt', de: 'es fing ganz normal an', decoding: [{ sv: 'det', de: 'es' }, { sv: 'började', de: 'begann' }, { sv: 'helt', de: 'ganz' }, { sv: 'vanligt', de: 'gewöhnlich' }] },
  { id: 'c-plotsligthande', categoryId: 'cat-story', sv: 'plötsligt hände något', de: 'plötzlich passierte etwas', decoding: [{ sv: 'plötsligt', de: 'plötzlich' }, { sv: 'hände', de: 'geschah' }, { sv: 'något', de: 'etwas' }] },
  { id: 'c-tillslutlostedetsig', categoryId: 'cat-story', sv: 'till slut löste det sig', de: 'am Ende hat es sich gelöst', decoding: [{ sv: 'till', de: 'zu' }, { sv: 'slut', de: 'Schluss' }, { sv: 'löste', de: 'löste' }, { sv: 'det', de: 'es' }, { sv: 'sig', de: 'sich' }] },
  { id: 'c-kortsagtgickdetbra', categoryId: 'cat-story', sv: 'kort sagt gick det bra', de: 'kurz gesagt ging es gut', decoding: [{ sv: 'kort', de: 'kurz' }, { sv: 'sagt', de: 'gesagt' }, { sv: 'gick', de: 'ging' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }] },
  { id: 'c-samtidigtsomdethande', categoryId: 'cat-story', sv: 'samtidigt som det hände', de: 'während das geschah', decoding: [{ sv: 'samtidigt', de: 'gleichzeitig' }, { sv: 'som', de: 'wie' }, { sv: 'det', de: 'es' }, { sv: 'hände', de: 'geschah' }] },
  { id: 'c-detvisadesigvarafel', categoryId: 'cat-story', sv: 'det visade sig vara fel', de: 'es stellte sich als falsch heraus', decoding: [{ sv: 'det', de: 'es' }, { sv: 'visade', de: 'zeigte' }, { sv: 'sig', de: 'sich' }, { sv: 'vara', de: 'sein' }, { sv: 'fel', de: 'falsch' }] },
  { id: 'c-jagminnsattdetregnade', categoryId: 'cat-story', sv: 'jag minns att det regnade', de: 'ich erinnere mich, dass es regnete', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'minns', de: 'erinnere mich' }, { sv: 'att', de: 'dass' }, { sv: 'det', de: 'es' }, { sv: 'regnade', de: 'regnete' }] },
  { id: 'c-forattsammanfatta', categoryId: 'cat-story', sv: 'för att sammanfatta', de: 'um es zusammenzufassen', decoding: [{ sv: 'för', de: 'für' }, { sv: 'att', de: 'zu' }, { sv: 'sammanfatta', de: 'zusammenfassen' }] },

  // ── Nuancen ───────────────────────────────────────────────────────────────
  { id: 'c-skillnadenarliten', categoryId: 'cat-nuance', sv: 'skillnaden är liten men viktig', de: 'der Unterschied ist klein, aber wichtig', decoding: [{ sv: 'skillnaden', de: 'der Unterschied' }, { sv: 'är', de: 'ist' }, { sv: 'liten', de: 'klein' }, { sv: 'men', de: 'aber' }, { sv: 'viktig', de: 'wichtig' }] },
  { id: 'c-laterhardare', categoryId: 'cat-nuance', sv: 'det låter hårdare än jag menar', de: 'das klingt härter, als ich es meine', decoding: [{ sv: 'det', de: 'das' }, { sv: 'låter', de: 'klingt' }, { sv: 'hårdare', de: 'härter' }, { sv: 'än', de: 'als' }, { sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }] },
  { id: 'c-menarsnarare', categoryId: 'cat-nuance', sv: 'jag menar snarare tvärtom', de: 'ich meine eher das Gegenteil', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }, { sv: 'snarare', de: 'eher' }, { sv: 'tvärtom', de: 'umgekehrt' }] },
  { id: 'c-uttrycketbetyderannat', categoryId: 'cat-nuance', sv: 'uttrycket betyder något annat', de: 'der Ausdruck bedeutet etwas anderes', decoding: [{ sv: 'uttrycket', de: 'der Ausdruck' }, { sv: 'betyder', de: 'bedeutet' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }] },
  { id: 'c-bokstavligttalat', categoryId: 'cat-nuance', sv: 'bokstavligt talat', de: 'wörtlich genommen', decoding: [{ sv: 'bokstavligt', de: 'buchstäblich' }, { sv: 'talat', de: 'gesprochen' }] },
  { id: 'c-berorpahurmansager', categoryId: 'cat-nuance', sv: 'det beror på hur man säger det', de: 'es kommt darauf an, wie man es sagt', decoding: [{ sv: 'det', de: 'es' }, { sv: 'beror', de: 'beruht' }, { sv: 'på', de: 'auf' }, { sv: 'hur', de: 'wie' }, { sv: 'man', de: 'man' }, { sv: 'säger', de: 'sagt' }, { sv: 'det', de: 'es' }] },
  { id: 'c-uttryckermigfel', categoryId: 'cat-nuance', sv: 'jag uttrycker mig kanske fel', de: 'ich drücke mich vielleicht falsch aus', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'uttrycker', de: 'drücke aus' }, { sv: 'mig', de: 'mich' }, { sv: 'kanske', de: 'vielleicht' }, { sv: 'fel', de: 'falsch' }] },
  { id: 'c-lasamellanraderna', categoryId: 'cat-nuance', sv: 'man får läsa mellan raderna', de: 'man muss zwischen den Zeilen lesen', decoding: [{ sv: 'man', de: 'man' }, { sv: 'får', de: 'darf' }, { sv: 'läsa', de: 'lesen' }, { sv: 'mellan', de: 'zwischen' }, { sv: 'raderna', de: 'den Zeilen' }] },

  // ── Redewendungen ─────────────────────────────────────────────────────────
  // Feste Wendungen: die Dekodierung zeigt bewusst das WÖRTLICHE — der Witz
  // dieser Wendungen liegt genau im Abstand zwischen Wort und Bedeutung.
  { id: 'c-ingenkopaisen', categoryId: 'cat-idioms', sv: 'det är ingen ko på isen', de: 'es eilt nicht', decoding: [{ sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'ingen', de: 'keine' }, { sv: 'ko', de: 'Kuh' }, { sv: 'på', de: 'auf' }, { sv: 'isen', de: 'dem Eis' }] },
  { id: 'c-hundbegraven', categoryId: 'cat-idioms', sv: 'här ligger en hund begraven', de: 'da stimmt etwas nicht', decoding: [{ sv: 'här', de: 'hier' }, { sv: 'ligger', de: 'liegt' }, { sv: 'en', de: 'ein' }, { sv: 'hund', de: 'Hund' }, { sv: 'begraven', de: 'begraben' }] },
  { id: 'c-lagomarbast', categoryId: 'cat-idioms', sv: 'lagom är bäst', de: 'das rechte Maß ist am besten', decoding: [{ sv: 'lagom', de: 'gerade genug' }, { sv: 'är', de: 'ist' }, { sv: 'bäst', de: 'am besten' }] },
  { id: 'c-ingenfarapataket', categoryId: 'cat-idioms', sv: 'ingen fara på taket', de: 'kein Grund zur Sorge', decoding: [{ sv: 'ingen', de: 'keine' }, { sv: 'fara', de: 'Gefahr' }, { sv: 'på', de: 'auf' }, { sv: 'taket', de: 'dem Dach' }] },
  { id: 'c-bortabrahemmabast', categoryId: 'cat-idioms', sv: 'borta bra men hemma bäst', de: 'daheim ist es doch am schönsten', decoding: [{ sv: 'borta', de: 'weg' }, { sv: 'bra', de: 'gut' }, { sv: 'men', de: 'aber' }, { sv: 'hemma', de: 'daheim' }, { sv: 'bäst', de: 'am besten' }] },
  { id: 'c-battresentanaldrig', categoryId: 'cat-idioms', sv: 'bättre sent än aldrig', de: 'besser spät als nie', decoding: [{ sv: 'bättre', de: 'besser' }, { sv: 'sent', de: 'spät' }, { sv: 'än', de: 'als' }, { sv: 'aldrig', de: 'nie' }] },
  { id: 'c-ovninggerfardighet', categoryId: 'cat-idioms', sv: 'övning ger färdighet', de: 'Übung macht den Meister', decoding: [{ sv: 'övning', de: 'Übung' }, { sv: 'ger', de: 'gibt' }, { sv: 'färdighet', de: 'Fertigkeit' }] },
  { id: 'c-detvardroppen', categoryId: 'cat-idioms', sv: 'det var droppen', de: 'das war zu viel des Guten', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'droppen', de: 'der Tropfen' }] },
];

export const segments: Segment[] = [
  // ── Diskutieren & Abwägen ─────────────────────────────────────────────────
  { id: 's-b2d-ena1', level: 3, sv: 'Å ena sidan är det billigt, men kvaliteten är osäker.', de: 'Einerseits ist es billig, aber die Qualität ist unsicher.', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'ena', de: 'einer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'billigt', de: 'billig' }, { sv: 'men', de: 'aber' }, { sv: 'kvaliteten', de: 'die Qualität' }, { sv: 'är', de: 'ist' }, { sv: 'osäker', de: 'unsicher' }], chunkIds: ['c-aenasidan'] },
  { id: 's-b2d-ena2', level: 3, sv: 'Å ena sidan är det billigt, och det spelar roll nu.', de: 'Einerseits ist es billig, und das spielt jetzt eine Rolle.', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'ena', de: 'einer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'billigt', de: 'billig' }, { sv: 'och', de: 'und' }, { sv: 'det', de: 'das' }, { sv: 'spelar', de: 'spielt' }, { sv: 'roll', de: 'Rolle' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-aenasidan'] },
  { id: 's-b2d-andra1', level: 3, sv: 'Å andra sidan tar det tid, och tid har vi inte.', de: 'Andererseits dauert es, und Zeit haben wir nicht.', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'andra', de: 'anderer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'tid', de: 'Zeit' }, { sv: 'och', de: 'und' }, { sv: 'tid', de: 'Zeit' }, { sv: 'har', de: 'haben' }, { sv: 'vi', de: 'wir' }, { sv: 'inte', de: 'nicht' }], chunkIds: ['c-aandrasidan'] },
  { id: 's-b2d-andra2', level: 3, sv: 'Å andra sidan tar det tid att lära sig allt.', de: 'Andererseits dauert es, alles zu lernen.', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'andra', de: 'anderer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'tid', de: 'Zeit' }, { sv: 'att', de: 'zu' }, { sv: 'lära', de: 'lernen' }, { sv: 'sig', de: 'sich' }, { sv: 'allt', de: 'alles' }], chunkIds: ['c-aandrasidan'] },
  { id: 's-b2d-delvis1', level: 3, sv: 'Det stämmer delvis, men inte helt.', de: 'Das stimmt teilweise, aber nicht ganz.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'stämmer', de: 'stimmt' }, { sv: 'delvis', de: 'teilweise' }, { sv: 'men', de: 'aber' }, { sv: 'inte', de: 'nicht' }, { sv: 'helt', de: 'ganz' }], chunkIds: ['c-stammerdelvis'] },
  { id: 's-b2d-delvis2', level: 3, sv: 'Det stämmer delvis, siffrorna säger något annat.', de: 'Das stimmt teilweise, die Zahlen sagen etwas anderes.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'stämmer', de: 'stimmt' }, { sv: 'delvis', de: 'teilweise' }, { sv: 'siffrorna', de: 'die Zahlen' }, { sv: 'säger', de: 'sagen' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }], chunkIds: ['c-stammerdelvis'] },
  { id: 's-b2d-perspektiv1', level: 3, sv: 'Jag förstår ditt perspektiv, även om jag tycker annorlunda.', de: 'Ich verstehe deine Sichtweise, auch wenn ich anders denke.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'ditt', de: 'deine' }, { sv: 'perspektiv', de: 'Perspektive' }, { sv: 'även', de: 'auch' }, { sv: 'om', de: 'wenn' }, { sv: 'jag', de: 'ich' }, { sv: 'tycker', de: 'meine' }, { sv: 'annorlunda', de: 'anders' }], chunkIds: ['c-forstardittperspektiv'] },
  { id: 's-b2d-perspektiv2', level: 3, sv: 'Jag förstår ditt perspektiv, du har sett mer av det.', de: 'Ich verstehe deine Sichtweise, du hast mehr davon gesehen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'ditt', de: 'deine' }, { sv: 'perspektiv', de: 'Perspektive' }, { sv: 'du', de: 'du' }, { sv: 'har', de: 'hast' }, { sv: 'sett', de: 'gesehen' }, { sv: 'mer', de: 'mehr' }, { sv: 'av', de: 'von' }, { sv: 'det', de: 'dem' }], chunkIds: ['c-forstardittperspektiv'] },
  { id: 's-b2d-forklara1', level: 3, sv: 'Låt mig förklara hur jag tänker.', de: 'Lass mich erklären, wie ich denke.', decoding: [{ sv: 'låt', de: 'lass' }, { sv: 'mig', de: 'mich' }, { sv: 'förklara', de: 'erklären' }, { sv: 'hur', de: 'wie' }, { sv: 'jag', de: 'ich' }, { sv: 'tänker', de: 'denke' }], chunkIds: ['c-latmigforklara'] },
  { id: 's-b2d-forklara2', level: 3, sv: 'Vänta lite, låt mig förklara först.', de: 'Warte kurz, lass mich zuerst erklären.', decoding: [{ sv: 'vänta', de: 'warte' }, { sv: 'lite', de: 'wenig' }, { sv: 'låt', de: 'lass' }, { sv: 'mig', de: 'mich' }, { sv: 'förklara', de: 'erklären' }, { sv: 'först', de: 'zuerst' }], chunkIds: ['c-latmigforklara'] },
  { id: 's-b2d-enkelt1', level: 3, sv: 'Så enkelt är det inte, tyvärr.', de: 'So einfach ist es leider nicht.', decoding: [{ sv: 'så', de: 'so' }, { sv: 'enkelt', de: 'einfach' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }, { sv: 'tyvärr', de: 'leider' }], chunkIds: ['c-saenkeltardetinte'] },
  { id: 's-b2d-enkelt2', level: 3, sv: 'Så enkelt är det inte, det finns flera sidor.', de: 'So einfach ist es nicht, es gibt mehrere Seiten.', decoding: [{ sv: 'så', de: 'so' }, { sv: 'enkelt', de: 'einfach' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }, { sv: 'det', de: 'es' }, { sv: 'finns', de: 'gibt' }, { sv: 'flera', de: 'mehrere' }, { sv: 'sidor', de: 'Seiten' }], chunkIds: ['c-saenkeltardetinte'] },
  { id: 's-b2d-aterkomma1', level: 3, sv: 'Kan vi återkomma till det efter mötet?', de: 'Können wir nach dem Treffen darauf zurückkommen?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'återkomma', de: 'zurückkommen' }, { sv: 'till', de: 'zu' }, { sv: 'det', de: 'dem' }, { sv: 'efter', de: 'nach' }, { sv: 'mötet', de: 'dem Treffen' }], chunkIds: ['c-aterkommatilldet'] },
  { id: 's-b2d-aterkomma2', level: 3, sv: 'Kan vi återkomma till det? Vi hinner inte nu.', de: 'Können wir darauf zurückkommen? Wir schaffen es jetzt nicht.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'återkomma', de: 'zurückkommen' }, { sv: 'till', de: 'zu' }, { sv: 'det', de: 'dem' }, { sv: 'vi', de: 'wir' }, { sv: 'hinner', de: 'schaffen' }, { sv: 'inte', de: 'nicht' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-aterkommatilldet'] },
  { id: 's-b2d-overens1', level: 3, sv: 'Då är vi överens, bra att det löste sig.', de: 'Dann sind wir uns einig, gut, dass es sich gelöst hat.', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'är', de: 'sind' }, { sv: 'vi', de: 'wir' }, { sv: 'överens', de: 'einig' }, { sv: 'bra', de: 'gut' }, { sv: 'att', de: 'dass' }, { sv: 'det', de: 'es' }, { sv: 'löste', de: 'löste' }, { sv: 'sig', de: 'sich' }], chunkIds: ['c-daarvioverens'] },
  { id: 's-b2d-overens2', level: 3, sv: 'Då är vi överens om priset åtminstone.', de: 'Dann sind wir uns wenigstens beim Preis einig.', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'är', de: 'sind' }, { sv: 'vi', de: 'wir' }, { sv: 'överens', de: 'einig' }, { sv: 'om', de: 'über' }, { sv: 'priset', de: 'den Preis' }, { sv: 'åtminstone', de: 'wenigstens' }], chunkIds: ['c-daarvioverens'] },
  { id: 's-b2d-mix1', level: 3, sv: 'Å ena sidan är det billigt, å andra sidan tar det tid.', de: 'Einerseits ist es billig, andererseits dauert es.', decoding: [{ sv: 'å', de: 'auf' }, { sv: 'ena', de: 'einer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'billigt', de: 'billig' }, { sv: 'å', de: 'auf' }, { sv: 'andra', de: 'anderer' }, { sv: 'sidan', de: 'Seite' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'tid', de: 'Zeit' }], chunkIds: ['c-aenasidan', 'c-aandrasidan'] },
  { id: 's-b2d-mix2', level: 3, sv: 'Det stämmer delvis. Låt mig förklara varför.', de: 'Das stimmt teilweise. Lass mich erklären, warum.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'stämmer', de: 'stimmt' }, { sv: 'delvis', de: 'teilweise' }, { sv: 'låt', de: 'lass' }, { sv: 'mig', de: 'mich' }, { sv: 'förklara', de: 'erklären' }, { sv: 'varför', de: 'warum' }], chunkIds: ['c-stammerdelvis', 'c-latmigforklara'] },
  { id: 's-b2d-mix3', level: 3, sv: 'Jag förstår ditt perspektiv, men så enkelt är det inte.', de: 'Ich verstehe deine Sichtweise, aber so einfach ist es nicht.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'ditt', de: 'deine' }, { sv: 'perspektiv', de: 'Perspektive' }, { sv: 'men', de: 'aber' }, { sv: 'så', de: 'so' }, { sv: 'enkelt', de: 'einfach' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }], chunkIds: ['c-forstardittperspektiv', 'c-saenkeltardetinte'] },
  { id: 's-b2d-mix4', level: 3, sv: 'Kan vi återkomma till det? Då är vi överens så länge.', de: 'Können wir darauf zurückkommen? Dann sind wir uns so lange einig.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'återkomma', de: 'zurückkommen' }, { sv: 'till', de: 'zu' }, { sv: 'det', de: 'dem' }, { sv: 'då', de: 'dann' }, { sv: 'är', de: 'sind' }, { sv: 'vi', de: 'wir' }, { sv: 'överens', de: 'einig' }, { sv: 'så', de: 'so' }, { sv: 'länge', de: 'lange' }], chunkIds: ['c-aterkommatilldet', 'c-daarvioverens'] },

  // ── Umwelt & Gesellschaft ─────────────────────────────────────────────────
  { id: 's-b2u-miljo1', level: 3, sv: 'Vi måste tänka på miljön, inte bara på priset.', de: 'Wir müssen an die Umwelt denken, nicht nur an den Preis.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'miljön', de: 'die Umwelt' }, { sv: 'inte', de: 'nicht' }, { sv: 'bara', de: 'nur' }, { sv: 'på', de: 'an' }, { sv: 'priset', de: 'den Preis' }], chunkIds: ['c-tankapamiljon'] },
  { id: 's-b2u-miljo2', level: 3, sv: 'Vi måste tänka på miljön redan nu.', de: 'Wir müssen jetzt schon an die Umwelt denken.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'miljön', de: 'die Umwelt' }, { sv: 'redan', de: 'schon' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-tankapamiljon'] },
  { id: 's-b2u-klimat1', level: 3, sv: 'Klimatet förändras snabbt, det märks här uppe.', de: 'Das Klima verändert sich schnell, hier oben merkt man das.', decoding: [{ sv: 'klimatet', de: 'das Klima' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'snabbt', de: 'schnell' }, { sv: 'det', de: 'es' }, { sv: 'märks', de: 'merkt sich' }, { sv: 'här', de: 'hier' }, { sv: 'uppe', de: 'oben' }], chunkIds: ['c-klimatetforandras'] },
  { id: 's-b2u-klimat2', level: 3, sv: 'Vintrarna är kortare, klimatet förändras snabbt.', de: 'Die Winter sind kürzer, das Klima verändert sich schnell.', decoding: [{ sv: 'vintrarna', de: 'die Winter' }, { sv: 'är', de: 'sind' }, { sv: 'kortare', de: 'kürzer' }, { sv: 'klimatet', de: 'das Klima' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'snabbt', de: 'schnell' }], chunkIds: ['c-klimatetforandras'] },
  { id: 's-b2u-hallbart1', level: 3, sv: 'Det är inte hållbart i längden, alla vet det.', de: 'Das ist auf Dauer nicht tragfähig, alle wissen das.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'inte', de: 'nicht' }, { sv: 'hållbart', de: 'haltbar' }, { sv: 'i', de: 'auf' }, { sv: 'längden', de: 'die Länge' }, { sv: 'alla', de: 'alle' }, { sv: 'vet', de: 'wissen' }, { sv: 'det', de: 'das' }], chunkIds: ['c-intehallbart'] },
  { id: 's-b2u-hallbart2', level: 3, sv: 'Det fungerar nu, men det är inte hållbart i längden.', de: 'Es funktioniert jetzt, aber auf Dauer ist es nicht tragfähig.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'fungerar', de: 'funktioniert' }, { sv: 'nu', de: 'jetzt' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'inte', de: 'nicht' }, { sv: 'hållbart', de: 'haltbar' }, { sv: 'i', de: 'auf' }, { sv: 'längden', de: 'die Länge' }], chunkIds: ['c-intehallbart'] },
  { id: 's-b2u-utslapp1', level: 3, sv: 'Utsläppen måste minska, annars hjälper inget.', de: 'Die Emissionen müssen sinken, sonst hilft nichts.', decoding: [{ sv: 'utsläppen', de: 'die Emissionen' }, { sv: 'måste', de: 'müssen' }, { sv: 'minska', de: 'sinken' }, { sv: 'annars', de: 'sonst' }, { sv: 'hjälper', de: 'hilft' }, { sv: 'inget', de: 'nichts' }], chunkIds: ['c-utslappenmasteminska'] },
  { id: 's-b2u-utslapp2', level: 3, sv: 'Alla är eniga: utsläppen måste minska.', de: 'Alle sind sich einig: die Emissionen müssen sinken.', decoding: [{ sv: 'alla', de: 'alle' }, { sv: 'är', de: 'sind' }, { sv: 'eniga', de: 'einig' }, { sv: 'utsläppen', de: 'die Emissionen' }, { sv: 'måste', de: 'müssen' }, { sv: 'minska', de: 'sinken' }], chunkIds: ['c-utslappenmasteminska'] },
  { id: 's-b2u-samhalle1', level: 3, sv: 'Samhället förändras hela tiden, det är inget nytt.', de: 'Die Gesellschaft verändert sich ständig, das ist nichts Neues.', decoding: [{ sv: 'samhället', de: 'die Gesellschaft' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'hela', de: 'die ganze' }, { sv: 'tiden', de: 'die Zeit' }, { sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'inget', de: 'nichts' }, { sv: 'nytt', de: 'Neues' }], chunkIds: ['c-samhalletforandras'] },
  { id: 's-b2u-samhalle2', level: 3, sv: 'Samhället förändras hela tiden, och lagarna följer efter.', de: 'Die Gesellschaft verändert sich ständig, und die Gesetze folgen nach.', decoding: [{ sv: 'samhället', de: 'die Gesellschaft' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'hela', de: 'die ganze' }, { sv: 'tiden', de: 'die Zeit' }, { sv: 'och', de: 'und' }, { sv: 'lagarna', de: 'die Gesetze' }, { sv: 'följer', de: 'folgen' }, { sv: 'efter', de: 'nach' }], chunkIds: ['c-samhalletforandras'] },
  { id: 's-b2u-skatt1', level: 3, sv: 'Skatterna är höga här, men vi får mycket tillbaka.', de: 'Die Steuern sind hier hoch, aber wir bekommen viel zurück.', decoding: [{ sv: 'skatterna', de: 'die Steuern' }, { sv: 'är', de: 'sind' }, { sv: 'höga', de: 'hohe' }, { sv: 'här', de: 'hier' }, { sv: 'men', de: 'aber' }, { sv: 'vi', de: 'wir' }, { sv: 'får', de: 'bekommen' }, { sv: 'mycket', de: 'viel' }, { sv: 'tillbaka', de: 'zurück' }], chunkIds: ['c-skatternaarhoga'] },
  { id: 's-b2u-skatt2', level: 3, sv: 'Skatterna är höga här, det överraskar många.', de: 'Die Steuern sind hier hoch, das überrascht viele.', decoding: [{ sv: 'skatterna', de: 'die Steuern' }, { sv: 'är', de: 'sind' }, { sv: 'höga', de: 'hohe' }, { sv: 'här', de: 'hier' }, { sv: 'det', de: 'das' }, { sv: 'överraskar', de: 'überrascht' }, { sv: 'många', de: 'viele' }], chunkIds: ['c-skatternaarhoga'] },
  { id: 's-b2u-cykel1', level: 3, sv: 'Vi tar cykeln i stället, det går fortare.', de: 'Wir nehmen stattdessen das Fahrrad, das geht schneller.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'cykeln', de: 'das Fahrrad' }, { sv: 'i', de: 'an' }, { sv: 'stället', de: 'der Stelle' }, { sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'fortare', de: 'schneller' }], chunkIds: ['c-vitarcykeln'] },
  { id: 's-b2u-cykel2', level: 3, sv: 'Bilen står still i dag, vi tar cykeln i stället.', de: 'Das Auto bleibt heute stehen, wir nehmen stattdessen das Fahrrad.', decoding: [{ sv: 'bilen', de: 'das Auto' }, { sv: 'står', de: 'steht' }, { sv: 'still', de: 'still' }, { sv: 'i', de: 'am' }, { sv: 'dag', de: 'Tag' }, { sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'cykeln', de: 'das Fahrrad' }, { sv: 'i', de: 'an' }, { sv: 'stället', de: 'der Stelle' }], chunkIds: ['c-vitarcykeln'] },
  { id: 's-b2u-ansvar1', level: 3, sv: 'Vem tar ansvar för det, kommunen eller staten?', de: 'Wer übernimmt dafür die Verantwortung, die Gemeinde oder der Staat?', decoding: [{ sv: 'vem', de: 'wer' }, { sv: 'tar', de: 'nimmt' }, { sv: 'ansvar', de: 'Verantwortung' }, { sv: 'för', de: 'für' }, { sv: 'det', de: 'das' }, { sv: 'kommunen', de: 'die Gemeinde' }, { sv: 'eller', de: 'oder' }, { sv: 'staten', de: 'der Staat' }], chunkIds: ['c-vemtaransvar'] },
  { id: 's-b2u-ansvar2', level: 3, sv: 'Vem tar ansvar för det när något går fel?', de: 'Wer übernimmt dafür die Verantwortung, wenn etwas schiefgeht?', decoding: [{ sv: 'vem', de: 'wer' }, { sv: 'tar', de: 'nimmt' }, { sv: 'ansvar', de: 'Verantwortung' }, { sv: 'för', de: 'für' }, { sv: 'det', de: 'das' }, { sv: 'när', de: 'wenn' }, { sv: 'något', de: 'etwas' }, { sv: 'går', de: 'geht' }, { sv: 'fel', de: 'falsch' }], chunkIds: ['c-vemtaransvar'] },
  { id: 's-b2u-mix1', level: 3, sv: 'Klimatet förändras snabbt och utsläppen måste minska.', de: 'Das Klima verändert sich schnell und die Emissionen müssen sinken.', decoding: [{ sv: 'klimatet', de: 'das Klima' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'snabbt', de: 'schnell' }, { sv: 'och', de: 'und' }, { sv: 'utsläppen', de: 'die Emissionen' }, { sv: 'måste', de: 'müssen' }, { sv: 'minska', de: 'sinken' }], chunkIds: ['c-klimatetforandras', 'c-utslappenmasteminska'] },
  { id: 's-b2u-mix2', level: 3, sv: 'Vi måste tänka på miljön, så vi tar cykeln i stället.', de: 'Wir müssen an die Umwelt denken, also nehmen wir stattdessen das Fahrrad.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'miljön', de: 'die Umwelt' }, { sv: 'så', de: 'so' }, { sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'cykeln', de: 'das Fahrrad' }, { sv: 'i', de: 'an' }, { sv: 'stället', de: 'der Stelle' }], chunkIds: ['c-tankapamiljon', 'c-vitarcykeln'] },
  { id: 's-b2u-mix3', level: 3, sv: 'Samhället förändras hela tiden. Vem tar ansvar för det?', de: 'Die Gesellschaft verändert sich ständig. Wer übernimmt dafür die Verantwortung?', decoding: [{ sv: 'samhället', de: 'die Gesellschaft' }, { sv: 'förändras', de: 'verändert sich' }, { sv: 'hela', de: 'die ganze' }, { sv: 'tiden', de: 'die Zeit' }, { sv: 'vem', de: 'wer' }, { sv: 'tar', de: 'nimmt' }, { sv: 'ansvar', de: 'Verantwortung' }, { sv: 'för', de: 'für' }, { sv: 'det', de: 'das' }], chunkIds: ['c-samhalletforandras', 'c-vemtaransvar'] },
  { id: 's-b2u-mix4', level: 3, sv: 'Skatterna är höga här, men det är inte hållbart i längden ändå.', de: 'Die Steuern sind hier hoch, aber tragfähig ist es auf Dauer trotzdem nicht.', decoding: [{ sv: 'skatterna', de: 'die Steuern' }, { sv: 'är', de: 'sind' }, { sv: 'höga', de: 'hohe' }, { sv: 'här', de: 'hier' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'das' }, { sv: 'är', de: 'ist' }, { sv: 'inte', de: 'nicht' }, { sv: 'hållbart', de: 'haltbar' }, { sv: 'i', de: 'auf' }, { sv: 'längden', de: 'die Länge' }, { sv: 'ändå', de: 'trotzdem' }], chunkIds: ['c-skatternaarhoga', 'c-intehallbart'] },

  // ── Verhandeln ────────────────────────────────────────────────────────────
  { id: 's-b2v-pris1', level: 3, sv: 'Kan vi förhandla om priset, om vi tar fler?', de: 'Können wir über den Preis verhandeln, wenn wir mehr nehmen?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'förhandla', de: 'verhandeln' }, { sv: 'om', de: 'über' }, { sv: 'priset', de: 'den Preis' }, { sv: 'om', de: 'wenn' }, { sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'fler', de: 'mehrere' }], chunkIds: ['c-forhandlaompriset'] },
  { id: 's-b2v-pris2', level: 3, sv: 'Kan vi förhandla om priset? Det är lite högt.', de: 'Können wir über den Preis verhandeln? Er ist etwas hoch.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'förhandla', de: 'verhandeln' }, { sv: 'om', de: 'über' }, { sv: 'priset', de: 'den Preis' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'lite', de: 'wenig' }, { sv: 'högt', de: 'hoch' }], chunkIds: ['c-forhandlaompriset'] },
  { id: 's-b2v-kompromiss1', level: 3, sv: 'Jag föreslår en kompromiss: vi delar kostnaden.', de: 'Ich schlage einen Kompromiss vor: wir teilen die Kosten.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'föreslår', de: 'schlage vor' }, { sv: 'en', de: 'einen' }, { sv: 'kompromiss', de: 'Kompromiss' }, { sv: 'vi', de: 'wir' }, { sv: 'delar', de: 'teilen' }, { sv: 'kostnaden', de: 'die Kosten' }], chunkIds: ['c-foreslarkompromiss'] },
  { id: 's-b2v-kompromiss2', level: 3, sv: 'Ingen blir helt nöjd, så jag föreslår en kompromiss.', de: 'Niemand wird ganz zufrieden, also schlage ich einen Kompromiss vor.', decoding: [{ sv: 'ingen', de: 'niemand' }, { sv: 'blir', de: 'wird' }, { sv: 'helt', de: 'ganz' }, { sv: 'nöjd', de: 'zufrieden' }, { sv: 'så', de: 'so' }, { sv: 'jag', de: 'ich' }, { sv: 'föreslår', de: 'schlage vor' }, { sv: 'en', de: 'einen' }, { sv: 'kompromiss', de: 'Kompromiss' }], chunkIds: ['c-foreslarkompromiss'] },
  { id: 's-b2v-villkor1', level: 3, sv: 'Under vilka villkor gäller det?', de: 'Unter welchen Bedingungen gilt das?', decoding: [{ sv: 'under', de: 'unter' }, { sv: 'vilka', de: 'welchen' }, { sv: 'villkor', de: 'Bedingungen' }, { sv: 'gäller', de: 'gilt' }, { sv: 'det', de: 'das' }], chunkIds: ['c-vilkavillkor'] },
  { id: 's-b2v-villkor2', level: 3, sv: 'Under vilka villkor kan vi säga upp avtalet?', de: 'Unter welchen Bedingungen können wir die Vereinbarung kündigen?', decoding: [{ sv: 'under', de: 'unter' }, { sv: 'vilka', de: 'welchen' }, { sv: 'villkor', de: 'Bedingungen' }, { sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'säga', de: 'sagen' }, { sv: 'upp', de: 'auf' }, { sv: 'avtalet', de: 'die Vereinbarung' }], chunkIds: ['c-vilkavillkor'] },
  { id: 's-b2v-budget1', level: 3, sv: 'Det ligger utanför budgeten i år.', de: 'Das liegt dieses Jahr außerhalb des Budgets.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'ligger', de: 'liegt' }, { sv: 'utanför', de: 'außerhalb' }, { sv: 'budgeten', de: 'des Budgets' }, { sv: 'i', de: 'in' }, { sv: 'år', de: 'Jahr' }], chunkIds: ['c-utanforbudgeten'] },
  { id: 's-b2v-budget2', level: 3, sv: 'Förslaget är bra, men det ligger utanför budgeten.', de: 'Der Vorschlag ist gut, aber er liegt außerhalb des Budgets.', decoding: [{ sv: 'förslaget', de: 'der Vorschlag' }, { sv: 'är', de: 'ist' }, { sv: 'bra', de: 'gut' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'das' }, { sv: 'ligger', de: 'liegt' }, { sv: 'utanför', de: 'außerhalb' }, { sv: 'budgeten', de: 'des Budgets' }], chunkIds: ['c-utanforbudgeten'] },
  { id: 's-b2v-leverera1', level: 3, sv: 'När kan ni leverera, före jul?', de: 'Wann könnt ihr liefern, vor Weihnachten?', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'kan', de: 'könnt' }, { sv: 'ni', de: 'ihr' }, { sv: 'leverera', de: 'liefern' }, { sv: 'före', de: 'vor' }, { sv: 'jul', de: 'Weihnachten' }], chunkIds: ['c-narkannileverera'] },
  { id: 's-b2v-leverera2', level: 3, sv: 'När kan ni leverera? Vi behöver det snart.', de: 'Wann könnt ihr liefern? Wir brauchen es bald.', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'kan', de: 'könnt' }, { sv: 'ni', de: 'ihr' }, { sv: 'leverera', de: 'liefern' }, { sv: 'vi', de: 'wir' }, { sv: 'behöver', de: 'brauchen' }, { sv: 'det', de: 'es' }, { sv: 'snart', de: 'bald' }], chunkIds: ['c-narkannileverera'] },
  { id: 's-b2v-avtal1', level: 3, sv: 'Vi har ett avtal, och det gäller.', de: 'Wir haben eine Vereinbarung, und die gilt.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'ett', de: 'eine' }, { sv: 'avtal', de: 'Vereinbarung' }, { sv: 'och', de: 'und' }, { sv: 'det', de: 'sie' }, { sv: 'gäller', de: 'gilt' }], chunkIds: ['c-viharettavtal'] },
  { id: 's-b2v-avtal2', level: 3, sv: 'Vi har ett avtal sedan i fjol.', de: 'Wir haben seit letztem Jahr eine Vereinbarung.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'ett', de: 'eine' }, { sv: 'avtal', de: 'Vereinbarung' }, { sv: 'sedan', de: 'seit' }, { sv: 'i', de: 'im' }, { sv: 'fjol', de: 'Vorjahr' }], chunkIds: ['c-viharettavtal'] },
  { id: 's-b2v-tanka1', level: 3, sv: 'Jag måste tänka på saken över helgen.', de: 'Ich muss übers Wochenende darüber nachdenken.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'saken', de: 'die Sache' }, { sv: 'över', de: 'über' }, { sv: 'helgen', de: 'das Wochenende' }], chunkIds: ['c-mastetankapasaken'] },
  { id: 's-b2v-tanka2', level: 3, sv: 'Jag måste tänka på saken, jag svarar i morgon.', de: 'Ich muss darüber nachdenken, ich antworte morgen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'saken', de: 'die Sache' }, { sv: 'jag', de: 'ich' }, { sv: 'svarar', de: 'antworte' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }], chunkIds: ['c-mastetankapasaken'] },
  { id: 's-b2v-medpa1', level: 3, sv: 'Det går jag med på, om ni levererar i tid.', de: 'Darauf lasse ich mich ein, wenn ihr pünktlich liefert.', decoding: [{ sv: 'det', de: 'dem' }, { sv: 'går', de: 'gehe' }, { sv: 'jag', de: 'ich' }, { sv: 'med', de: 'mit' }, { sv: 'på', de: 'auf' }, { sv: 'om', de: 'wenn' }, { sv: 'ni', de: 'ihr' }, { sv: 'levererar', de: 'liefert' }, { sv: 'i', de: 'in' }, { sv: 'tid', de: 'Zeit' }], chunkIds: ['c-detgarjagmedpa'] },
  { id: 's-b2v-medpa2', level: 3, sv: 'Okej, det går jag med på.', de: 'Okay, darauf lasse ich mich ein.', decoding: [{ sv: 'okej', de: 'okay' }, { sv: 'det', de: 'dem' }, { sv: 'går', de: 'gehe' }, { sv: 'jag', de: 'ich' }, { sv: 'med', de: 'mit' }, { sv: 'på', de: 'auf' }], chunkIds: ['c-detgarjagmedpa'] },
  { id: 's-b2v-mix1', level: 3, sv: 'Kan vi förhandla om priset? Jag föreslår en kompromiss.', de: 'Können wir über den Preis verhandeln? Ich schlage einen Kompromiss vor.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'förhandla', de: 'verhandeln' }, { sv: 'om', de: 'über' }, { sv: 'priset', de: 'den Preis' }, { sv: 'jag', de: 'ich' }, { sv: 'föreslår', de: 'schlage vor' }, { sv: 'en', de: 'einen' }, { sv: 'kompromiss', de: 'Kompromiss' }], chunkIds: ['c-forhandlaompriset', 'c-foreslarkompromiss'] },
  { id: 's-b2v-mix2', level: 3, sv: 'Under vilka villkor? Vi har ett avtal redan.', de: 'Unter welchen Bedingungen? Wir haben schon eine Vereinbarung.', decoding: [{ sv: 'under', de: 'unter' }, { sv: 'vilka', de: 'welchen' }, { sv: 'villkor', de: 'Bedingungen' }, { sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'ett', de: 'eine' }, { sv: 'avtal', de: 'Vereinbarung' }, { sv: 'redan', de: 'schon' }], chunkIds: ['c-vilkavillkor', 'c-viharettavtal'] },
  { id: 's-b2v-mix3', level: 3, sv: 'Det ligger utanför budgeten. Jag måste tänka på saken.', de: 'Das liegt außerhalb des Budgets. Ich muss darüber nachdenken.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'ligger', de: 'liegt' }, { sv: 'utanför', de: 'außerhalb' }, { sv: 'budgeten', de: 'des Budgets' }, { sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'tänka', de: 'denken' }, { sv: 'på', de: 'an' }, { sv: 'saken', de: 'die Sache' }], chunkIds: ['c-utanforbudgeten', 'c-mastetankapasaken'] },
  { id: 's-b2v-mix4', level: 3, sv: 'När kan ni leverera? Då går jag med på det.', de: 'Wann könnt ihr liefern? Dann lasse ich mich darauf ein.', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'kan', de: 'könnt' }, { sv: 'ni', de: 'ihr' }, { sv: 'leverera', de: 'liefern' }, { sv: 'då', de: 'dann' }, { sv: 'går', de: 'gehe' }, { sv: 'jag', de: 'ich' }, { sv: 'med', de: 'mit' }, { sv: 'på', de: 'auf' }, { sv: 'det', de: 'dem' }], chunkIds: ['c-narkannileverera', 'c-detgarjagmedpa'] },

  // ── Erzählen & Zusammenfassen ─────────────────────────────────────────────
  { id: 's-b2e-borjade1', level: 3, sv: 'Det började helt vanligt, en tisdag i mars.', de: 'Es fing ganz normal an, an einem Dienstag im März.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'började', de: 'begann' }, { sv: 'helt', de: 'ganz' }, { sv: 'vanligt', de: 'gewöhnlich' }, { sv: 'en', de: 'einen' }, { sv: 'tisdag', de: 'Dienstag' }, { sv: 'i', de: 'im' }, { sv: 'mars', de: 'März' }], chunkIds: ['c-borjadehelvanligt'] },
  { id: 's-b2e-borjade2', level: 3, sv: 'Det började helt vanligt, ingen anade något.', de: 'Es fing ganz normal an, niemand ahnte etwas.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'började', de: 'begann' }, { sv: 'helt', de: 'ganz' }, { sv: 'vanligt', de: 'gewöhnlich' }, { sv: 'ingen', de: 'niemand' }, { sv: 'anade', de: 'ahnte' }, { sv: 'något', de: 'etwas' }], chunkIds: ['c-borjadehelvanligt'] },
  { id: 's-b2e-plotsligt1', level: 3, sv: 'Plötsligt hände något, alla vände sig om.', de: 'Plötzlich passierte etwas, alle drehten sich um.', decoding: [{ sv: 'plötsligt', de: 'plötzlich' }, { sv: 'hände', de: 'geschah' }, { sv: 'något', de: 'etwas' }, { sv: 'alla', de: 'alle' }, { sv: 'vände', de: 'wandten' }, { sv: 'sig', de: 'sich' }, { sv: 'om', de: 'um' }], chunkIds: ['c-plotsligthande'] },
  { id: 's-b2e-plotsligt2', level: 3, sv: 'Vi väntade i kön, och plötsligt hände något.', de: 'Wir warteten in der Schlange, und plötzlich passierte etwas.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'väntade', de: 'warteten' }, { sv: 'i', de: 'in' }, { sv: 'kön', de: 'der Schlange' }, { sv: 'och', de: 'und' }, { sv: 'plötsligt', de: 'plötzlich' }, { sv: 'hände', de: 'geschah' }, { sv: 'något', de: 'etwas' }], chunkIds: ['c-plotsligthande'] },
  { id: 's-b2e-slut1', level: 3, sv: 'Till slut löste det sig, som det brukar.', de: 'Am Ende hat es sich gelöst, wie meistens.', decoding: [{ sv: 'till', de: 'zu' }, { sv: 'slut', de: 'Schluss' }, { sv: 'löste', de: 'löste' }, { sv: 'det', de: 'es' }, { sv: 'sig', de: 'sich' }, { sv: 'som', de: 'wie' }, { sv: 'det', de: 'es' }, { sv: 'brukar', de: 'pflegt' }], chunkIds: ['c-tillslutlostedetsig'] },
  { id: 's-b2e-slut2', level: 3, sv: 'Det tog en vecka, men till slut löste det sig.', de: 'Es dauerte eine Woche, aber am Ende hat es sich gelöst.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'tog', de: 'nahm' }, { sv: 'en', de: 'eine' }, { sv: 'vecka', de: 'Woche' }, { sv: 'men', de: 'aber' }, { sv: 'till', de: 'zu' }, { sv: 'slut', de: 'Schluss' }, { sv: 'löste', de: 'löste' }, { sv: 'det', de: 'es' }, { sv: 'sig', de: 'sich' }], chunkIds: ['c-tillslutlostedetsig'] },
  { id: 's-b2e-kort1', level: 3, sv: 'Kort sagt gick det bra, trots allt.', de: 'Kurz gesagt ging es gut, trotz allem.', decoding: [{ sv: 'kort', de: 'kurz' }, { sv: 'sagt', de: 'gesagt' }, { sv: 'gick', de: 'ging' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }, { sv: 'trots', de: 'trotz' }, { sv: 'allt', de: 'allem' }], chunkIds: ['c-kortsagtgickdetbra'] },
  { id: 's-b2e-kort2', level: 3, sv: 'Kort sagt gick det bra, och alla var nöjda.', de: 'Kurz gesagt ging es gut, und alle waren zufrieden.', decoding: [{ sv: 'kort', de: 'kurz' }, { sv: 'sagt', de: 'gesagt' }, { sv: 'gick', de: 'ging' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }, { sv: 'och', de: 'und' }, { sv: 'alla', de: 'alle' }, { sv: 'var', de: 'waren' }, { sv: 'nöjda', de: 'zufrieden' }], chunkIds: ['c-kortsagtgickdetbra'] },
  { id: 's-b2e-samtidigt1', level: 3, sv: 'Samtidigt som det hände ringde telefonen.', de: 'Während das geschah, klingelte das Telefon.', decoding: [{ sv: 'samtidigt', de: 'gleichzeitig' }, { sv: 'som', de: 'wie' }, { sv: 'det', de: 'es' }, { sv: 'hände', de: 'geschah' }, { sv: 'ringde', de: 'klingelte' }, { sv: 'telefonen', de: 'das Telefon' }], chunkIds: ['c-samtidigtsomdethande'] },
  { id: 's-b2e-samtidigt2', level: 3, sv: 'Samtidigt som det hände satt jag på tåget.', de: 'Während das geschah, saß ich im Zug.', decoding: [{ sv: 'samtidigt', de: 'gleichzeitig' }, { sv: 'som', de: 'wie' }, { sv: 'det', de: 'es' }, { sv: 'hände', de: 'geschah' }, { sv: 'satt', de: 'saß' }, { sv: 'jag', de: 'ich' }, { sv: 'på', de: 'auf' }, { sv: 'tåget', de: 'dem Zug' }], chunkIds: ['c-samtidigtsomdethande'] },
  { id: 's-b2e-visade1', level: 3, sv: 'Det visade sig vara fel, tyvärr.', de: 'Es stellte sich leider als falsch heraus.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'visade', de: 'zeigte' }, { sv: 'sig', de: 'sich' }, { sv: 'vara', de: 'sein' }, { sv: 'fel', de: 'falsch' }, { sv: 'tyvärr', de: 'leider' }], chunkIds: ['c-detvisadesigvarafel'] },
  { id: 's-b2e-visade2', level: 3, sv: 'Alla trodde på det, men det visade sig vara fel.', de: 'Alle glaubten daran, aber es stellte sich als falsch heraus.', decoding: [{ sv: 'alla', de: 'alle' }, { sv: 'trodde', de: 'glaubten' }, { sv: 'på', de: 'an' }, { sv: 'det', de: 'das' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'es' }, { sv: 'visade', de: 'zeigte' }, { sv: 'sig', de: 'sich' }, { sv: 'vara', de: 'sein' }, { sv: 'fel', de: 'falsch' }], chunkIds: ['c-detvisadesigvarafel'] },
  { id: 's-b2e-minns1', level: 3, sv: 'Jag minns att det regnade hela dagen.', de: 'Ich erinnere mich, dass es den ganzen Tag regnete.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'minns', de: 'erinnere mich' }, { sv: 'att', de: 'dass' }, { sv: 'det', de: 'es' }, { sv: 'regnade', de: 'regnete' }, { sv: 'hela', de: 'den ganzen' }, { sv: 'dagen', de: 'Tag' }], chunkIds: ['c-jagminnsattdetregnade'] },
  { id: 's-b2e-minns2', level: 3, sv: 'Jag minns att det regnade, annars minns jag lite.', de: 'Ich erinnere mich, dass es regnete, sonst erinnere ich mich an wenig.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'minns', de: 'erinnere mich' }, { sv: 'att', de: 'dass' }, { sv: 'det', de: 'es' }, { sv: 'regnade', de: 'regnete' }, { sv: 'annars', de: 'sonst' }, { sv: 'minns', de: 'erinnere' }, { sv: 'jag', de: 'ich' }, { sv: 'lite', de: 'wenig' }], chunkIds: ['c-jagminnsattdetregnade'] },
  { id: 's-b2e-sammanfatta1', level: 3, sv: 'För att sammanfatta: vi fortsätter som förut.', de: 'Um es zusammenzufassen: wir machen weiter wie bisher.', decoding: [{ sv: 'för', de: 'für' }, { sv: 'att', de: 'zu' }, { sv: 'sammanfatta', de: 'zusammenfassen' }, { sv: 'vi', de: 'wir' }, { sv: 'fortsätter', de: 'fahren fort' }, { sv: 'som', de: 'wie' }, { sv: 'förut', de: 'vorher' }], chunkIds: ['c-forattsammanfatta'] },
  { id: 's-b2e-sammanfatta2', level: 3, sv: 'För att sammanfatta det hela kort.', de: 'Um das Ganze kurz zusammenzufassen.', decoding: [{ sv: 'för', de: 'für' }, { sv: 'att', de: 'zu' }, { sv: 'sammanfatta', de: 'zusammenfassen' }, { sv: 'det', de: 'das' }, { sv: 'hela', de: 'Ganze' }, { sv: 'kort', de: 'kurz' }], chunkIds: ['c-forattsammanfatta'] },
  { id: 's-b2e-mix1', level: 3, sv: 'Det började helt vanligt, men plötsligt hände något.', de: 'Es fing ganz normal an, aber plötzlich passierte etwas.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'började', de: 'begann' }, { sv: 'helt', de: 'ganz' }, { sv: 'vanligt', de: 'gewöhnlich' }, { sv: 'men', de: 'aber' }, { sv: 'plötsligt', de: 'plötzlich' }, { sv: 'hände', de: 'geschah' }, { sv: 'något', de: 'etwas' }], chunkIds: ['c-borjadehelvanligt', 'c-plotsligthande'] },
  { id: 's-b2e-mix2', level: 3, sv: 'Det visade sig vara fel, men till slut löste det sig.', de: 'Es stellte sich als falsch heraus, aber am Ende hat es sich gelöst.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'visade', de: 'zeigte' }, { sv: 'sig', de: 'sich' }, { sv: 'vara', de: 'sein' }, { sv: 'fel', de: 'falsch' }, { sv: 'men', de: 'aber' }, { sv: 'till', de: 'zu' }, { sv: 'slut', de: 'Schluss' }, { sv: 'löste', de: 'löste' }, { sv: 'det', de: 'es' }, { sv: 'sig', de: 'sich' }], chunkIds: ['c-detvisadesigvarafel', 'c-tillslutlostedetsig'] },
  { id: 's-b2e-mix3', level: 3, sv: 'Jag minns att det regnade samtidigt som det hände.', de: 'Ich erinnere mich, dass es regnete, während das geschah.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'minns', de: 'erinnere mich' }, { sv: 'att', de: 'dass' }, { sv: 'det', de: 'es' }, { sv: 'regnade', de: 'regnete' }, { sv: 'samtidigt', de: 'gleichzeitig' }, { sv: 'som', de: 'wie' }, { sv: 'det', de: 'es' }, { sv: 'hände', de: 'geschah' }], chunkIds: ['c-jagminnsattdetregnade', 'c-samtidigtsomdethande'] },
  { id: 's-b2e-mix4', level: 3, sv: 'För att sammanfatta: kort sagt gick det bra.', de: 'Um es zusammenzufassen: kurz gesagt ging es gut.', decoding: [{ sv: 'för', de: 'für' }, { sv: 'att', de: 'zu' }, { sv: 'sammanfatta', de: 'zusammenfassen' }, { sv: 'kort', de: 'kurz' }, { sv: 'sagt', de: 'gesagt' }, { sv: 'gick', de: 'ging' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }], chunkIds: ['c-forattsammanfatta', 'c-kortsagtgickdetbra'] },

  // ── Nuancen ───────────────────────────────────────────────────────────────
  { id: 's-b2n-skillnad1', level: 3, sv: 'Skillnaden är liten men viktig i det här fallet.', de: 'Der Unterschied ist klein, aber in diesem Fall wichtig.', decoding: [{ sv: 'skillnaden', de: 'der Unterschied' }, { sv: 'är', de: 'ist' }, { sv: 'liten', de: 'klein' }, { sv: 'men', de: 'aber' }, { sv: 'viktig', de: 'wichtig' }, { sv: 'i', de: 'in' }, { sv: 'det', de: 'dem' }, { sv: 'här', de: 'hier' }, { sv: 'fallet', de: 'Fall' }], chunkIds: ['c-skillnadenarliten'] },
  { id: 's-b2n-skillnad2', level: 3, sv: 'Orden liknar varandra, skillnaden är liten men viktig.', de: 'Die Wörter ähneln einander, der Unterschied ist klein, aber wichtig.', decoding: [{ sv: 'orden', de: 'die Wörter' }, { sv: 'liknar', de: 'ähneln' }, { sv: 'varandra', de: 'einander' }, { sv: 'skillnaden', de: 'der Unterschied' }, { sv: 'är', de: 'ist' }, { sv: 'liten', de: 'klein' }, { sv: 'men', de: 'aber' }, { sv: 'viktig', de: 'wichtig' }], chunkIds: ['c-skillnadenarliten'] },
  { id: 's-b2n-hardare1', level: 3, sv: 'Det låter hårdare än jag menar, förlåt.', de: 'Das klingt härter, als ich es meine, entschuldige.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'låter', de: 'klingt' }, { sv: 'hårdare', de: 'härter' }, { sv: 'än', de: 'als' }, { sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }, { sv: 'förlåt', de: 'verzeih' }], chunkIds: ['c-laterhardare'] },
  { id: 's-b2n-hardare2', level: 3, sv: 'På svenska låter det hårdare än jag menar.', de: 'Auf Schwedisch klingt es härter, als ich es meine.', decoding: [{ sv: 'på', de: 'auf' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'låter', de: 'klingt' }, { sv: 'det', de: 'es' }, { sv: 'hårdare', de: 'härter' }, { sv: 'än', de: 'als' }, { sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }], chunkIds: ['c-laterhardare'] },
  { id: 's-b2n-snarare1', level: 3, sv: 'Jag menar snarare tvärtom, om jag får förklara.', de: 'Ich meine eher das Gegenteil, wenn ich erklären darf.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }, { sv: 'snarare', de: 'eher' }, { sv: 'tvärtom', de: 'umgekehrt' }, { sv: 'om', de: 'wenn' }, { sv: 'jag', de: 'ich' }, { sv: 'får', de: 'darf' }, { sv: 'förklara', de: 'erklären' }], chunkIds: ['c-menarsnarare'] },
  { id: 's-b2n-snarare2', level: 3, sv: 'Nej, jag menar snarare tvärtom.', de: 'Nein, ich meine eher das Gegenteil.', decoding: [{ sv: 'nej', de: 'nein' }, { sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }, { sv: 'snarare', de: 'eher' }, { sv: 'tvärtom', de: 'umgekehrt' }], chunkIds: ['c-menarsnarare'] },
  { id: 's-b2n-uttryck1', level: 3, sv: 'Uttrycket betyder något annat på svenska.', de: 'Der Ausdruck bedeutet auf Schwedisch etwas anderes.', decoding: [{ sv: 'uttrycket', de: 'der Ausdruck' }, { sv: 'betyder', de: 'bedeutet' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }, { sv: 'på', de: 'auf' }, { sv: 'svenska', de: 'Schwedisch' }], chunkIds: ['c-uttrycketbetyderannat'] },
  { id: 's-b2n-uttryck2', level: 3, sv: 'Var försiktig, uttrycket betyder något annat här.', de: 'Sei vorsichtig, der Ausdruck bedeutet hier etwas anderes.', decoding: [{ sv: 'var', de: 'sei' }, { sv: 'försiktig', de: 'vorsichtig' }, { sv: 'uttrycket', de: 'der Ausdruck' }, { sv: 'betyder', de: 'bedeutet' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }, { sv: 'här', de: 'hier' }], chunkIds: ['c-uttrycketbetyderannat'] },
  { id: 's-b2n-bokstavligt1', level: 3, sv: 'Bokstavligt talat betyder det något annat.', de: 'Wörtlich genommen bedeutet es etwas anderes.', decoding: [{ sv: 'bokstavligt', de: 'buchstäblich' }, { sv: 'talat', de: 'gesprochen' }, { sv: 'betyder', de: 'bedeutet' }, { sv: 'det', de: 'es' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }], chunkIds: ['c-bokstavligttalat', 'c-uttrycketbetyderannat'] },
  { id: 's-b2n-bokstavligt2', level: 3, sv: 'Ta det inte bokstavligt talat.', de: 'Nimm es nicht wörtlich.', decoding: [{ sv: 'ta', de: 'nimm' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }, { sv: 'bokstavligt', de: 'buchstäblich' }, { sv: 'talat', de: 'gesprochen' }], chunkIds: ['c-bokstavligttalat'] },
  { id: 's-b2n-hur1', level: 3, sv: 'Det beror på hur man säger det, inte vad man säger.', de: 'Es kommt darauf an, wie man es sagt, nicht was man sagt.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'beror', de: 'beruht' }, { sv: 'på', de: 'auf' }, { sv: 'hur', de: 'wie' }, { sv: 'man', de: 'man' }, { sv: 'säger', de: 'sagt' }, { sv: 'det', de: 'es' }, { sv: 'inte', de: 'nicht' }, { sv: 'vad', de: 'was' }, { sv: 'man', de: 'man' }, { sv: 'säger', de: 'sagt' }], chunkIds: ['c-berorpahurmansager'] },
  { id: 's-b2n-hur2', level: 3, sv: 'Tonen avgör: det beror på hur man säger det.', de: 'Der Ton entscheidet: es kommt darauf an, wie man es sagt.', decoding: [{ sv: 'tonen', de: 'der Ton' }, { sv: 'avgör', de: 'entscheidet' }, { sv: 'det', de: 'es' }, { sv: 'beror', de: 'beruht' }, { sv: 'på', de: 'auf' }, { sv: 'hur', de: 'wie' }, { sv: 'man', de: 'man' }, { sv: 'säger', de: 'sagt' }, { sv: 'det', de: 'es' }], chunkIds: ['c-berorpahurmansager'] },
  { id: 's-b2n-fel1', level: 3, sv: 'Jag uttrycker mig kanske fel, men du förstår nog.', de: 'Ich drücke mich vielleicht falsch aus, aber du verstehst schon.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'uttrycker', de: 'drücke aus' }, { sv: 'mig', de: 'mich' }, { sv: 'kanske', de: 'vielleicht' }, { sv: 'fel', de: 'falsch' }, { sv: 'men', de: 'aber' }, { sv: 'du', de: 'du' }, { sv: 'förstår', de: 'verstehst' }, { sv: 'nog', de: 'wohl' }], chunkIds: ['c-uttryckermigfel'] },
  { id: 's-b2n-fel2', level: 3, sv: 'Jag uttrycker mig kanske fel på svenska.', de: 'Ich drücke mich auf Schwedisch vielleicht falsch aus.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'uttrycker', de: 'drücke aus' }, { sv: 'mig', de: 'mich' }, { sv: 'kanske', de: 'vielleicht' }, { sv: 'fel', de: 'falsch' }, { sv: 'på', de: 'auf' }, { sv: 'svenska', de: 'Schwedisch' }], chunkIds: ['c-uttryckermigfel'] },
  { id: 's-b2n-rader1', level: 3, sv: 'Man får läsa mellan raderna här.', de: 'Man muss hier zwischen den Zeilen lesen.', decoding: [{ sv: 'man', de: 'man' }, { sv: 'får', de: 'darf' }, { sv: 'läsa', de: 'lesen' }, { sv: 'mellan', de: 'zwischen' }, { sv: 'raderna', de: 'den Zeilen' }, { sv: 'här', de: 'hier' }], chunkIds: ['c-lasamellanraderna'] },
  { id: 's-b2n-rader2', level: 3, sv: 'Han säger inte nej, man får läsa mellan raderna.', de: 'Er sagt nicht nein, man muss zwischen den Zeilen lesen.', decoding: [{ sv: 'han', de: 'er' }, { sv: 'säger', de: 'sagt' }, { sv: 'inte', de: 'nicht' }, { sv: 'nej', de: 'nein' }, { sv: 'man', de: 'man' }, { sv: 'får', de: 'darf' }, { sv: 'läsa', de: 'lesen' }, { sv: 'mellan', de: 'zwischen' }, { sv: 'raderna', de: 'den Zeilen' }], chunkIds: ['c-lasamellanraderna'] },
  { id: 's-b2n-mix1', level: 3, sv: 'Skillnaden är liten men viktig, det låter hårdare än jag menar.', de: 'Der Unterschied ist klein, aber wichtig — das klingt härter, als ich es meine.', decoding: [{ sv: 'skillnaden', de: 'der Unterschied' }, { sv: 'är', de: 'ist' }, { sv: 'liten', de: 'klein' }, { sv: 'men', de: 'aber' }, { sv: 'viktig', de: 'wichtig' }, { sv: 'det', de: 'das' }, { sv: 'låter', de: 'klingt' }, { sv: 'hårdare', de: 'härter' }, { sv: 'än', de: 'als' }, { sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }], chunkIds: ['c-skillnadenarliten', 'c-laterhardare'] },
  { id: 's-b2n-mix2', level: 3, sv: 'Jag menar snarare tvärtom, jag uttrycker mig kanske fel.', de: 'Ich meine eher das Gegenteil, ich drücke mich vielleicht falsch aus.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'menar', de: 'meine' }, { sv: 'snarare', de: 'eher' }, { sv: 'tvärtom', de: 'umgekehrt' }, { sv: 'jag', de: 'ich' }, { sv: 'uttrycker', de: 'drücke aus' }, { sv: 'mig', de: 'mich' }, { sv: 'kanske', de: 'vielleicht' }, { sv: 'fel', de: 'falsch' }], chunkIds: ['c-menarsnarare', 'c-uttryckermigfel'] },
  { id: 's-b2n-mix3', level: 3, sv: 'Det beror på hur man säger det, man får läsa mellan raderna.', de: 'Es kommt darauf an, wie man es sagt — man muss zwischen den Zeilen lesen.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'beror', de: 'beruht' }, { sv: 'på', de: 'auf' }, { sv: 'hur', de: 'wie' }, { sv: 'man', de: 'man' }, { sv: 'säger', de: 'sagt' }, { sv: 'det', de: 'es' }, { sv: 'man', de: 'man' }, { sv: 'får', de: 'darf' }, { sv: 'läsa', de: 'lesen' }, { sv: 'mellan', de: 'zwischen' }, { sv: 'raderna', de: 'den Zeilen' }], chunkIds: ['c-berorpahurmansager', 'c-lasamellanraderna'] },
  { id: 's-b2n-mix4', level: 3, sv: 'Uttrycket betyder något annat, bokstavligt talat.', de: 'Der Ausdruck bedeutet etwas anderes, wörtlich genommen.', decoding: [{ sv: 'uttrycket', de: 'der Ausdruck' }, { sv: 'betyder', de: 'bedeutet' }, { sv: 'något', de: 'etwas' }, { sv: 'annat', de: 'anderes' }, { sv: 'bokstavligt', de: 'buchstäblich' }, { sv: 'talat', de: 'gesprochen' }], chunkIds: ['c-uttrycketbetyderannat', 'c-bokstavligttalat'] },

  // ── Redewendungen ─────────────────────────────────────────────────────────
  { id: 's-b2i-ko1', level: 3, sv: 'Ta det lugnt, det är ingen ko på isen.', de: 'Immer mit der Ruhe, es eilt nicht.', decoding: [{ sv: 'ta', de: 'nimm' }, { sv: 'det', de: 'es' }, { sv: 'lugnt', de: 'ruhig' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'ingen', de: 'keine' }, { sv: 'ko', de: 'Kuh' }, { sv: 'på', de: 'auf' }, { sv: 'isen', de: 'dem Eis' }], chunkIds: ['c-ingenkopaisen'] },
  { id: 's-b2i-ko2', level: 3, sv: 'Det är ingen ko på isen, vi hinner i morgon.', de: 'Es eilt nicht, wir schaffen es morgen.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'ingen', de: 'keine' }, { sv: 'ko', de: 'Kuh' }, { sv: 'på', de: 'auf' }, { sv: 'isen', de: 'dem Eis' }, { sv: 'vi', de: 'wir' }, { sv: 'hinner', de: 'schaffen' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }], chunkIds: ['c-ingenkopaisen'] },
  { id: 's-b2i-hund1', level: 3, sv: 'Priset är för lågt — här ligger en hund begraven.', de: 'Der Preis ist zu niedrig — da stimmt etwas nicht.', decoding: [{ sv: 'priset', de: 'der Preis' }, { sv: 'är', de: 'ist' }, { sv: 'för', de: 'zu' }, { sv: 'lågt', de: 'niedrig' }, { sv: 'här', de: 'hier' }, { sv: 'ligger', de: 'liegt' }, { sv: 'en', de: 'ein' }, { sv: 'hund', de: 'Hund' }, { sv: 'begraven', de: 'begraben' }], chunkIds: ['c-hundbegraven'] },
  { id: 's-b2i-hund2', level: 3, sv: 'Här ligger en hund begraven, tro mig.', de: 'Da stimmt etwas nicht, glaub mir.', decoding: [{ sv: 'här', de: 'hier' }, { sv: 'ligger', de: 'liegt' }, { sv: 'en', de: 'ein' }, { sv: 'hund', de: 'Hund' }, { sv: 'begraven', de: 'begraben' }, { sv: 'tro', de: 'glaube' }, { sv: 'mig', de: 'mir' }], chunkIds: ['c-hundbegraven'] },
  { id: 's-b2i-lagom1', level: 3, sv: 'Inte för mycket, inte för lite — lagom är bäst.', de: 'Nicht zu viel, nicht zu wenig — das rechte Maß ist am besten.', decoding: [{ sv: 'inte', de: 'nicht' }, { sv: 'för', de: 'zu' }, { sv: 'mycket', de: 'viel' }, { sv: 'inte', de: 'nicht' }, { sv: 'för', de: 'zu' }, { sv: 'lite', de: 'wenig' }, { sv: 'lagom', de: 'gerade genug' }, { sv: 'är', de: 'ist' }, { sv: 'bäst', de: 'am besten' }], chunkIds: ['c-lagomarbast'] },
  { id: 's-b2i-lagom2', level: 3, sv: 'Som vi säger här: lagom är bäst.', de: 'Wie wir hier sagen: das rechte Maß ist am besten.', decoding: [{ sv: 'som', de: 'wie' }, { sv: 'vi', de: 'wir' }, { sv: 'säger', de: 'sagen' }, { sv: 'här', de: 'hier' }, { sv: 'lagom', de: 'gerade genug' }, { sv: 'är', de: 'ist' }, { sv: 'bäst', de: 'am besten' }], chunkIds: ['c-lagomarbast'] },
  { id: 's-b2i-taket1', level: 3, sv: 'Ingen fara på taket, jag fixar det.', de: 'Kein Grund zur Sorge, ich mache das.', decoding: [{ sv: 'ingen', de: 'keine' }, { sv: 'fara', de: 'Gefahr' }, { sv: 'på', de: 'auf' }, { sv: 'taket', de: 'dem Dach' }, { sv: 'jag', de: 'ich' }, { sv: 'fixar', de: 'richte' }, { sv: 'det', de: 'es' }], chunkIds: ['c-ingenfarapataket'] },
  { id: 's-b2i-taket2', level: 3, sv: 'Ingen fara på taket, det löser sig alltid.', de: 'Kein Grund zur Sorge, es löst sich immer.', decoding: [{ sv: 'ingen', de: 'keine' }, { sv: 'fara', de: 'Gefahr' }, { sv: 'på', de: 'auf' }, { sv: 'taket', de: 'dem Dach' }, { sv: 'det', de: 'es' }, { sv: 'löser', de: 'löst' }, { sv: 'sig', de: 'sich' }, { sv: 'alltid', de: 'immer' }], chunkIds: ['c-ingenfarapataket'] },
  { id: 's-b2i-hemma1', level: 3, sv: 'Resan var fin, men borta bra men hemma bäst.', de: 'Die Reise war schön, aber daheim ist es doch am schönsten.', decoding: [{ sv: 'resan', de: 'die Reise' }, { sv: 'var', de: 'war' }, { sv: 'fin', de: 'schön' }, { sv: 'men', de: 'aber' }, { sv: 'borta', de: 'weg' }, { sv: 'bra', de: 'gut' }, { sv: 'men', de: 'aber' }, { sv: 'hemma', de: 'daheim' }, { sv: 'bäst', de: 'am besten' }], chunkIds: ['c-bortabrahemmabast'] },
  { id: 's-b2i-hemma2', level: 3, sv: 'Nu är jag hemma igen: borta bra men hemma bäst.', de: 'Jetzt bin ich wieder daheim: daheim ist es doch am schönsten.', decoding: [{ sv: 'nu', de: 'jetzt' }, { sv: 'är', de: 'bin' }, { sv: 'jag', de: 'ich' }, { sv: 'hemma', de: 'daheim' }, { sv: 'igen', de: 'wieder' }, { sv: 'borta', de: 'weg' }, { sv: 'bra', de: 'gut' }, { sv: 'men', de: 'aber' }, { sv: 'hemma', de: 'daheim' }, { sv: 'bäst', de: 'am besten' }], chunkIds: ['c-bortabrahemmabast'] },
  { id: 's-b2i-sent1', level: 3, sv: 'Svaret kom i dag, bättre sent än aldrig.', de: 'Die Antwort kam heute, besser spät als nie.', decoding: [{ sv: 'svaret', de: 'die Antwort' }, { sv: 'kom', de: 'kam' }, { sv: 'i', de: 'am' }, { sv: 'dag', de: 'Tag' }, { sv: 'bättre', de: 'besser' }, { sv: 'sent', de: 'spät' }, { sv: 'än', de: 'als' }, { sv: 'aldrig', de: 'nie' }], chunkIds: ['c-battresentanaldrig'] },
  { id: 's-b2i-sent2', level: 3, sv: 'Bättre sent än aldrig, sa han och skrattade.', de: 'Besser spät als nie, sagte er und lachte.', decoding: [{ sv: 'bättre', de: 'besser' }, { sv: 'sent', de: 'spät' }, { sv: 'än', de: 'als' }, { sv: 'aldrig', de: 'nie' }, { sv: 'sa', de: 'sagte' }, { sv: 'han', de: 'er' }, { sv: 'och', de: 'und' }, { sv: 'skrattade', de: 'lachte' }], chunkIds: ['c-battresentanaldrig'] },
  { id: 's-b2i-ovning1', level: 3, sv: 'Övning ger färdighet, säger min lärare.', de: 'Übung macht den Meister, sagt meine Lehrkraft.', decoding: [{ sv: 'övning', de: 'Übung' }, { sv: 'ger', de: 'gibt' }, { sv: 'färdighet', de: 'Fertigkeit' }, { sv: 'säger', de: 'sagt' }, { sv: 'min', de: 'meine' }, { sv: 'lärare', de: 'Lehrkraft' }], chunkIds: ['c-ovninggerfardighet'] },
  { id: 's-b2i-ovning2', level: 3, sv: 'Jag övar varje dag: övning ger färdighet.', de: 'Ich übe jeden Tag: Übung macht den Meister.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'övar', de: 'übe' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }, { sv: 'övning', de: 'Übung' }, { sv: 'ger', de: 'gibt' }, { sv: 'färdighet', de: 'Fertigkeit' }], chunkIds: ['c-ovninggerfardighet', 'c-ovarvarjedag'] },
  { id: 's-b2i-droppen1', level: 3, sv: 'Det var droppen, nu säger jag upp mig.', de: 'Das war zu viel des Guten, jetzt kündige ich.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'droppen', de: 'der Tropfen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'säger', de: 'sage' }, { sv: 'jag', de: 'ich' }, { sv: 'upp', de: 'auf' }, { sv: 'mig', de: 'mich' }], chunkIds: ['c-detvardroppen'] },
  { id: 's-b2i-droppen2', level: 3, sv: 'Tåget var sent igen — det var droppen.', de: 'Der Zug war wieder spät — das war zu viel des Guten.', decoding: [{ sv: 'tåget', de: 'der Zug' }, { sv: 'var', de: 'war' }, { sv: 'sent', de: 'spät' }, { sv: 'igen', de: 'wieder' }, { sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'droppen', de: 'der Tropfen' }], chunkIds: ['c-detvardroppen'] },
  { id: 's-b2i-mix1', level: 3, sv: 'Det är ingen ko på isen, ingen fara på taket.', de: 'Es eilt nicht, kein Grund zur Sorge.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'ingen', de: 'keine' }, { sv: 'ko', de: 'Kuh' }, { sv: 'på', de: 'auf' }, { sv: 'isen', de: 'dem Eis' }, { sv: 'ingen', de: 'keine' }, { sv: 'fara', de: 'Gefahr' }, { sv: 'på', de: 'auf' }, { sv: 'taket', de: 'dem Dach' }], chunkIds: ['c-ingenkopaisen', 'c-ingenfarapataket'] },
  { id: 's-b2i-mix2', level: 3, sv: 'Lagom är bäst, och borta bra men hemma bäst.', de: 'Das rechte Maß ist am besten, und daheim ist es doch am schönsten.', decoding: [{ sv: 'lagom', de: 'gerade genug' }, { sv: 'är', de: 'ist' }, { sv: 'bäst', de: 'am besten' }, { sv: 'och', de: 'und' }, { sv: 'borta', de: 'weg' }, { sv: 'bra', de: 'gut' }, { sv: 'men', de: 'aber' }, { sv: 'hemma', de: 'daheim' }, { sv: 'bäst', de: 'am besten' }], chunkIds: ['c-lagomarbast', 'c-bortabrahemmabast'] },
  { id: 's-b2i-mix3', level: 3, sv: 'Här ligger en hund begraven, och det var droppen.', de: 'Da stimmt etwas nicht, und das war zu viel des Guten.', decoding: [{ sv: 'här', de: 'hier' }, { sv: 'ligger', de: 'liegt' }, { sv: 'en', de: 'ein' }, { sv: 'hund', de: 'Hund' }, { sv: 'begraven', de: 'begraben' }, { sv: 'och', de: 'und' }, { sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'droppen', de: 'der Tropfen' }], chunkIds: ['c-hundbegraven', 'c-detvardroppen'] },
  { id: 's-b2i-mix4', level: 3, sv: 'Bättre sent än aldrig — övning ger färdighet.', de: 'Besser spät als nie — Übung macht den Meister.', decoding: [{ sv: 'bättre', de: 'besser' }, { sv: 'sent', de: 'spät' }, { sv: 'än', de: 'als' }, { sv: 'aldrig', de: 'nie' }, { sv: 'övning', de: 'Übung' }, { sv: 'ger', de: 'gibt' }, { sv: 'färdighet', de: 'Fertigkeit' }], chunkIds: ['c-battresentanaldrig', 'c-ovninggerfardighet'] },
];
