// Gespräche für „Die ersten Wörter".
//
// Beide Szenen sind bewusst kurz und bestehen fast nur aus Ein-Wort-Antworten:
// Wer sechzehn Wörter kann, soll SOFORT merken, dass er damit schon ein
// Gespräch führen kann. Genau das ist der Unterschied zwischen einer
// Vokabelliste und einer Sprache.

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-fw-morgon',
    categoryId: 'cat-first-words',
    title: 'Guten Morgen: die ersten Wörter im Einsatz',
    blurb: 'Frühstück am Küchentisch — du kommst mit acht Wörtern durch.',
    scene: 'home',
    partnerName: 'Mitbewohnerin',
    turns: [
      {
        id: 'fm1',
        speaker: 'partner',
        sv: 'God morgon {name}!',
        de: 'Guten Morgen {name}!',
        listenFirst: true,
        decoding: [
          { sv: 'god', de: 'guten' },
          { sv: 'morgon', de: 'Morgen' },
        ],
      },
      { id: 'fm2', speaker: 'you', sv: 'god morgon', de: 'guten Morgen', chunkId: 'c-fw-godmorgon' },
      {
        id: 'fm3',
        speaker: 'partner',
        sv: 'Kaffe?',
        de: 'Kaffee?',
        decoding: [{ sv: 'kaffe', de: 'Kaffee' }],
      },
      { id: 'fm4', speaker: 'you', sv: 'ja', de: 'ja', chunkId: 'c-fw-ja' },
      {
        id: 'fm5',
        speaker: 'partner',
        sv: 'Här. Mjölk också?',
        de: 'Hier. Milch auch?',
        decoding: [
          { sv: 'här', de: 'hier' },
          { sv: 'mjölk', de: 'Milch' },
          { sv: 'också', de: 'auch' },
        ],
      },
      { id: 'fm6', speaker: 'you', sv: 'nej', de: 'nein', chunkId: 'c-fw-nej' },
      {
        id: 'fm7',
        speaker: 'partner',
        sv: 'Okej. Varsågod.',
        de: 'Okay. Bitte sehr.',
        decoding: [
          { sv: 'okej', de: 'okay' },
          { sv: 'varsågod', de: 'bitte sehr' },
        ],
      },
      { id: 'fm8', speaker: 'you', sv: 'tack', de: 'danke', chunkId: 'c-fw-tack' },
      {
        id: 'fm9',
        speaker: 'partner',
        sv: 'Titta, solen är uppe redan.',
        de: 'Schau, die Sonne ist schon oben.',
        decoding: [
          { sv: 'titta', de: 'schau' },
          { sv: 'solen', de: 'die Sonne' },
          { sv: 'är', de: 'ist' },
          { sv: 'uppe', de: 'oben' },
          { sv: 'redan', de: 'schon' },
        ],
      },
      { id: 'fm10', speaker: 'you', sv: 'jättebra', de: 'super', chunkId: 'c-fw-jattebra' },
      {
        id: 'fm11',
        speaker: 'partner',
        sv: 'Vill du gå ut sedan?',
        de: 'Willst du nachher rausgehen?',
        decoding: [
          { sv: 'vill', de: 'willst' },
          { sv: 'du', de: 'du' },
          { sv: 'gå', de: 'gehen' },
          { sv: 'ut', de: 'raus' },
          { sv: 'sedan', de: 'danach' },
        ],
      },
      { id: 'fm12', speaker: 'you', sv: 'gärna', de: 'gern', chunkId: 'c-fw-garna' },
      {
        id: 'fm13',
        speaker: 'partner',
        sv: 'Bra. Om en timme?',
        de: 'Gut. In einer Stunde?',
        decoding: [
          { sv: 'bra', de: 'gut' },
          { sv: 'om', de: 'in' },
          { sv: 'en', de: 'einer' },
          { sv: 'timme', de: 'Stunde' },
        ],
      },
      { id: 'fm14', speaker: 'you', sv: 'kanske', de: 'vielleicht', chunkId: 'c-fw-kanske' },
      {
        id: 'fm15',
        speaker: 'partner',
        sv: 'Haha, okej. Säg till bara.',
        de: 'Haha, okay. Sag einfach Bescheid.',
        decoding: [
          { sv: 'haha', de: 'haha' },
          { sv: 'okej', de: 'okay' },
          { sv: 'säg', de: 'sag' },
          { sv: 'till', de: 'zu' },
          { sv: 'bara', de: 'nur' },
        ],
      },
    ],
  },
  {
    id: 'dlg-fw-dorren',
    categoryId: 'cat-first-words',
    title: 'An der Tür: hallo, warte, bitte',
    blurb: 'Jemand klingelt. Acht kurze Wörter reichen für die ganze Szene.',
    scene: 'street',
    partnerName: 'Nachbar',
    turns: [
      {
        id: 'fd1',
        speaker: 'partner',
        sv: 'Hallå? Är någon hemma?',
        de: 'Hallo? Ist jemand zu Hause?',
        listenFirst: true,
        decoding: [
          { sv: 'hallå', de: 'hallo' },
          { sv: 'är', de: 'ist' },
          { sv: 'någon', de: 'jemand' },
          { sv: 'hemma', de: 'daheim' },
        ],
      },
      { id: 'fd2', speaker: 'you', sv: 'hej', de: 'hallo', chunkId: 'c-fw-hej' },
      {
        id: 'fd3',
        speaker: 'partner',
        sv: 'Hej! Jag är din granne.',
        de: 'Hallo! Ich bin dein Nachbar.',
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'jag', de: 'ich' },
          { sv: 'är', de: 'bin' },
          { sv: 'din', de: 'dein' },
          { sv: 'granne', de: 'Nachbar' },
        ],
      },
      {
        id: 'fd4',
        speaker: 'partner',
        sv: 'Har du en skruvmejsel?',
        de: 'Hast du einen Schraubenzieher?',
        decoding: [
          { sv: 'har', de: 'hast' },
          { sv: 'du', de: 'du' },
          { sv: 'en', de: 'einen' },
          { sv: 'skruvmejsel', de: 'Schraubenzieher' },
        ],
      },
      { id: 'fd5', speaker: 'you', sv: 'vänta', de: 'warte', chunkId: 'c-fw-vanta' },
      {
        id: 'fd6',
        speaker: 'partner',
        sv: 'Visst, ingen brådska.',
        de: 'Klar, keine Eile.',
        decoding: [
          { sv: 'visst', de: 'klar' },
          { sv: 'ingen', de: 'keine' },
          { sv: 'brådska', de: 'Eile' },
        ],
      },
      {
        id: 'fd7',
        speaker: 'partner',
        sv: 'Hittade du en skruvmejsel?',
        de: 'Hast du einen Schraubenzieher gefunden?',
        decoding: [
          { sv: 'hittade', de: 'fandest' },
          { sv: 'du', de: 'du' },
          { sv: 'en', de: 'einen' },
          { sv: 'skruvmejsel', de: 'Schraubenzieher' },
        ],
      },
      { id: 'fd8', speaker: 'you', sv: 'tyvärr', de: 'leider', chunkId: 'c-fw-tyvarr' },
      {
        id: 'fd9',
        speaker: 'partner',
        sv: 'Ingen fara. Jag frågar Erik.',
        de: 'Kein Problem. Ich frage Erik.',
        decoding: [
          { sv: 'ingen', de: 'kein' },
          { sv: 'fara', de: 'Gefahr' },
          { sv: 'jag', de: 'ich' },
          { sv: 'frågar', de: 'frage' },
          { sv: 'erik', de: 'Erik' },
        ],
      },
      {
        id: 'fd10',
        speaker: 'partner',
        sv: 'Kan du säga till om du hittar en?',
        de: 'Kannst du Bescheid sagen, wenn du einen findest?',
        decoding: [
          { sv: 'kan', de: 'kannst' },
          { sv: 'du', de: 'du' },
          { sv: 'säga', de: 'sagen' },
          { sv: 'till', de: 'zu' },
          { sv: 'om', de: 'wenn' },
          { sv: 'du', de: 'du' },
          { sv: 'hittar', de: 'findest' },
          { sv: 'en', de: 'einen' },
        ],
      },
      { id: 'fd11', speaker: 'you', sv: 'visst', de: 'klar', chunkId: 'c-fw-visst' },
      {
        id: 'fd12',
        speaker: 'partner',
        sv: 'Tack! Då ses vi.',
        de: 'Danke! Dann sehen wir uns.',
        decoding: [
          { sv: 'tack', de: 'danke' },
          { sv: 'då', de: 'dann' },
          { sv: 'ses', de: 'sehen' },
          { sv: 'vi', de: 'wir' },
        ],
      },
      { id: 'fd13', speaker: 'you', sv: 'hallå', de: 'hallo?', chunkId: 'c-fw-hallo' },
      {
        id: 'fd14',
        speaker: 'partner',
        sv: 'Ja? Sa du något?',
        de: 'Ja? Hast du etwas gesagt?',
        decoding: [
          { sv: 'ja', de: 'ja' },
          { sv: 'sa', de: 'sagtest' },
          { sv: 'du', de: 'du' },
          { sv: 'något', de: 'etwas' },
        ],
      },
      { id: 'fd15', speaker: 'you', sv: 'kom', de: 'komm', chunkId: 'c-fw-kom' },
      {
        id: 'fd16',
        speaker: 'partner',
        sv: 'Åh, du hittade en! Snällt av dig.',
        de: 'Oh, du hast einen gefunden! Nett von dir.',
        decoding: [
          { sv: 'åh', de: 'oh' },
          { sv: 'du', de: 'du' },
          { sv: 'hittade', de: 'fandest' },
          { sv: 'en', de: 'einen' },
          { sv: 'snällt', de: 'nett' },
          { sv: 'av', de: 'von' },
          { sv: 'dig', de: 'dir' },
        ],
      },
    ],
  },
];
