// Gespräche zu den vier Themen aus Ausbau 1.
//
// Jede Szene bringt ALLE Wendungen ihres Themas als „du"-Zeile unter — ein
// Gespräch ist der härtere Abruf (richtige Stelle, mit Antwort davor und
// danach), und ohne Szene bliebe ein Thema halb.

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-airport',
    categoryId: 'cat-airport',
    title: 'Am Flughafen: einchecken, Gate finden, Gepäck holen',
    blurb: 'Vom Schalter bis zum Kofferband — und der Flug hat auch noch Verspätung.',
    scene: 'station',
    partnerName: 'Bodenpersonal',
    turns: [
      { id: 'ap1', speaker: 'partner', sv: 'Hej {name}! Vart ska du idag?', de: 'Hallo {name}! Wohin geht es heute?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'vart', de: 'wohin' }, { sv: 'ska', de: 'sollst' }, { sv: 'du', de: 'du' }, { sv: 'idag', de: 'heute' }] },
      { id: 'ap2', speaker: 'you', sv: 'var är incheckningen?', de: 'wo ist der Check-in?', chunkId: 'c-ap-incheck' },
      { id: 'ap3', speaker: 'partner', sv: 'Där borta, disk fyra. Har du väska?', de: 'Da drüben, Schalter vier. Hast du einen Koffer?', decoding: [{ sv: 'där', de: 'dort' }, { sv: 'borta', de: 'drüben' }, { sv: 'disk', de: 'Schalter' }, { sv: 'fyra', de: 'vier' }, { sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'väska', de: 'Tasche' }] },
      { id: 'ap4', speaker: 'you', sv: 'jag har bara handbagage', de: 'ich habe nur Handgepäck', chunkId: 'c-ap-handbagage' },
      { id: 'ap5', speaker: 'partner', sv: 'Perfekt, då går det snabbt. Legitimation, tack.', de: 'Perfekt, dann geht es schnell. Ausweis, bitte.', decoding: [{ sv: 'perfekt', de: 'perfekt' }, { sv: 'då', de: 'dann' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }, { sv: 'snabbt', de: 'schnell' }, { sv: 'legitimation', de: 'Ausweis' }, { sv: 'tack', de: 'bitte' }] },
      { id: 'ap6', speaker: 'you', sv: 'har du ditt pass?', de: 'hast du deinen Pass?', chunkId: 'c-ap-pass' },
      { id: 'ap7', speaker: 'partner', sv: 'Haha, jag frågade dig! Men ja, här är ditt kort.', de: 'Haha, ich habe dich gefragt! Aber ja, hier ist deine Karte.', decoding: [{ sv: 'haha', de: 'haha' }, { sv: 'jag', de: 'ich' }, { sv: 'frågade', de: 'fragte' }, { sv: 'dig', de: 'dich' }, { sv: 'men', de: 'aber' }, { sv: 'ja', de: 'ja' }, { sv: 'här', de: 'hier' }, { sv: 'är', de: 'ist' }, { sv: 'ditt', de: 'deine' }, { sv: 'kort', de: 'Karte' }] },
      { id: 'ap8', speaker: 'you', sv: 'vilken gate är det?', de: 'welches Gate ist es?', chunkId: 'c-ap-gate' },
      { id: 'ap9', speaker: 'partner', sv: 'Gate tolv. Men kolla skärmen igen om en stund.', de: 'Gate zwölf. Aber schau gleich noch mal auf den Bildschirm.', decoding: [{ sv: 'gate', de: 'Gate' }, { sv: 'tolv', de: 'zwölf' }, { sv: 'men', de: 'aber' }, { sv: 'kolla', de: 'schau' }, { sv: 'skärmen', de: 'den Bildschirm' }, { sv: 'igen', de: 'wieder' }, { sv: 'om', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'stund', de: 'Weile' }] },
      { id: 'ap10', speaker: 'partner', sv: 'Just det — det står nytt på skärmen nu.', de: 'Genau — auf dem Bildschirm steht jetzt etwas Neues.', decoding: [{ sv: 'just', de: 'gerade' }, { sv: 'det', de: 'das' }, { sv: 'det', de: 'es' }, { sv: 'står', de: 'steht' }, { sv: 'nytt', de: 'Neues' }, { sv: 'på', de: 'auf' }, { sv: 'skärmen', de: 'dem Bildschirm' }, { sv: 'nu', de: 'jetzt' }] },
      { id: 'ap11', speaker: 'you', sv: 'flyget är försenat', de: 'der Flug hat Verspätung', chunkId: 'c-ap-forsenat' },
      { id: 'ap12', speaker: 'partner', sv: 'Tyvärr, en timme. Ta en kaffe så länge.', de: 'Leider, eine Stunde. Trink so lange einen Kaffee.', decoding: [{ sv: 'tyvärr', de: 'leider' }, { sv: 'en', de: 'eine' }, { sv: 'timme', de: 'Stunde' }, { sv: 'ta', de: 'nimm' }, { sv: 'en', de: 'einen' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'så', de: 'so' }, { sv: 'länge', de: 'lange' }] },
      { id: 'ap13', speaker: 'partner', sv: 'Nästa gång: kom tidigare, annars händer det här.', de: 'Nächstes Mal: komm früher, sonst passiert das hier.', decoding: [{ sv: 'nästa', de: 'nächstes' }, { sv: 'gång', de: 'Mal' }, { sv: 'kom', de: 'komm' }, { sv: 'tidigare', de: 'früher' }, { sv: 'annars', de: 'sonst' }, { sv: 'händer', de: 'passiert' }, { sv: 'det', de: 'das' }, { sv: 'här', de: 'hier' }] },
      { id: 'ap14', speaker: 'you', sv: 'jag har missat mitt flyg', de: 'ich habe meinen Flug verpasst', chunkId: 'c-ap-missat' },
      { id: 'ap15', speaker: 'partner', sv: 'Inte idag! Du är i tid. Framme om två timmar.', de: 'Heute nicht! Du bist pünktlich. In zwei Stunden bist du da.', decoding: [{ sv: 'inte', de: 'nicht' }, { sv: 'idag', de: 'heute' }, { sv: 'du', de: 'du' }, { sv: 'är', de: 'bist' }, { sv: 'i', de: 'in' }, { sv: 'tid', de: 'Zeit' }, { sv: 'framme', de: 'angekommen' }, { sv: 'om', de: 'in' }, { sv: 'två', de: 'zwei' }, { sv: 'timmar', de: 'Stunden' }] },
      { id: 'ap16', speaker: 'you', sv: 'var hämtar man bagaget?', de: 'wo holt man das Gepäck?', chunkId: 'c-ap-bagage' },
      { id: 'ap17', speaker: 'partner', sv: 'Band tre, när du landat. Trevlig resa!', de: 'Band drei, wenn du gelandet bist. Gute Reise!', decoding: [{ sv: 'band', de: 'Band' }, { sv: 'tre', de: 'drei' }, { sv: 'när', de: 'wenn' }, { sv: 'du', de: 'du' }, { sv: 'landat', de: 'gelandet' }, { sv: 'trevlig', de: 'schöne' }, { sv: 'resa', de: 'Reise' }] },
    ],
  },
  {
    id: 'dlg-tech',
    categoryId: 'cat-tech',
    title: 'Technik: WLAN, Passwort, leerer Akku',
    blurb: 'Nichts geht — und du musst es auf Schwedisch erklären.',
    scene: 'office',
    partnerName: 'Kollegin',
    turns: [
      { id: 'tk1', speaker: 'partner', sv: 'Hej {name}, har du problem med något?', de: 'Hallo {name}, hast du mit etwas Probleme?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'problem', de: 'Probleme' }, { sv: 'med', de: 'mit' }, { sv: 'något', de: 'etwas' }] },
      { id: 'tk2', speaker: 'you', sv: 'wifi funkar inte', de: 'das WLAN geht nicht', chunkId: 'c-tk-wifi' },
      { id: 'tk3', speaker: 'partner', sv: 'Konstigt. Är du på rätt nät?', de: 'Seltsam. Bist du im richtigen Netz?', decoding: [{ sv: 'konstigt', de: 'seltsam' }, { sv: 'är', de: 'bist' }, { sv: 'du', de: 'du' }, { sv: 'på', de: 'auf' }, { sv: 'rätt', de: 'richtig' }, { sv: 'nät', de: 'Netz' }] },
      { id: 'tk4', speaker: 'you', sv: 'vad är lösenordet?', de: 'wie ist das Passwort?', chunkId: 'c-tk-losenord' },
      { id: 'tk5', speaker: 'partner', sv: 'Det står på lappen vid dörren.', de: 'Es steht auf dem Zettel an der Tür.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'står', de: 'steht' }, { sv: 'på', de: 'auf' }, { sv: 'lappen', de: 'dem Zettel' }, { sv: 'vid', de: 'bei' }, { sv: 'dörren', de: 'der Tür' }] },
      { id: 'tk6', speaker: 'partner', sv: 'Fungerar det nu? Din skärm ser konstig ut.', de: 'Geht es jetzt? Dein Bildschirm sieht komisch aus.', decoding: [{ sv: 'fungerar', de: 'funktioniert' }, { sv: 'det', de: 'es' }, { sv: 'nu', de: 'jetzt' }, { sv: 'din', de: 'dein' }, { sv: 'skärm', de: 'Bildschirm' }, { sv: 'ser', de: 'sieht' }, { sv: 'konstig', de: 'seltsam' }, { sv: 'ut', de: 'aus' }] },
      { id: 'tk7', speaker: 'you', sv: 'den har hängt sig', de: 'er ist abgestürzt', chunkId: 'c-tk-hangt' },
      { id: 'tk8', speaker: 'partner', sv: 'Klassiskt. Vet du vad man gör då?', de: 'Klassisch. Weißt du, was man dann macht?', decoding: [{ sv: 'klassiskt', de: 'klassisch' }, { sv: 'vet', de: 'weißt' }, { sv: 'du', de: 'du' }, { sv: 'vad', de: 'was' }, { sv: 'man', de: 'man' }, { sv: 'gör', de: 'macht' }, { sv: 'då', de: 'dann' }] },
      { id: 'tk9', speaker: 'you', sv: 'starta om den', de: 'starte ihn neu', chunkId: 'c-tk-starta' },
      { id: 'tk10', speaker: 'partner', sv: 'Precis. Och telefonen? Den blinkar rött.', de: 'Genau. Und das Telefon? Es blinkt rot.', decoding: [{ sv: 'precis', de: 'genau' }, { sv: 'och', de: 'und' }, { sv: 'telefonen', de: 'das Telefon' }, { sv: 'den', de: 'es' }, { sv: 'blinkar', de: 'blinkt' }, { sv: 'rött', de: 'rot' }] },
      { id: 'tk11', speaker: 'you', sv: 'mitt batteri är slut', de: 'mein Akku ist leer', chunkId: 'c-tk-batteri' },
      { id: 'tk12', speaker: 'partner', sv: 'Det finns uttag under bordet.', de: 'Unter dem Tisch gibt es Steckdosen.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'finns', de: 'gibt es' }, { sv: 'uttag', de: 'Steckdosen' }, { sv: 'under', de: 'unter' }, { sv: 'bordet', de: 'dem Tisch' }] },
      { id: 'tk13', speaker: 'you', sv: 'kan jag ladda här?', de: 'kann ich hier laden?', chunkId: 'c-tk-ladda' },
      { id: 'tk14', speaker: 'partner', sv: 'Visst. Skicka inbjudan till mötet sedan, tack.', de: 'Klar. Schick danach die Einladung zum Treffen, bitte.', decoding: [{ sv: 'visst', de: 'klar' }, { sv: 'skicka', de: 'schicke' }, { sv: 'inbjudan', de: 'die Einladung' }, { sv: 'till', de: 'zu' }, { sv: 'mötet', de: 'dem Treffen' }, { sv: 'sedan', de: 'danach' }, { sv: 'tack', de: 'bitte' }] },
      { id: 'tk15', speaker: 'you', sv: 'jag skickar en länk', de: 'ich schicke einen Link', chunkId: 'c-tk-lank' },
      { id: 'tk16', speaker: 'partner', sv: 'Tack! Då fungerar allt igen om fem minuter.', de: 'Danke! Dann geht in fünf Minuten alles wieder.', decoding: [{ sv: 'tack', de: 'danke' }, { sv: 'då', de: 'dann' }, { sv: 'fungerar', de: 'funktioniert' }, { sv: 'allt', de: 'alles' }, { sv: 'igen', de: 'wieder' }, { sv: 'om', de: 'in' }, { sv: 'fem', de: 'fünf' }, { sv: 'minuter', de: 'Minuten' }] },
    ],
  },
  {
    id: 'dlg-cooking',
    categoryId: 'cat-cooking',
    title: 'Zusammen kochen: Rezept, Pfanne, Ofen',
    blurb: 'Ihr kocht zu zweit — und einer von euch liest das Rezept.',
    scene: 'home',
    partnerName: 'Freund',
    turns: [
      { id: 'ko1', speaker: 'partner', sv: 'Hej {name}! Jag är hungrig.', de: 'Hallo {name}! Ich habe Hunger.', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'hungrig', de: 'hungrig' }] },
      { id: 'ko2', speaker: 'you', sv: 'vad ska vi laga?', de: 'was sollen wir kochen?', chunkId: 'c-ko-laga' },
      { id: 'ko3', speaker: 'partner', sv: 'Något enkelt. Har du en idé?', de: 'Etwas Einfaches. Hast du eine Idee?', decoding: [{ sv: 'något', de: 'etwas' }, { sv: 'enkelt', de: 'einfach' }, { sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'en', de: 'eine' }, { sv: 'idé', de: 'Idee' }] },
      { id: 'ko4', speaker: 'you', sv: 'jag följer ett recept', de: 'ich folge einem Rezept', chunkId: 'c-ko-recept' },
      { id: 'ko5', speaker: 'partner', sv: 'Bra. Vad behöver vi först?', de: 'Gut. Was brauchen wir zuerst?', decoding: [{ sv: 'bra', de: 'gut' }, { sv: 'vad', de: 'was' }, { sv: 'behöver', de: 'brauchen' }, { sv: 'vi', de: 'wir' }, { sv: 'först', de: 'erst' }] },
      { id: 'ko6', speaker: 'you', sv: 'har du en stekpanna?', de: 'hast du eine Pfanne?', chunkId: 'c-ko-stekpanna' },
      { id: 'ko7', speaker: 'partner', sv: 'I skåpet till vänster. Och ugnen?', de: 'Im Schrank links. Und der Ofen?', decoding: [{ sv: 'i', de: 'im' }, { sv: 'skåpet', de: 'dem Schrank' }, { sv: 'till', de: 'zu' }, { sv: 'vänster', de: 'links' }, { sv: 'och', de: 'und' }, { sv: 'ugnen', de: 'der Ofen' }] },
      { id: 'ko8', speaker: 'you', sv: 'sätt på ugnen', de: 'schalte den Ofen an', chunkId: 'c-ko-ugnen' },
      { id: 'ko9', speaker: 'partner', sv: 'Klart. Hur länge ska det vara på spisen?', de: 'Erledigt. Wie lange soll es auf dem Herd sein?', decoding: [{ sv: 'klart', de: 'klar' }, { sv: 'hur', de: 'wie' }, { sv: 'länge', de: 'lange' }, { sv: 'ska', de: 'soll' }, { sv: 'det', de: 'es' }, { sv: 'vara', de: 'sein' }, { sv: 'på', de: 'auf' }, { sv: 'spisen', de: 'dem Herd' }] },
      { id: 'ko10', speaker: 'you', sv: 'det ska koka i tio minuter', de: 'es soll zehn Minuten kochen', chunkId: 'c-ko-koka' },
      { id: 'ko11', speaker: 'partner', sv: 'Okej. Vill du smaka?', de: 'Okay. Willst du probieren?', decoding: [{ sv: 'okej', de: 'okay' }, { sv: 'vill', de: 'willst' }, { sv: 'du', de: 'du' }, { sv: 'smaka', de: 'kosten' }] },
      { id: 'ko12', speaker: 'you', sv: 'smakar det bra?', de: 'schmeckt es gut?', chunkId: 'c-ko-smakar' },
      { id: 'ko13', speaker: 'partner', sv: 'Nästan. Det saknas något.', de: 'Fast. Es fehlt etwas.', decoding: [{ sv: 'nästan', de: 'fast' }, { sv: 'det', de: 'es' }, { sv: 'saknas', de: 'fehlt' }, { sv: 'något', de: 'etwas' }] },
      { id: 'ko14', speaker: 'you', sv: 'salta lite mer', de: 'salz etwas mehr', chunkId: 'c-ko-salta' },
      { id: 'ko15', speaker: 'partner', sv: 'Där ja! Nu är det jättebra.', de: 'Da ja! Jetzt ist es super.', decoding: [{ sv: 'där', de: 'dort' }, { sv: 'ja', de: 'ja' }, { sv: 'nu', de: 'jetzt' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'jättebra', de: 'super' }] },
    ],
  },
  {
    id: 'dlg-hair',
    categoryId: 'cat-hair',
    title: 'Beim Friseur: Termin und ein paar Zentimeter',
    blurb: 'Reinkommen, Termin bekommen, und dann genau sagen, wie kurz.',
    scene: 'shop',
    partnerName: 'Friseurin',
    turns: [
      { id: 'fr1', speaker: 'partner', sv: 'Hej! Vad kan jag hjälpa till med?', de: 'Hallo! Womit kann ich helfen?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'vad', de: 'was' }, { sv: 'kan', de: 'kann' }, { sv: 'jag', de: 'ich' }, { sv: 'hjälpa', de: 'helfen' }, { sv: 'till', de: 'zu' }, { sv: 'med', de: 'mit' }] },
      { id: 'fr2', speaker: 'you', sv: 'har ni en tid idag?', de: 'habt ihr heute einen Termin?', chunkId: 'c-fr-tid' },
      { id: 'fr3', speaker: 'partner', sv: 'Om tjugo minuter blir det ledigt.', de: 'In zwanzig Minuten wird etwas frei.', decoding: [{ sv: 'om', de: 'in' }, { sv: 'tjugo', de: 'zwanzig' }, { sv: 'minuter', de: 'Minuten' }, { sv: 'blir', de: 'wird' }, { sv: 'det', de: 'es' }, { sv: 'ledigt', de: 'frei' }] },
      { id: 'fr4', speaker: 'you', sv: 'jag vill klippa mig', de: 'ich möchte mir die Haare schneiden lassen', chunkId: 'c-fr-klippa' },
      { id: 'fr5', speaker: 'partner', sv: 'Så klart. Hur mycket ska bort?', de: 'Natürlich. Wie viel soll weg?', decoding: [{ sv: 'så', de: 'so' }, { sv: 'klart', de: 'klar' }, { sv: 'hur', de: 'wie' }, { sv: 'mycket', de: 'viel' }, { sv: 'ska', de: 'soll' }, { sv: 'bort', de: 'weg' }] },
      { id: 'fr6', speaker: 'you', sv: 'bara lite kortare', de: 'nur ein bisschen kürzer', chunkId: 'c-fr-kortare' },
      { id: 'fr7', speaker: 'partner', sv: 'Två centimeter? Eller mer?', de: 'Zwei Zentimeter? Oder mehr?', decoding: [{ sv: 'två', de: 'zwei' }, { sv: 'centimeter', de: 'Zentimeter' }, { sv: 'eller', de: 'oder' }, { sv: 'mer', de: 'mehr' }] },
      { id: 'fr8', speaker: 'you', sv: 'inte för kort', de: 'nicht zu kurz', chunkId: 'c-fr-forkort' },
      { id: 'fr9', speaker: 'partner', sv: 'Uppfattat. Och framtill?', de: 'Verstanden. Und vorne?', decoding: [{ sv: 'uppfattat', de: 'aufgefasst' }, { sv: 'och', de: 'und' }, { sv: 'framtill', de: 'vorne' }] },
      { id: 'fr10', speaker: 'you', sv: 'jag vill ha lugg', de: 'ich möchte einen Pony', chunkId: 'c-fr-lugg' },
      { id: 'fr11', speaker: 'partner', sv: 'Fint. Vi börjar med att tvätta.', de: 'Schön. Wir fangen mit Waschen an.', decoding: [{ sv: 'fint', de: 'schön' }, { sv: 'vi', de: 'wir' }, { sv: 'börjar', de: 'beginnen' }, { sv: 'med', de: 'mit' }, { sv: 'att', de: 'zu' }, { sv: 'tvätta', de: 'waschen' }] },
      { id: 'fr12', speaker: 'partner', sv: 'Titta i spegeln — är det bra så?', de: 'Schau in den Spiegel — ist es so gut?', decoding: [{ sv: 'titta', de: 'schau' }, { sv: 'i', de: 'in' }, { sv: 'spegeln', de: 'den Spiegel' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }, { sv: 'så', de: 'so' }] },
      { id: 'fr13', speaker: 'you', sv: 'så där, tack', de: 'so ist gut, danke', chunkId: 'c-fr-sadar' },
      { id: 'fr14', speaker: 'partner', sv: 'Varsågod! Vi ses om sex veckor.', de: 'Bitte sehr! Wir sehen uns in sechs Wochen.', decoding: [{ sv: 'varsågod', de: 'bitte sehr' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'om', de: 'in' }, { sv: 'sex', de: 'sechs' }, { sv: 'veckor', de: 'Wochen' }] },
    ],
  },
];
