// SEED-DIALOGE (Dialog-Modus) — PROVISORISCH, wie der übrige Seed.
//
// ⚠️ EHRLICH: von uns/der KI verfasst, NICHT muttersprachlich geprüft
// (docs/content-review-schwedisch.md). Jede „du"-Zeile referenziert einen
// vorhandenen Chunk (c-*), damit das Gespräch echtes Können übt und in die
// Memory-Engine zurückfließt — kein separater Schein-Fortschritt.
//
// Partner-Zeilen sind verständlicher Input (i+1): ein paar neue Wörter sind ok,
// solange die Wort-für-Wort-Dekodierung (Birkenbihl) sie sofort verständlich macht.

import type { Dialog } from '../../domain/dialog';

export const seedDialogs: Dialog[] = [
  // ── Im Restaurant (cat-restaurant) ───────────────────────────────────────────
  {
    id: 'dlg-restaurant',
    categoryId: 'cat-restaurant',
    title: 'Im Restaurant: Tisch, bestellen, zahlen',
    blurb: 'Ein ganzes Essen auf Schwedisch — vom Tisch bis zur Rechnung.',
    scene: 'cafe',
    partnerName: 'Kellner',
    turns: [
      {
        id: 'r1',
        speaker: 'partner',
        // „{name}" wird durch den Vornamen des Lerners ersetzt (oder sauber entfernt).
        sv: 'Hej {name}, välkommen!',
        de: 'Hallo {name}, willkommen!',
        listenFirst: true,
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'välkommen', de: 'willkommen' },
        ],
      },
      {
        id: 'r2',
        speaker: 'partner',
        sv: 'Ett bord för två?',
        de: 'Ein Tisch für zwei?',
        decoding: [
          { sv: 'ett', de: 'ein' },
          { sv: 'bord', de: 'Tisch' },
          { sv: 'för', de: 'für' },
          { sv: 'två', de: 'zwei' },
        ],
      },
      {
        id: 'r3',
        speaker: 'you',
        sv: 'ja, tack',
        de: 'ja, bitte',
        chunkId: 'c-jatack',
        suggestions: ['Ja, tack.', 'Nej, tack.'],
      },
      {
        id: 'r4',
        speaker: 'partner',
        sv: 'Varsågod. Här är menyn.',
        de: 'Bitte. Hier ist die Karte.',
        decoding: [
          { sv: 'varsågod', de: 'bitte' },
          { sv: 'här', de: 'hier' },
          { sv: 'är', de: 'ist' },
          { sv: 'menyn', de: 'die Speisekarte' },
        ],
      },
      {
        id: 'r5',
        speaker: 'you',
        sv: 'vad rekommenderar du?',
        de: 'was empfiehlst du?',
        chunkId: 'c-rekommenderar',
        suggestions: ['Vad rekommenderar du?', 'Vad kostar det?'],
      },
      {
        id: 'r6',
        speaker: 'partner',
        sv: 'Jag rekommenderar köttbullar.',
        de: 'Ich empfehle Fleischbällchen.',
        decoding: [
          { sv: 'jag', de: 'ich' },
          { sv: 'rekommenderar', de: 'empfehle' },
          { sv: 'köttbullar', de: 'Fleischbällchen' },
        ],
      },
      {
        id: 'r7',
        speaker: 'you',
        sv: 'jag tar den här',
        de: 'ich nehme das hier',
        chunkId: 'c-tardenhar',
        suggestions: ['Jag tar den här.', 'Jag tar den.'],
      },
      {
        id: 'r8',
        speaker: 'partner',
        sv: 'Utmärkt! Smaklig måltid.',
        de: 'Ausgezeichnet! Guten Appetit.',
        decoding: [
          { sv: 'utmärkt', de: 'ausgezeichnet' },
          { sv: 'smaklig', de: 'schmackhaft' },
          { sv: 'måltid', de: 'Mahlzeit' },
        ],
      },
      {
        id: 'r9',
        speaker: 'you',
        sv: 'kan jag få notan?',
        de: 'kann ich die Rechnung haben?',
        chunkId: 'c-notan',
        suggestions: ['Kan jag få notan?', 'Kan jag få menyn?'],
      },
      {
        id: 'r10',
        speaker: 'partner',
        sv: 'Javisst. Ha en trevlig kväll {name}!',
        de: 'Aber sicher. Einen schönen Abend, {name}!',
        decoding: [
          { sv: 'javisst', de: 'aber sicher' },
          { sv: 'ha', de: 'hab' },
          { sv: 'en', de: 'einen' },
          { sv: 'trevlig', de: 'schönen' },
          { sv: 'kväll', de: 'Abend' },
        ],
      },
    ],
  },

  // ── Im Hotel (cat-hotel) ─────────────────────────────────────────────────────
  {
    id: 'dlg-hotel',
    categoryId: 'cat-hotel',
    title: 'Im Hotel: einchecken',
    blurb: 'Ankommen, Zimmer, Preis, Schlüssel — an der Rezeption.',
    scene: 'hotel',
    partnerName: 'Rezeption',
    turns: [
      {
        id: 'h1',
        speaker: 'partner',
        sv: 'God kväll {name}! Välkommen.',
        de: 'Guten Abend {name}! Willkommen.',
        listenFirst: true,
        decoding: [
          { sv: 'god', de: 'guten' },
          { sv: 'kväll', de: 'Abend' },
          { sv: 'välkommen', de: 'willkommen' },
        ],
      },
      {
        id: 'h2',
        speaker: 'you',
        sv: 'jag har bokat ett rum',
        de: 'ich habe ein Zimmer gebucht',
        chunkId: 'c-bokatrum',
        suggestions: ['Jag har bokat ett rum.', 'Har ni ett ledigt rum?'],
      },
      {
        id: 'h3',
        speaker: 'partner',
        sv: 'Perfekt. För hur många nätter?',
        de: 'Perfekt. Für wie viele Nächte?',
        decoding: [
          { sv: 'perfekt', de: 'perfekt' },
          { sv: 'för', de: 'für' },
          { sv: 'hur', de: 'wie' },
          { sv: 'många', de: 'viele' },
          { sv: 'nätter', de: 'Nächte' },
        ],
      },
      {
        id: 'h4',
        speaker: 'you',
        sv: 'vad kostar en natt?',
        de: 'was kostet eine Nacht?',
        chunkId: 'c-vadnatt',
        suggestions: ['Vad kostar en natt?', 'Vad kostar det?'],
      },
      {
        id: 'h5',
        speaker: 'partner',
        sv: 'Tusen kronor per natt.',
        de: 'Tausend Kronen pro Nacht.',
        decoding: [
          { sv: 'tusen', de: 'tausend' },
          { sv: 'kronor', de: 'Kronen' },
          { sv: 'per', de: 'pro' },
          { sv: 'natt', de: 'Nacht' },
        ],
      },
      {
        id: 'h6',
        speaker: 'you',
        sv: 'kan jag få nyckeln?',
        de: 'kann ich den Schlüssel haben?',
        chunkId: 'c-nyckeln',
        suggestions: ['Kan jag få nyckeln?', 'Kan jag få notan?'],
      },
      {
        id: 'h7',
        speaker: 'partner',
        sv: 'Varsågod. Frukost är klockan åtta.',
        de: 'Bitte. Frühstück ist um acht Uhr.',
        decoding: [
          { sv: 'varsågod', de: 'bitte' },
          { sv: 'frukost', de: 'Frühstück' },
          { sv: 'är', de: 'ist' },
          { sv: 'klockan', de: 'die Uhr' },
          { sv: 'åtta', de: 'acht' },
        ],
      },
      {
        id: 'h8',
        speaker: 'you',
        sv: 'tack så mycket',
        de: 'danke vielmals',
        chunkId: 'c-tack',
        suggestions: ['Tack så mycket.', 'Ha det bra.'],
      },
      {
        id: 'h9',
        speaker: 'partner',
        sv: 'Tack själv {name}. Ha det bra!',
        de: 'Danke gleichfalls {name}. Machen Sie es gut!',
        decoding: [
          { sv: 'tack', de: 'danke' },
          { sv: 'själv', de: 'selbst' },
          { sv: 'ha', de: 'hab' },
          { sv: 'det', de: 'es' },
          { sv: 'bra', de: 'gut' },
        ],
      },
    ],
  },

  // ── Nach dem Weg fragen (cat-around) ─────────────────────────────────────────
  {
    id: 'dlg-weg',
    categoryId: 'cat-around',
    title: 'Nach dem Weg fragen',
    blurb: 'Jemanden ansprechen, den Weg erfragen, danke sagen.',
    scene: 'station',
    partnerName: 'Passant',
    turns: [
      {
        id: 'w1',
        speaker: 'you',
        sv: 'kan du hjälpa mig?',
        de: 'kannst du mir helfen?',
        chunkId: 'c-hjalpa',
        suggestions: ['Kan du hjälpa mig?', 'Kan du prata långsammare?'],
      },
      {
        id: 'w2',
        speaker: 'partner',
        sv: 'Javisst {name}! Vad söker du?',
        de: 'Aber sicher {name}! Was suchst du?',
        decoding: [
          { sv: 'javisst', de: 'aber sicher' },
          { sv: 'vad', de: 'was' },
          { sv: 'söker', de: 'suchst' },
          { sv: 'du', de: 'du' },
        ],
      },
      {
        id: 'w3',
        speaker: 'you',
        sv: 'var ligger stationen?',
        de: 'wo liegt der Bahnhof?',
        chunkId: 'c-stationen',
        suggestions: ['Var ligger stationen?', 'Var är toaletten?'],
      },
      {
        id: 'w4',
        speaker: 'partner',
        sv: 'Gå rakt fram, sen till höger.',
        de: 'Geh geradeaus, dann nach rechts.',
        decoding: [
          { sv: 'gå', de: 'geh' },
          { sv: 'rakt', de: 'gerade' },
          { sv: 'fram', de: 'voraus' },
          { sv: 'sen', de: 'dann' },
          { sv: 'till', de: 'nach' },
          { sv: 'höger', de: 'rechts' },
        ],
      },
      {
        id: 'w5',
        speaker: 'you',
        sv: 'hur kommer jag till centrum?',
        de: 'wie komme ich ins Zentrum?',
        chunkId: 'c-centrum',
        suggestions: ['Hur kommer jag till centrum?', 'Hur mår du?'],
      },
      {
        id: 'w6',
        speaker: 'partner',
        sv: 'Ta bussen. Hållplatsen är där.',
        de: 'Nimm den Bus. Die Haltestelle ist dort.',
        decoding: [
          { sv: 'ta', de: 'nimm' },
          { sv: 'bussen', de: 'der Bus' },
          { sv: 'hållplatsen', de: 'die Haltestelle' },
          { sv: 'är', de: 'ist' },
          { sv: 'där', de: 'dort' },
        ],
      },
      {
        id: 'w7',
        speaker: 'you',
        sv: 'tack så mycket',
        de: 'danke vielmals',
        chunkId: 'c-tack',
        suggestions: ['Tack så mycket!', 'Förlåt.'],
      },
      {
        id: 'w8',
        speaker: 'partner',
        sv: 'Ingen orsak. Lycka till!',
        de: 'Keine Ursache. Viel Glück!',
        decoding: [
          { sv: 'ingen', de: 'keine' },
          { sv: 'orsak', de: 'Ursache' },
          { sv: 'lycka', de: 'Glück' },
          { sv: 'till', de: 'zu' },
        ],
      },
    ],
  },

  // ── Im Café (cat-cafe) ───────────────────────────────────────────────────────
  {
    id: 'dlg-cafe',
    categoryId: 'cat-cafe',
    title: 'Im Café: bestellen und zahlen',
    blurb: 'Einen Kaffee bestellen, nachbestellen, nach dem Preis fragen.',
    scene: 'cafe',
    partnerName: 'Barista',
    turns: [
      {
        id: 'k1',
        speaker: 'partner',
        sv: 'Hej {name}! Vad får det lov att vara?',
        de: 'Hallo {name}! Was darf es sein?',
        listenFirst: true,
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'vad', de: 'was' },
          { sv: 'får', de: 'darf' },
          { sv: 'det', de: 'es' },
          { sv: 'lov', de: 'Erlaubnis' },
          { sv: 'att', de: 'zu' },
          { sv: 'vara', de: 'sein' },
        ],
      },
      {
        id: 'k2',
        speaker: 'you',
        sv: 'jag vill ha',
        de: 'ich möchte',
        chunkId: 'c-vill-ha',
        suggestions: ['Jag vill ha.', 'Jag tar den.'],
      },
      {
        id: 'k3',
        speaker: 'partner',
        sv: 'En kaffe? Kommer strax.',
        de: 'Einen Kaffee? Kommt sofort.',
        decoding: [
          { sv: 'en', de: 'einen' },
          { sv: 'kaffe', de: 'Kaffee' },
          { sv: 'kommer', de: 'kommt' },
          { sv: 'strax', de: 'gleich' },
        ],
      },
      {
        id: 'k4',
        speaker: 'you',
        sv: 'vad kostar det?',
        de: 'was kostet das?',
        chunkId: 'c-kostar',
        suggestions: ['Vad kostar det?', 'Hur mycket blir det?'],
      },
      {
        id: 'k5',
        speaker: 'partner',
        sv: 'Trettiofem kronor, tack.',
        de: 'Fünfunddreißig Kronen, bitte.',
        decoding: [
          { sv: 'trettiofem', de: 'fünfunddreißig' },
          { sv: 'kronor', de: 'Kronen' },
          { sv: 'tack', de: 'bitte' },
        ],
      },
      {
        id: 'k6',
        speaker: 'you',
        sv: 'en till, tack',
        de: 'noch eine(n), bitte',
        chunkId: 'c-entill',
        suggestions: ['En till, tack.', 'Tack så mycket.'],
      },
      {
        id: 'k7',
        speaker: 'partner',
        sv: 'Självklart! Varsågod.',
        de: 'Selbstverständlich! Bitte sehr.',
        decoding: [
          { sv: 'självklart', de: 'selbstverständlich' },
          { sv: 'varsågod', de: 'bitte' },
        ],
      },
      {
        id: 'k8',
        speaker: 'you',
        sv: 'tack så mycket',
        de: 'danke vielmals',
        chunkId: 'c-tack',
        suggestions: ['Tack så mycket.', 'Ha det bra.'],
      },
    ],
  },

  // ── Im Geschäft (cat-shop) ───────────────────────────────────────────────────
  {
    id: 'dlg-shop',
    categoryId: 'cat-shop',
    title: 'Im Geschäft: anprobieren und kaufen',
    blurb: 'Nur schauen, Größe finden, anprobieren — und mitnehmen.',
    scene: 'shop',
    partnerName: 'Verkäuferin',
    turns: [
      {
        id: 'g1',
        speaker: 'partner',
        sv: 'Hej {name}! Behöver du hjälp?',
        de: 'Hallo {name}! Brauchst du Hilfe?',
        listenFirst: true,
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'behöver', de: 'brauchst' },
          { sv: 'du', de: 'du' },
          { sv: 'hjälp', de: 'Hilfe' },
        ],
      },
      {
        id: 'g2',
        speaker: 'you',
        sv: 'jag tittar bara',
        de: 'ich schaue nur',
        chunkId: 'c-tittarbara',
        suggestions: ['Jag tittar bara.', 'Kan du hjälpa mig?'],
      },
      {
        id: 'g3',
        speaker: 'partner',
        sv: 'Säg till om du undrar något.',
        de: 'Sag Bescheid, wenn du etwas wissen möchtest.',
        decoding: [
          { sv: 'säg', de: 'sag' },
          { sv: 'till', de: 'Bescheid' },
          { sv: 'om', de: 'wenn' },
          { sv: 'du', de: 'du' },
          { sv: 'undrar', de: 'dich fragst' },
          { sv: 'något', de: 'etwas' },
        ],
      },
      {
        id: 'g4',
        speaker: 'you',
        sv: 'kan jag prova?',
        de: 'kann ich anprobieren?',
        chunkId: 'c-prova',
        suggestions: ['Kan jag prova?', 'Vilken storlek?'],
      },
      {
        id: 'g5',
        speaker: 'partner',
        sv: 'Visst! Provrummet är där borta.',
        de: 'Klar! Die Umkleide ist da drüben.',
        decoding: [
          { sv: 'visst', de: 'klar' },
          { sv: 'provrummet', de: 'die Umkleidekabine' },
          { sv: 'är', de: 'ist' },
          { sv: 'där', de: 'da' },
          { sv: 'borta', de: 'drüben' },
        ],
      },
      {
        id: 'g6',
        speaker: 'you',
        sv: 'jag tar den',
        de: 'ich nehme es',
        chunkId: 'c-tarden',
        suggestions: ['Jag tar den.', 'Det är för dyrt.'],
      },
      {
        id: 'g7',
        speaker: 'partner',
        sv: 'Utmärkt val! Betalar du med kort?',
        de: 'Ausgezeichnete Wahl! Zahlst du mit Karte?',
        decoding: [
          { sv: 'utmärkt', de: 'ausgezeichnete' },
          { sv: 'val', de: 'Wahl' },
          { sv: 'betalar', de: 'zahlst' },
          { sv: 'du', de: 'du' },
          { sv: 'med', de: 'mit' },
          { sv: 'kort', de: 'Karte' },
        ],
      },
      {
        id: 'g8',
        speaker: 'you',
        sv: 'kan jag betala med kort?',
        de: 'kann ich mit Karte zahlen?',
        chunkId: 'c-medkort',
        suggestions: ['Kan jag betala med kort?', 'Jag betalar kontant.'],
      },
      {
        id: 'g9',
        speaker: 'partner',
        sv: 'Absolut. Här är kvittot.',
        de: 'Absolut. Hier ist der Beleg.',
        decoding: [
          { sv: 'absolut', de: 'absolut' },
          { sv: 'här', de: 'hier' },
          { sv: 'är', de: 'ist' },
          { sv: 'kvittot', de: 'der Beleg' },
        ],
      },
    ],
  },

  // ── Im Supermarkt (cat-groceries) ────────────────────────────────────────────
  {
    id: 'dlg-groceries',
    categoryId: 'cat-groceries',
    title: 'Im Supermarkt: finden und zahlen',
    blurb: 'Etwas suchen, Menge sagen, Tüte holen, zur Kasse.',
    scene: 'shop',
    partnerName: 'Mitarbeiter',
    turns: [
      {
        id: 'm1',
        speaker: 'partner',
        sv: 'Hej! Kan jag hjälpa dig, {name}?',
        de: 'Hallo! Kann ich dir helfen, {name}?',
        listenFirst: true,
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'kan', de: 'kann' },
          { sv: 'jag', de: 'ich' },
          { sv: 'hjälpa', de: 'helfen' },
          { sv: 'dig', de: 'dir' },
        ],
      },
      {
        id: 'm2',
        speaker: 'you',
        sv: 'var finns mjölk?',
        de: 'wo gibt es Milch?',
        chunkId: 'c-finnsmjolk',
        suggestions: ['Var finns mjölk?', 'Har ni bröd?'],
      },
      {
        id: 'm3',
        speaker: 'partner',
        sv: 'Där borta, till höger.',
        de: 'Da drüben, nach rechts.',
        decoding: [
          { sv: 'där', de: 'da' },
          { sv: 'borta', de: 'drüben' },
          { sv: 'till', de: 'nach' },
          { sv: 'höger', de: 'rechts' },
        ],
      },
      {
        id: 'm4',
        speaker: 'you',
        sv: 'ett kilo äpplen, tack',
        de: 'ein Kilo Äpfel, bitte',
        chunkId: 'c-kiloapplen',
        suggestions: ['Ett kilo äpplen, tack.', 'En påse, tack.'],
      },
      {
        id: 'm5',
        speaker: 'partner',
        sv: 'Varsågod. Något mer?',
        de: 'Bitte sehr. Sonst noch etwas?',
        decoding: [
          { sv: 'varsågod', de: 'bitte' },
          { sv: 'något', de: 'etwas' },
          { sv: 'mer', de: 'mehr' },
        ],
      },
      {
        id: 'm6',
        speaker: 'you',
        sv: 'en påse, tack',
        de: 'eine Tüte, bitte',
        chunkId: 'c-pase',
        suggestions: ['En påse, tack.', 'Nej, tack.'],
      },
      {
        id: 'm7',
        speaker: 'partner',
        sv: 'Här är den.',
        de: 'Hier ist sie.',
        decoding: [
          { sv: 'här', de: 'hier' },
          { sv: 'är', de: 'ist' },
          { sv: 'den', de: 'sie' },
        ],
      },
      {
        id: 'm8',
        speaker: 'you',
        sv: 'var är kassan?',
        de: 'wo ist die Kasse?',
        chunkId: 'c-kassan',
        suggestions: ['Var är kassan?', 'Var är toaletten?'],
      },
      {
        id: 'm9',
        speaker: 'partner',
        sv: 'Rakt fram. Ha det bra!',
        de: 'Geradeaus. Mach es gut!',
        decoding: [
          { sv: 'rakt', de: 'gerade' },
          { sv: 'fram', de: 'voraus' },
          { sv: 'ha', de: 'hab' },
          { sv: 'det', de: 'es' },
          { sv: 'bra', de: 'gut' },
        ],
      },
    ],
  },

  // ── Beim Arzt (cat-health) ───────────────────────────────────────────────────
  {
    id: 'dlg-arzt',
    categoryId: 'cat-health',
    title: 'Beim Arzt: sagen, was weh tut',
    blurb: 'Beschwerden schildern, Allergie nennen, Apotheke finden.',
    scene: 'clinic',
    partnerName: 'Ärztin',
    turns: [
      {
        id: 'a1',
        speaker: 'partner',
        sv: 'God dag {name}. Vad kan jag hjälpa till med?',
        de: 'Guten Tag {name}. Womit kann ich helfen?',
        listenFirst: true,
        decoding: [
          { sv: 'god', de: 'guten' },
          { sv: 'dag', de: 'Tag' },
          { sv: 'vad', de: 'was' },
          { sv: 'kan', de: 'kann' },
          { sv: 'jag', de: 'ich' },
          { sv: 'hjälpa', de: 'helfen' },
          { sv: 'till', de: 'bei' },
          { sv: 'med', de: 'mit' },
        ],
      },
      {
        id: 'a2',
        speaker: 'you',
        sv: 'jag är sjuk',
        de: 'ich bin krank',
        chunkId: 'c-sjuk',
        suggestions: ['Jag är sjuk.', 'Jag mår bra.'],
      },
      {
        id: 'a3',
        speaker: 'partner',
        sv: 'Jag förstår. Var gör det ont?',
        de: 'Ich verstehe. Wo tut es weh?',
        decoding: [
          { sv: 'jag', de: 'ich' },
          { sv: 'förstår', de: 'verstehe' },
          { sv: 'var', de: 'wo' },
          { sv: 'gör', de: 'macht' },
          { sv: 'det', de: 'es' },
          { sv: 'ont', de: 'Schmerz' },
        ],
      },
      {
        id: 'a4',
        speaker: 'you',
        sv: 'jag har ont här',
        de: 'mir tut es hier weh',
        chunkId: 'c-onthär',
        suggestions: ['Jag har ont här.', 'Jag har huvudvärk.'],
      },
      {
        id: 'a5',
        speaker: 'partner',
        sv: 'Har du feber också?',
        de: 'Hast du auch Fieber?',
        decoding: [
          { sv: 'har', de: 'hast' },
          { sv: 'du', de: 'du' },
          { sv: 'feber', de: 'Fieber' },
          { sv: 'också', de: 'auch' },
        ],
      },
      {
        id: 'a6',
        speaker: 'you',
        sv: 'jag har huvudvärk',
        de: 'ich habe Kopfschmerzen',
        chunkId: 'c-huvudvark',
        suggestions: ['Jag har huvudvärk.', 'Jag är törstig.'],
      },
      {
        id: 'a7',
        speaker: 'partner',
        sv: 'Tål du penicillin?',
        de: 'Verträgst du Penicillin?',
        decoding: [
          { sv: 'tål', de: 'verträgst' },
          { sv: 'du', de: 'du' },
          { sv: 'penicillin', de: 'Penicillin' },
        ],
      },
      {
        id: 'a8',
        speaker: 'you',
        sv: 'jag är allergisk',
        de: 'ich bin allergisch',
        chunkId: 'c-allergisk',
        suggestions: ['Jag är allergisk.', 'Nej, tack.'],
      },
      {
        id: 'a9',
        speaker: 'partner',
        sv: 'Tack, det är viktigt att veta.',
        de: 'Danke, das ist wichtig zu wissen.',
        decoding: [
          { sv: 'tack', de: 'danke' },
          { sv: 'det', de: 'das' },
          { sv: 'är', de: 'ist' },
          { sv: 'viktigt', de: 'wichtig' },
          { sv: 'att', de: 'zu' },
          { sv: 'veta', de: 'wissen' },
        ],
      },
      {
        id: 'a10',
        speaker: 'you',
        sv: 'var är apoteket?',
        de: 'wo ist die Apotheke?',
        chunkId: 'c-apoteket',
        suggestions: ['Var är apoteket?', 'Var är stationen?'],
      },
      {
        id: 'a11',
        speaker: 'partner',
        sv: 'Runt hörnet. Krya på dig!',
        de: 'Um die Ecke. Gute Besserung!',
        decoding: [
          { sv: 'runt', de: 'um' },
          { sv: 'hörnet', de: 'die Ecke' },
          { sv: 'krya', de: 'erhol' },
          { sv: 'på', de: 'auf' },
          { sv: 'dig', de: 'dich' },
        ],
      },
    ],
  },

  // ── Am Bahnhof: Ticket kaufen (cat-transport) ────────────────────────────────
  {
    id: 'dlg-ticket',
    categoryId: 'cat-transport',
    title: 'Am Schalter: Ticket kaufen',
    blurb: 'Fahrkarte lösen, Abfahrt und Gleis erfragen.',
    scene: 'station',
    partnerName: 'Schalter',
    turns: [
      {
        id: 't1',
        speaker: 'partner',
        sv: 'Hej {name}! Vart ska du åka?',
        de: 'Hallo {name}! Wohin möchtest du fahren?',
        listenFirst: true,
        decoding: [
          { sv: 'hej', de: 'hallo' },
          { sv: 'vart', de: 'wohin' },
          { sv: 'ska', de: 'sollst' },
          { sv: 'du', de: 'du' },
          { sv: 'åka', de: 'fahren' },
        ],
      },
      {
        id: 't2',
        speaker: 'you',
        sv: 'en biljett, tack',
        de: 'ein Ticket, bitte',
        chunkId: 'c-biljett',
        suggestions: ['En biljett, tack.', 'En påse, tack.'],
      },
      {
        id: 't3',
        speaker: 'partner',
        sv: 'Till Göteborg? Det blir hundra kronor.',
        de: 'Nach Göteborg? Das macht hundert Kronen.',
        decoding: [
          { sv: 'till', de: 'nach' },
          { sv: 'Göteborg', de: 'Göteborg' },
          { sv: 'det', de: 'das' },
          { sv: 'blir', de: 'wird' },
          { sv: 'hundra', de: 'hundert' },
          { sv: 'kronor', de: 'Kronen' },
        ],
      },
      {
        id: 't4',
        speaker: 'you',
        sv: 'när går tåget?',
        de: 'wann fährt der Zug?',
        chunkId: 'c-nartag',
        suggestions: ['När går tåget?', 'När går bussen?'],
      },
      {
        id: 't5',
        speaker: 'partner',
        sv: 'Om tjugo minuter.',
        de: 'In zwanzig Minuten.',
        decoding: [
          { sv: 'om', de: 'in' },
          { sv: 'tjugo', de: 'zwanzig' },
          { sv: 'minuter', de: 'Minuten' },
        ],
      },
      {
        id: 't6',
        speaker: 'you',
        sv: 'vilket spår?',
        de: 'welches Gleis?',
        chunkId: 'c-spar',
        suggestions: ['Vilket spår?', 'Vilken storlek?'],
      },
      {
        id: 't7',
        speaker: 'partner',
        sv: 'Spår tre. Trevlig resa!',
        de: 'Gleis drei. Gute Reise!',
        decoding: [
          { sv: 'spår', de: 'Gleis' },
          { sv: 'tre', de: 'drei' },
          { sv: 'trevlig', de: 'angenehme' },
          { sv: 'resa', de: 'Reise' },
        ],
      },
      {
        id: 't8',
        speaker: 'you',
        sv: 'tack så mycket',
        de: 'danke vielmals',
        chunkId: 'c-tack',
        suggestions: ['Tack så mycket.', 'Ha det bra.'],
      },
    ],
  },
];
