// A1 — AUSBAU. Neue Themen auf dem Grundstock-Meilenstein.
//
// ⚠️ EHRLICH (gilt für alle Inhaltsdateien): verfasst von uns/der KI, maschinell
// vorgeprüft (jedes Wort echtes Schwedisch), aber NICHT muttersprachlich
// gegengelesen — Wortstellung, Idiomatik und Ton hat hier niemand geprüft.
// Diese Grenze steht auch in der App (docs/content-review-schwedisch.md).
//
// Aufbau je Thema: 8 Wendungen, je 2 eigene Kontexte plus gemischte Sätze —
// Kontextvariation ist Schritt 4 des Lern-Loops (docs/03-method.md), nicht Deko.

import type { Category, Chunk, Segment } from '../../domain/chunk';

export const categories: Category[] = [
  { id: 'cat-time', areaId: 'area-basics', title: 'Zeit & Uhrzeit', blurb: 'Wie spät ist es, wann, wie lange.', order: 5, cefr: 'A1' },
  { id: 'cat-week', areaId: 'area-basics', title: 'Tage & Jahreszeiten', blurb: 'Wochentage, Wochenende, Monate, Sommer und Winter.', order: 6, cefr: 'A1' },
  { id: 'cat-fika', areaId: 'area-food', title: 'Fika & Süßes', blurb: 'Die schwedische Kaffeepause — Kaffee, Kuchen, sitzen bleiben.', order: 4, cefr: 'A1' },
  { id: 'cat-language', areaId: 'area-basics', title: 'Sprache & Lernen', blurb: 'Nach Wörtern fragen, buchstabieren, üben.', order: 7, cefr: 'A1' },
  { id: 'cat-smalltalk', areaId: 'area-people', title: 'Small Talk', blurb: 'Kurz plaudern, Anteil nehmen, sich verabschieden.', order: 7, cefr: 'A1' },
];

export const chunks: Chunk[] = [
  // ── Zeit & Uhrzeit ────────────────────────────────────────────────────────
  { id: 'c-vilkentidpassar', categoryId: 'cat-time', sv: 'vilken tid passar dig?', de: 'welche Zeit passt dir?', decoding: [{ sv: 'vilken', de: 'welche' }, { sv: 'tid', de: 'Zeit' }, { sv: 'passar', de: 'passt' }, { sv: 'dig', de: 'dir' }] },
  { id: 'c-kvartover', categoryId: 'cat-time', sv: 'klockan är kvart över tre', de: 'es ist Viertel nach drei', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }] },
  { id: 'c-halvfyra', categoryId: 'cat-time', sv: 'klockan är halv fyra', de: 'es ist halb vier', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'halv', de: 'halb' }, { sv: 'fyra', de: 'vier' }] },
  { id: 'c-imorgon', categoryId: 'cat-time', sv: 'vi ses i morgon', de: 'wir sehen uns morgen', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }] },
  { id: 'c-varigar', categoryId: 'cat-time', sv: 'det var igår', de: 'das war gestern', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'igår', de: 'gestern' }] },
  { id: 'c-kommernu', categoryId: 'cat-time', sv: 'jag kommer nu', de: 'ich komme jetzt', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'nu', de: 'jetzt' }] },
  { id: 'c-horssenare', categoryId: 'cat-time', sv: 'vi hörs senare', de: 'wir hören uns später', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'hörs', de: 'hören uns' }, { sv: 'senare', de: 'später' }] },
  { id: 'c-hurlangtid', categoryId: 'cat-time', sv: 'hur lång tid tar det?', de: 'wie lange dauert das?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'lång', de: 'lange' }, { sv: 'tid', de: 'Zeit' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }] },

  // ── Tage & Jahreszeiten ───────────────────────────────────────────────────
  { id: 'c-idagartorsdag', categoryId: 'cat-week', sv: 'idag är det torsdag', de: 'heute ist Donnerstag', decoding: [{ sv: 'idag', de: 'heute' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'torsdag', de: 'Donnerstag' }] },
  { id: 'c-pamandag', categoryId: 'cat-week', sv: 'det passar på måndag', de: 'am Montag passt es', decoding: [{ sv: 'det', de: 'es' }, { sv: 'passar', de: 'passt' }, { sv: 'på', de: 'am' }, { sv: 'måndag', de: 'Montag' }] },
  { id: 'c-ledigihelgen', categoryId: 'cat-week', sv: 'jag är ledig i helgen', de: 'am Wochenende habe ich frei', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'ledig', de: 'frei' }, { sv: 'i', de: 'an' }, { sv: 'helgen', de: 'dem Wochenende' }] },
  { id: 'c-nastavecka', categoryId: 'cat-week', sv: 'vi ses nästa vecka', de: 'wir sehen uns nächste Woche', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'nästa', de: 'nächste' }, { sv: 'vecka', de: 'Woche' }] },
  { id: 'c-omenvecka', categoryId: 'cat-week', sv: 'jag kommer om en vecka', de: 'ich komme in einer Woche', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'om', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'vecka', de: 'Woche' }] },
  { id: 'c-ijanuari', categoryId: 'cat-week', sv: 'i januari är det kallt', de: 'im Januar ist es kalt', decoding: [{ sv: 'i', de: 'im' }, { sv: 'januari', de: 'Januar' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'kallt', de: 'kalt' }] },
  { id: 'c-pasommaren', categoryId: 'cat-week', sv: 'på sommaren är det ljust', de: 'im Sommer ist es hell', decoding: [{ sv: 'på', de: 'im' }, { sv: 'sommaren', de: 'dem Sommer' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'ljust', de: 'hell' }] },
  { id: 'c-fyllerar', categoryId: 'cat-week', sv: 'när fyller du år?', de: 'wann hast du Geburtstag?', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'fyller', de: 'füllst' }, { sv: 'du', de: 'du' }, { sv: 'år', de: 'Jahre' }] },

  // ── Fika & Süßes ──────────────────────────────────────────────────────────
  { id: 'c-skavifika', categoryId: 'cat-fika', sv: 'ska vi fika?', de: 'wollen wir Kaffee trinken?', decoding: [{ sv: 'ska', de: 'sollen' }, { sv: 'vi', de: 'wir' }, { sv: 'fika', de: 'Kaffeepause machen' }] },
  { id: 'c-kaffeochkaka', categoryId: 'cat-fika', sv: 'kaffe och kaka, tack', de: 'Kaffee und Kuchen, bitte', decoding: [{ sv: 'kaffe', de: 'Kaffee' }, { sv: 'och', de: 'und' }, { sv: 'kaka', de: 'Kuchen' }, { sv: 'tack', de: 'bitte' }] },
  { id: 'c-teellerkaffe', categoryId: 'cat-fika', sv: 'te eller kaffe?', de: 'Tee oder Kaffee?', decoding: [{ sv: 'te', de: 'Tee' }, { sv: 'eller', de: 'oder' }, { sv: 'kaffe', de: 'Kaffee' }] },
  { id: 'c-medmjolk', categoryId: 'cat-fika', sv: 'med mjölk, tack', de: 'mit Milch, bitte', decoding: [{ sv: 'med', de: 'mit' }, { sv: 'mjölk', de: 'Milch' }, { sv: 'tack', de: 'bitte' }] },
  { id: 'c-enkopptill', categoryId: 'cat-fika', sv: 'en kopp till, tack', de: 'noch eine Tasse, bitte', decoding: [{ sv: 'en', de: 'eine' }, { sv: 'kopp', de: 'Tasse' }, { sv: 'till', de: 'noch' }, { sv: 'tack', de: 'bitte' }] },
  { id: 'c-sittahar', categoryId: 'cat-fika', sv: 'kan vi sitta här?', de: 'können wir hier sitzen?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'sitta', de: 'sitzen' }, { sv: 'här', de: 'hier' }] },
  { id: 'c-smakarbra', categoryId: 'cat-fika', sv: 'det smakar bra', de: 'das schmeckt gut', decoding: [{ sv: 'det', de: 'das' }, { sv: 'smakar', de: 'schmeckt' }, { sv: 'bra', de: 'gut' }] },
  { id: 'c-nagotsott', categoryId: 'cat-fika', sv: 'har ni något sött?', de: 'habt ihr etwas Süßes?', decoding: [{ sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'något', de: 'etwas' }, { sv: 'sött', de: 'Süßes' }] },

  // ── Sprache & Lernen ──────────────────────────────────────────────────────
  { id: 'c-jagarnyborjare', categoryId: 'cat-language', sv: 'jag är nybörjare', de: 'ich bin Anfänger', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'nybörjare', de: 'Anfänger' }] },
  { id: 'c-larmigsvenska', categoryId: 'cat-language', sv: 'jag lär mig svenska', de: 'ich lerne Schwedisch', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'lär', de: 'lehre' }, { sv: 'mig', de: 'mich' }, { sv: 'svenska', de: 'Schwedisch' }] },
  { id: 'c-pratarlite', categoryId: 'cat-language', sv: 'jag pratar lite svenska', de: 'ich spreche ein bisschen Schwedisch', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'pratar', de: 'spreche' }, { sv: 'lite', de: 'wenig' }, { sv: 'svenska', de: 'Schwedisch' }] },
  { id: 'c-hururtalar', categoryId: 'cat-language', sv: 'hur uttalar man det?', de: 'wie spricht man das aus?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'uttalar', de: 'spricht aus' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }] },
  { id: 'c-hurstavar', categoryId: 'cat-language', sv: 'hur stavar man det?', de: 'wie schreibt man das?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'stavar', de: 'buchstabiert' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }] },
  { id: 'c-kanduskriva', categoryId: 'cat-language', sv: 'kan du skriva det?', de: 'kannst du das schreiben?', decoding: [{ sv: 'kan', de: 'kannst' }, { sv: 'du', de: 'du' }, { sv: 'skriva', de: 'schreiben' }, { sv: 'det', de: 'es' }] },
  { id: 'c-vadardetforord', categoryId: 'cat-language', sv: 'vad är det för ord?', de: 'was ist das für ein Wort?', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'das' }, { sv: 'för', de: 'für' }, { sv: 'ord', de: 'Wort' }] },
  { id: 'c-ovarvarjedag', categoryId: 'cat-language', sv: 'jag övar varje dag', de: 'ich übe jeden Tag', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'övar', de: 'übe' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }] },

  // ── Small Talk ────────────────────────────────────────────────────────────
  { id: 'c-hurgardet', categoryId: 'cat-smalltalk', sv: 'hur går det?', de: 'wie läuft es?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }] },
  { id: 'c-detgarbra', categoryId: 'cat-smalltalk', sv: 'det går bra, tack', de: 'es läuft gut, danke', decoding: [{ sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'bra', de: 'gut' }, { sv: 'tack', de: 'danke' }] },
  { id: 'c-vadroligt', categoryId: 'cat-smalltalk', sv: 'vad roligt!', de: 'wie schön!', decoding: [{ sv: 'vad', de: 'wie' }, { sv: 'roligt', de: 'lustig' }] },
  { id: 'c-sasynd', categoryId: 'cat-smalltalk', sv: 'så synd!', de: 'wie schade!', decoding: [{ sv: 'så', de: 'so' }, { sv: 'synd', de: 'schade' }] },
  { id: 'c-sessnart', categoryId: 'cat-smalltalk', sv: 'vi måste ses snart', de: 'wir müssen uns bald sehen', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'snart', de: 'bald' }] },
  { id: 'c-halsahemma', categoryId: 'cat-smalltalk', sv: 'hälsa hemma!', de: 'grüß zu Hause!', decoding: [{ sv: 'hälsa', de: 'grüße' }, { sv: 'hemma', de: 'daheim' }] },
  { id: 'c-mastega', categoryId: 'cat-smalltalk', sv: 'jag måste gå nu', de: 'ich muss jetzt gehen', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'gå', de: 'gehen' }, { sv: 'nu', de: 'jetzt' }] },
  { id: 'c-vartrevligt', categoryId: 'cat-smalltalk', sv: 'det var trevligt', de: 'das war nett', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'trevligt', de: 'nett' }] },
];

export const segments: Segment[] = [
  // ── Zeit & Uhrzeit ────────────────────────────────────────────────────────
  { id: 's-a1t-klockan1', level: 1, sv: 'Vilken tid passar dig på fredag?', de: 'Welche Zeit passt dir am Freitag?', decoding: [{ sv: 'vilken', de: 'welche' }, { sv: 'tid', de: 'Zeit' }, { sv: 'passar', de: 'passt' }, { sv: 'dig', de: 'dir' }, { sv: 'på', de: 'am' }, { sv: 'fredag', de: 'Freitag' }], chunkIds: ['c-vilkentidpassar'] },
  { id: 's-a1t-klockan2', level: 1, sv: 'Vilken tid passar dig? Jag är ledig hela dagen.', de: 'Welche Zeit passt dir? Ich habe den ganzen Tag frei.', decoding: [{ sv: 'vilken', de: 'welche' }, { sv: 'tid', de: 'Zeit' }, { sv: 'passar', de: 'passt' }, { sv: 'dig', de: 'dir' }, { sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'ledig', de: 'frei' }, { sv: 'hela', de: 'ganzen' }, { sv: 'dagen', de: 'den Tag' }], chunkIds: ['c-vilkentidpassar'] },
  { id: 's-a1t-tre1', level: 1, sv: 'Klockan är kvart över tre, vi har gott om tid.', de: 'Es ist Viertel nach drei, wir haben genug Zeit.', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }, { sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'gott', de: 'gut' }, { sv: 'om', de: 'um' }, { sv: 'tid', de: 'Zeit' }], chunkIds: ['c-kvartover'] },
  { id: 's-a1t-tre2', level: 1, sv: 'Nu är klockan kvart över tre och jag är trött.', de: 'Jetzt ist es Viertel nach drei und ich bin müde.', decoding: [{ sv: 'nu', de: 'jetzt' }, { sv: 'är', de: 'ist' }, { sv: 'klockan', de: 'die Uhr' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }, { sv: 'och', de: 'und' }, { sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'trött', de: 'müde' }], chunkIds: ['c-kvartover'] },
  { id: 's-a1t-halv1', level: 1, sv: 'Klockan är halv fyra, vi måste gå.', de: 'Es ist halb vier, wir müssen los.', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'halv', de: 'halb' }, { sv: 'fyra', de: 'vier' }, { sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'gå', de: 'gehen' }], chunkIds: ['c-halvfyra'] },
  { id: 's-a1t-halv2', level: 1, sv: 'Mötet börjar när klockan är halv fyra.', de: 'Das Treffen beginnt, wenn es halb vier ist.', decoding: [{ sv: 'mötet', de: 'das Treffen' }, { sv: 'börjar', de: 'beginnt' }, { sv: 'när', de: 'wenn' }, { sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'halv', de: 'halb' }, { sv: 'fyra', de: 'vier' }], chunkIds: ['c-halvfyra'] },
  { id: 's-a1t-imorgon1', level: 1, sv: 'Tack för idag, vi ses i morgon!', de: 'Danke für heute, wir sehen uns morgen!', decoding: [{ sv: 'tack', de: 'danke' }, { sv: 'för', de: 'für' }, { sv: 'idag', de: 'heute' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }], chunkIds: ['c-imorgon'] },
  { id: 's-a1t-imorgon2', level: 1, sv: 'Jag jobbar sent, så vi ses i morgon.', de: 'Ich arbeite lange, also sehen wir uns morgen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'jobbar', de: 'arbeite' }, { sv: 'sent', de: 'spät' }, { sv: 'så', de: 'so' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }], chunkIds: ['c-imorgon'] },
  { id: 's-a1t-igar1', level: 1, sv: 'Det var igår, inte idag.', de: 'Das war gestern, nicht heute.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'igår', de: 'gestern' }, { sv: 'inte', de: 'nicht' }, { sv: 'idag', de: 'heute' }], chunkIds: ['c-varigar'] },
  { id: 's-a1t-igar2', level: 1, sv: 'Mötet? Det var igår kvart över tre.', de: 'Das Treffen? Das war gestern um Viertel nach drei.', decoding: [{ sv: 'mötet', de: 'das Treffen' }, { sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'igår', de: 'gestern' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }], chunkIds: ['c-varigar', 'c-kvartover'] },
  { id: 's-a1t-nu1', level: 1, sv: 'Vänta lite, jag kommer nu!', de: 'Warte kurz, ich komme jetzt!', decoding: [{ sv: 'vänta', de: 'warte' }, { sv: 'lite', de: 'wenig' }, { sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-kommernu'] },
  { id: 's-a1t-nu2', level: 1, sv: 'Jag kommer nu, jag är nästan framme.', de: 'Ich komme jetzt, ich bin fast da.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'nu', de: 'jetzt' }, { sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'nästan', de: 'fast' }, { sv: 'framme', de: 'angekommen' }], chunkIds: ['c-kommernu'] },
  { id: 's-a1t-senare1', level: 1, sv: 'Jag måste gå nu. Vi hörs senare!', de: 'Ich muss jetzt gehen. Wir hören uns später!', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'gå', de: 'gehen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'vi', de: 'wir' }, { sv: 'hörs', de: 'hören uns' }, { sv: 'senare', de: 'später' }], chunkIds: ['c-horssenare', 'c-mastega'] },
  { id: 's-a1t-senare2', level: 1, sv: 'Vi hörs senare i kväll.', de: 'Wir hören uns später am Abend.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'hörs', de: 'hören uns' }, { sv: 'senare', de: 'später' }, { sv: 'i', de: 'am' }, { sv: 'kväll', de: 'Abend' }], chunkIds: ['c-horssenare'] },
  { id: 's-a1t-langtid1', level: 1, sv: 'Hur lång tid tar det till Malmö?', de: 'Wie lange dauert es nach Malmö?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'lång', de: 'lange' }, { sv: 'tid', de: 'Zeit' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'till', de: 'nach' }, { sv: 'Malmö', de: 'Malmö' }], chunkIds: ['c-hurlangtid'] },
  { id: 's-a1t-langtid2', level: 1, sv: 'Hur lång tid tar det? Jag har bråttom.', de: 'Wie lange dauert das? Ich habe es eilig.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'lång', de: 'lange' }, { sv: 'tid', de: 'Zeit' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'jag', de: 'ich' }, { sv: 'har', de: 'habe' }, { sv: 'bråttom', de: 'eilig' }], chunkIds: ['c-hurlangtid'] },
  { id: 's-a1t-mix1', level: 1, sv: 'Vilken tid passar dig? Vi ses i morgon.', de: 'Welche Zeit passt dir? Wir sehen uns morgen.', decoding: [{ sv: 'vilken', de: 'welche' }, { sv: 'tid', de: 'Zeit' }, { sv: 'passar', de: 'passt' }, { sv: 'dig', de: 'dir' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }], chunkIds: ['c-vilkentidpassar', 'c-imorgon'] },
  { id: 's-a1t-mix2', level: 1, sv: 'Klockan är halv fyra, vi hörs senare.', de: 'Es ist halb vier, wir hören uns später.', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'halv', de: 'halb' }, { sv: 'fyra', de: 'vier' }, { sv: 'vi', de: 'wir' }, { sv: 'hörs', de: 'hören uns' }, { sv: 'senare', de: 'später' }], chunkIds: ['c-halvfyra', 'c-horssenare'] },
  { id: 's-a1t-mix3', level: 1, sv: 'Hur lång tid tar det? Jag kommer nu.', de: 'Wie lange dauert es? Ich komme jetzt.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'lång', de: 'lange' }, { sv: 'tid', de: 'Zeit' }, { sv: 'tar', de: 'nimmt' }, { sv: 'det', de: 'es' }, { sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-hurlangtid', 'c-kommernu'] },
  { id: 's-a1t-mix4', level: 1, sv: 'Det var igår. Klockan är kvart över tre nu.', de: 'Das war gestern. Jetzt ist es Viertel nach drei.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'igår', de: 'gestern' }, { sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-varigar', 'c-kvartover'] },

  // ── Tage & Jahreszeiten ───────────────────────────────────────────────────
  { id: 's-a1v-dag1', level: 1, sv: 'Idag är det torsdag, inte fredag.', de: 'Heute ist Donnerstag, nicht Freitag.', decoding: [{ sv: 'idag', de: 'heute' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'torsdag', de: 'Donnerstag' }, { sv: 'inte', de: 'nicht' }, { sv: 'fredag', de: 'Freitag' }], chunkIds: ['c-idagartorsdag'] },
  { id: 's-a1v-dag2', level: 1, sv: 'Idag är det torsdag och i morgon är det fredag.', de: 'Heute ist Donnerstag und morgen ist Freitag.', decoding: [{ sv: 'idag', de: 'heute' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'torsdag', de: 'Donnerstag' }, { sv: 'och', de: 'und' }, { sv: 'i', de: 'am' }, { sv: 'morgon', de: 'Morgen' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'fredag', de: 'Freitag' }], chunkIds: ['c-idagartorsdag'] },
  { id: 's-a1v-mandag1', level: 1, sv: 'Det passar på måndag, före lunch.', de: 'Am Montag passt es, vor dem Mittagessen.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'passar', de: 'passt' }, { sv: 'på', de: 'am' }, { sv: 'måndag', de: 'Montag' }, { sv: 'före', de: 'vor' }, { sv: 'lunch', de: 'Mittagessen' }], chunkIds: ['c-pamandag'] },
  { id: 's-a1v-mandag2', level: 1, sv: 'Inte i dag, men det passar på måndag.', de: 'Nicht heute, aber am Montag passt es.', decoding: [{ sv: 'inte', de: 'nicht' }, { sv: 'i', de: 'am' }, { sv: 'dag', de: 'Tag' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'es' }, { sv: 'passar', de: 'passt' }, { sv: 'på', de: 'am' }, { sv: 'måndag', de: 'Montag' }], chunkIds: ['c-pamandag'] },
  { id: 's-a1v-helg1', level: 1, sv: 'Jag är ledig i helgen, vi kan träffas.', de: 'Am Wochenende habe ich frei, wir können uns treffen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'ledig', de: 'frei' }, { sv: 'i', de: 'an' }, { sv: 'helgen', de: 'dem Wochenende' }, { sv: 'vi', de: 'wir' }, { sv: 'kan', de: 'können' }, { sv: 'träffas', de: 'treffen' }], chunkIds: ['c-ledigihelgen'] },
  { id: 's-a1v-helg2', level: 1, sv: 'Jag är ledig i helgen och åker till stugan.', de: 'Am Wochenende habe ich frei und fahre zur Hütte.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'ledig', de: 'frei' }, { sv: 'i', de: 'an' }, { sv: 'helgen', de: 'dem Wochenende' }, { sv: 'och', de: 'und' }, { sv: 'åker', de: 'fahre' }, { sv: 'till', de: 'zu' }, { sv: 'stugan', de: 'der Hütte' }], chunkIds: ['c-ledigihelgen'] },
  { id: 's-a1v-nasta1', level: 1, sv: 'Ha det bra, vi ses nästa vecka!', de: 'Mach es gut, wir sehen uns nächste Woche!', decoding: [{ sv: 'ha', de: 'habe' }, { sv: 'det', de: 'es' }, { sv: 'bra', de: 'gut' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'nästa', de: 'nächste' }, { sv: 'vecka', de: 'Woche' }], chunkIds: ['c-nastavecka'] },
  { id: 's-a1v-nasta2', level: 1, sv: 'Kursen börjar sent, så vi ses nästa vecka.', de: 'Der Kurs beginnt spät, also sehen wir uns nächste Woche.', decoding: [{ sv: 'kursen', de: 'der Kurs' }, { sv: 'börjar', de: 'beginnt' }, { sv: 'sent', de: 'spät' }, { sv: 'så', de: 'so' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'nästa', de: 'nächste' }, { sv: 'vecka', de: 'Woche' }], chunkIds: ['c-nastavecka'] },
  { id: 's-a1v-omvecka1', level: 1, sv: 'Jag kommer om en vecka, inte förr.', de: 'Ich komme in einer Woche, nicht früher.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'om', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'vecka', de: 'Woche' }, { sv: 'inte', de: 'nicht' }, { sv: 'förr', de: 'früher' }], chunkIds: ['c-omenvecka'] },
  { id: 's-a1v-omvecka2', level: 1, sv: 'Jag kommer om en vecka och stannar länge.', de: 'Ich komme in einer Woche und bleibe lange.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'om', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'vecka', de: 'Woche' }, { sv: 'och', de: 'und' }, { sv: 'stannar', de: 'bleibe' }, { sv: 'länge', de: 'lange' }], chunkIds: ['c-omenvecka'] },
  { id: 's-a1v-januari1', level: 1, sv: 'I januari är det kallt och mörkt.', de: 'Im Januar ist es kalt und dunkel.', decoding: [{ sv: 'i', de: 'im' }, { sv: 'januari', de: 'Januar' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'kallt', de: 'kalt' }, { sv: 'och', de: 'und' }, { sv: 'mörkt', de: 'dunkel' }], chunkIds: ['c-ijanuari'] },
  { id: 's-a1v-januari2', level: 1, sv: 'Ta med mössa, i januari är det kallt.', de: 'Nimm eine Mütze mit, im Januar ist es kalt.', decoding: [{ sv: 'ta', de: 'nimm' }, { sv: 'med', de: 'mit' }, { sv: 'mössa', de: 'Mütze' }, { sv: 'i', de: 'im' }, { sv: 'januari', de: 'Januar' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'kallt', de: 'kalt' }], chunkIds: ['c-ijanuari'] },
  { id: 's-a1v-sommar1', level: 1, sv: 'På sommaren är det ljust hela natten.', de: 'Im Sommer ist es die ganze Nacht hell.', decoding: [{ sv: 'på', de: 'im' }, { sv: 'sommaren', de: 'dem Sommer' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'ljust', de: 'hell' }, { sv: 'hela', de: 'ganze' }, { sv: 'natten', de: 'die Nacht' }], chunkIds: ['c-pasommaren'] },
  { id: 's-a1v-sommar2', level: 1, sv: 'På sommaren är det ljust, på vintern mörkt.', de: 'Im Sommer ist es hell, im Winter dunkel.', decoding: [{ sv: 'på', de: 'im' }, { sv: 'sommaren', de: 'dem Sommer' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'ljust', de: 'hell' }, { sv: 'på', de: 'im' }, { sv: 'vintern', de: 'dem Winter' }, { sv: 'mörkt', de: 'dunkel' }], chunkIds: ['c-pasommaren'] },
  { id: 's-a1v-fyller1', level: 1, sv: 'När fyller du år? I mars?', de: 'Wann hast du Geburtstag? Im März?', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'fyller', de: 'füllst' }, { sv: 'du', de: 'du' }, { sv: 'år', de: 'Jahre' }, { sv: 'i', de: 'im' }, { sv: 'mars', de: 'März' }], chunkIds: ['c-fyllerar'] },
  { id: 's-a1v-fyller2', level: 1, sv: 'Grattis! När fyller du år egentligen?', de: 'Glückwunsch! Wann hast du eigentlich Geburtstag?', decoding: [{ sv: 'grattis', de: 'Glückwunsch' }, { sv: 'när', de: 'wann' }, { sv: 'fyller', de: 'füllst' }, { sv: 'du', de: 'du' }, { sv: 'år', de: 'Jahre' }, { sv: 'egentligen', de: 'eigentlich' }], chunkIds: ['c-fyllerar'] },
  { id: 's-a1v-mix1', level: 1, sv: 'Idag är det torsdag. Det passar på måndag.', de: 'Heute ist Donnerstag. Am Montag passt es.', decoding: [{ sv: 'idag', de: 'heute' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'torsdag', de: 'Donnerstag' }, { sv: 'det', de: 'es' }, { sv: 'passar', de: 'passt' }, { sv: 'på', de: 'am' }, { sv: 'måndag', de: 'Montag' }], chunkIds: ['c-idagartorsdag', 'c-pamandag'] },
  { id: 's-a1v-mix2', level: 1, sv: 'Jag är ledig i helgen, men vi ses nästa vecka.', de: 'Am Wochenende habe ich frei, aber wir sehen uns nächste Woche.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'ledig', de: 'frei' }, { sv: 'i', de: 'an' }, { sv: 'helgen', de: 'dem Wochenende' }, { sv: 'men', de: 'aber' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'nästa', de: 'nächste' }, { sv: 'vecka', de: 'Woche' }], chunkIds: ['c-ledigihelgen', 'c-nastavecka'] },
  { id: 's-a1v-mix3', level: 1, sv: 'I januari är det kallt, men på sommaren är det ljust.', de: 'Im Januar ist es kalt, aber im Sommer ist es hell.', decoding: [{ sv: 'i', de: 'im' }, { sv: 'januari', de: 'Januar' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'kallt', de: 'kalt' }, { sv: 'men', de: 'aber' }, { sv: 'på', de: 'im' }, { sv: 'sommaren', de: 'dem Sommer' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'ljust', de: 'hell' }], chunkIds: ['c-ijanuari', 'c-pasommaren'] },
  { id: 's-a1v-mix4', level: 1, sv: 'När fyller du år? Jag kommer om en vecka.', de: 'Wann hast du Geburtstag? Ich komme in einer Woche.', decoding: [{ sv: 'när', de: 'wann' }, { sv: 'fyller', de: 'füllst' }, { sv: 'du', de: 'du' }, { sv: 'år', de: 'Jahre' }, { sv: 'jag', de: 'ich' }, { sv: 'kommer', de: 'komme' }, { sv: 'om', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'vecka', de: 'Woche' }], chunkIds: ['c-fyllerar', 'c-omenvecka'] },

  // ── Fika & Süßes ──────────────────────────────────────────────────────────
  { id: 's-a1f-fika1', level: 1, sv: 'Ska vi fika? Jag bjuder.', de: 'Wollen wir Kaffee trinken? Ich lade ein.', decoding: [{ sv: 'ska', de: 'sollen' }, { sv: 'vi', de: 'wir' }, { sv: 'fika', de: 'Kaffeepause machen' }, { sv: 'jag', de: 'ich' }, { sv: 'bjuder', de: 'lade ein' }], chunkIds: ['c-skavifika'] },
  { id: 's-a1f-fika2', level: 1, sv: 'Klockan är kvart över tre. Ska vi fika nu?', de: 'Es ist Viertel nach drei. Wollen wir jetzt Kaffee trinken?', decoding: [{ sv: 'klockan', de: 'die Uhr' }, { sv: 'är', de: 'ist' }, { sv: 'kvart', de: 'Viertel' }, { sv: 'över', de: 'über' }, { sv: 'tre', de: 'drei' }, { sv: 'ska', de: 'sollen' }, { sv: 'vi', de: 'wir' }, { sv: 'fika', de: 'Kaffeepause machen' }, { sv: 'nu', de: 'jetzt' }], chunkIds: ['c-skavifika', 'c-kvartover'] },
  { id: 's-a1f-kaka1', level: 1, sv: 'Kaffe och kaka, tack. Vad kostar det?', de: 'Kaffee und Kuchen, bitte. Was kostet das?', decoding: [{ sv: 'kaffe', de: 'Kaffee' }, { sv: 'och', de: 'und' }, { sv: 'kaka', de: 'Kuchen' }, { sv: 'tack', de: 'bitte' }, { sv: 'vad', de: 'was' }, { sv: 'kostar', de: 'kostet' }, { sv: 'det', de: 'das' }], chunkIds: ['c-kaffeochkaka', 'c-kostar'] },
  { id: 's-a1f-kaka2', level: 1, sv: 'För mig kaffe och kaka, tack.', de: 'Für mich Kaffee und Kuchen, bitte.', decoding: [{ sv: 'för', de: 'für' }, { sv: 'mig', de: 'mich' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'och', de: 'und' }, { sv: 'kaka', de: 'Kuchen' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-kaffeochkaka'] },
  { id: 's-a1f-te1', level: 1, sv: 'Te eller kaffe? Vi har båda.', de: 'Tee oder Kaffee? Wir haben beides.', decoding: [{ sv: 'te', de: 'Tee' }, { sv: 'eller', de: 'oder' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'båda', de: 'beide' }], chunkIds: ['c-teellerkaffe'] },
  { id: 's-a1f-te2', level: 1, sv: 'Vill du ha te eller kaffe till kakan?', de: 'Möchtest du Tee oder Kaffee zum Kuchen?', decoding: [{ sv: 'vill', de: 'willst' }, { sv: 'du', de: 'du' }, { sv: 'ha', de: 'haben' }, { sv: 'te', de: 'Tee' }, { sv: 'eller', de: 'oder' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'till', de: 'zu' }, { sv: 'kakan', de: 'dem Kuchen' }], chunkIds: ['c-teellerkaffe'] },
  { id: 's-a1f-mjolk1', level: 1, sv: 'Med mjölk, tack. Inget socker.', de: 'Mit Milch, bitte. Keinen Zucker.', decoding: [{ sv: 'med', de: 'mit' }, { sv: 'mjölk', de: 'Milch' }, { sv: 'tack', de: 'bitte' }, { sv: 'inget', de: 'kein' }, { sv: 'socker', de: 'Zucker' }], chunkIds: ['c-medmjolk'] },
  { id: 's-a1f-mjolk2', level: 1, sv: 'En kaffe med mjölk, tack.', de: 'Einen Kaffee mit Milch, bitte.', decoding: [{ sv: 'en', de: 'einen' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'med', de: 'mit' }, { sv: 'mjölk', de: 'Milch' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-medmjolk'] },
  { id: 's-a1f-kopp1', level: 1, sv: 'En kopp till, tack. Den var god.', de: 'Noch eine Tasse, bitte. Die war gut.', decoding: [{ sv: 'en', de: 'eine' }, { sv: 'kopp', de: 'Tasse' }, { sv: 'till', de: 'noch' }, { sv: 'tack', de: 'bitte' }, { sv: 'den', de: 'die' }, { sv: 'var', de: 'war' }, { sv: 'god', de: 'gut' }], chunkIds: ['c-enkopptill'] },
  { id: 's-a1f-kopp2', level: 1, sv: 'Jag tar en kopp till, tack.', de: 'Ich nehme noch eine Tasse, bitte.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'tar', de: 'nehme' }, { sv: 'en', de: 'eine' }, { sv: 'kopp', de: 'Tasse' }, { sv: 'till', de: 'noch' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-enkopptill'] },
  { id: 's-a1f-sitta1', level: 1, sv: 'Kan vi sitta här? Det är ledigt.', de: 'Können wir hier sitzen? Es ist frei.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'sitta', de: 'sitzen' }, { sv: 'här', de: 'hier' }, { sv: 'det', de: 'es' }, { sv: 'är', de: 'ist' }, { sv: 'ledigt', de: 'frei' }], chunkIds: ['c-sittahar'] },
  { id: 's-a1f-sitta2', level: 1, sv: 'Kan vi sitta här vid fönstret?', de: 'Können wir hier am Fenster sitzen?', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'sitta', de: 'sitzen' }, { sv: 'här', de: 'hier' }, { sv: 'vid', de: 'bei' }, { sv: 'fönstret', de: 'dem Fenster' }], chunkIds: ['c-sittahar'] },
  { id: 's-a1f-smakar1', level: 1, sv: 'Det smakar bra, tack så mycket.', de: 'Das schmeckt gut, vielen Dank.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'smakar', de: 'schmeckt' }, { sv: 'bra', de: 'gut' }, { sv: 'tack', de: 'danke' }, { sv: 'så', de: 'so' }, { sv: 'mycket', de: 'viel' }], chunkIds: ['c-smakarbra', 'c-tack'] },
  { id: 's-a1f-smakar2', level: 1, sv: 'Kakan är hemmagjord och det smakar bra.', de: 'Der Kuchen ist selbstgemacht und das schmeckt gut.', decoding: [{ sv: 'kakan', de: 'der Kuchen' }, { sv: 'är', de: 'ist' }, { sv: 'hemmagjord', de: 'hausgemacht' }, { sv: 'och', de: 'und' }, { sv: 'det', de: 'das' }, { sv: 'smakar', de: 'schmeckt' }, { sv: 'bra', de: 'gut' }], chunkIds: ['c-smakarbra'] },
  { id: 's-a1f-sott1', level: 1, sv: 'Har ni något sött till kaffet?', de: 'Habt ihr etwas Süßes zum Kaffee?', decoding: [{ sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'något', de: 'etwas' }, { sv: 'sött', de: 'Süßes' }, { sv: 'till', de: 'zu' }, { sv: 'kaffet', de: 'dem Kaffee' }], chunkIds: ['c-nagotsott'] },
  { id: 's-a1f-sott2', level: 1, sv: 'Har ni något sött? Barnen är hungriga.', de: 'Habt ihr etwas Süßes? Die Kinder sind hungrig.', decoding: [{ sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'något', de: 'etwas' }, { sv: 'sött', de: 'Süßes' }, { sv: 'barnen', de: 'die Kinder' }, { sv: 'är', de: 'sind' }, { sv: 'hungriga', de: 'hungrig' }], chunkIds: ['c-nagotsott'] },
  { id: 's-a1f-mix1', level: 1, sv: 'Ska vi fika? Te eller kaffe?', de: 'Wollen wir Kaffee trinken? Tee oder Kaffee?', decoding: [{ sv: 'ska', de: 'sollen' }, { sv: 'vi', de: 'wir' }, { sv: 'fika', de: 'Kaffeepause machen' }, { sv: 'te', de: 'Tee' }, { sv: 'eller', de: 'oder' }, { sv: 'kaffe', de: 'Kaffee' }], chunkIds: ['c-skavifika', 'c-teellerkaffe'] },
  { id: 's-a1f-mix2', level: 1, sv: 'Kan vi sitta här? Kaffe och kaka, tack.', de: 'Können wir hier sitzen? Kaffee und Kuchen, bitte.', decoding: [{ sv: 'kan', de: 'können' }, { sv: 'vi', de: 'wir' }, { sv: 'sitta', de: 'sitzen' }, { sv: 'här', de: 'hier' }, { sv: 'kaffe', de: 'Kaffee' }, { sv: 'och', de: 'und' }, { sv: 'kaka', de: 'Kuchen' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-sittahar', 'c-kaffeochkaka'] },
  { id: 's-a1f-mix3', level: 1, sv: 'Med mjölk, tack. Det smakar bra så.', de: 'Mit Milch, bitte. So schmeckt es gut.', decoding: [{ sv: 'med', de: 'mit' }, { sv: 'mjölk', de: 'Milch' }, { sv: 'tack', de: 'bitte' }, { sv: 'det', de: 'es' }, { sv: 'smakar', de: 'schmeckt' }, { sv: 'bra', de: 'gut' }, { sv: 'så', de: 'so' }], chunkIds: ['c-medmjolk', 'c-smakarbra'] },
  { id: 's-a1f-mix4', level: 1, sv: 'Har ni något sött? En kopp till, tack.', de: 'Habt ihr etwas Süßes? Noch eine Tasse, bitte.', decoding: [{ sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'något', de: 'etwas' }, { sv: 'sött', de: 'Süßes' }, { sv: 'en', de: 'eine' }, { sv: 'kopp', de: 'Tasse' }, { sv: 'till', de: 'noch' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-nagotsott', 'c-enkopptill'] },

  // ── Sprache & Lernen ──────────────────────────────────────────────────────
  { id: 's-a1s-engelska1', level: 1, sv: 'Jag är nybörjare, prata gärna långsamt.', de: 'Ich bin Anfänger, sprich bitte langsam.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'nybörjare', de: 'Anfänger' }, { sv: 'prata', de: 'sprich' }, { sv: 'gärna', de: 'gern' }, { sv: 'långsamt', de: 'langsam' }], chunkIds: ['c-jagarnyborjare'] },
  { id: 's-a1s-engelska2', level: 1, sv: 'Jag är nybörjare och förstår inte allt.', de: 'Ich bin Anfänger und verstehe nicht alles.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'nybörjare', de: 'Anfänger' }, { sv: 'och', de: 'und' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'inte', de: 'nicht' }, { sv: 'allt', de: 'alles' }], chunkIds: ['c-jagarnyborjare'] },
  { id: 's-a1s-lar1', level: 1, sv: 'Jag lär mig svenska varje dag.', de: 'Ich lerne jeden Tag Schwedisch.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'lär', de: 'lehre' }, { sv: 'mig', de: 'mich' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }], chunkIds: ['c-larmigsvenska'] },
  { id: 's-a1s-lar2', level: 1, sv: 'Jag lär mig svenska, men det tar tid.', de: 'Ich lerne Schwedisch, aber es dauert.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'lär', de: 'lehre' }, { sv: 'mig', de: 'mich' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'es' }, { sv: 'tar', de: 'nimmt' }, { sv: 'tid', de: 'Zeit' }], chunkIds: ['c-larmigsvenska'] },
  { id: 's-a1s-lite1', level: 1, sv: 'Jag pratar lite svenska, bara lite.', de: 'Ich spreche ein bisschen Schwedisch, nur ein bisschen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'pratar', de: 'spreche' }, { sv: 'lite', de: 'wenig' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'bara', de: 'nur' }, { sv: 'lite', de: 'wenig' }], chunkIds: ['c-pratarlite'] },
  { id: 's-a1s-lite2', level: 1, sv: 'Jag pratar lite svenska och lär mig mer.', de: 'Ich spreche ein bisschen Schwedisch und lerne mehr.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'pratar', de: 'spreche' }, { sv: 'lite', de: 'wenig' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'och', de: 'und' }, { sv: 'lär', de: 'lehre' }, { sv: 'mig', de: 'mich' }, { sv: 'mer', de: 'mehr' }], chunkIds: ['c-pratarlite'] },
  { id: 's-a1s-heter1', level: 1, sv: 'Hur uttalar man det? Ordet är svårt.', de: 'Wie spricht man das aus? Das Wort ist schwer.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'uttalar', de: 'spricht aus' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }, { sv: 'ordet', de: 'das Wort' }, { sv: 'är', de: 'ist' }, { sv: 'svårt', de: 'schwer' }], chunkIds: ['c-hururtalar'] },
  { id: 's-a1s-heter2', level: 1, sv: 'Hur uttalar man det på svenska?', de: 'Wie spricht man das auf Schwedisch aus?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'uttalar', de: 'spricht aus' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }, { sv: 'på', de: 'auf' }, { sv: 'svenska', de: 'Schwedisch' }], chunkIds: ['c-hururtalar'] },
  { id: 's-a1s-stavar1', level: 1, sv: 'Hur stavar man det? Långsamt, tack.', de: 'Wie schreibt man das? Langsam, bitte.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'stavar', de: 'buchstabiert' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }, { sv: 'långsamt', de: 'langsam' }, { sv: 'tack', de: 'bitte' }], chunkIds: ['c-hurstavar'] },
  { id: 's-a1s-stavar2', level: 1, sv: 'Ett svårt namn. Hur stavar man det?', de: 'Ein schwieriger Name. Wie schreibt man das?', decoding: [{ sv: 'ett', de: 'ein' }, { sv: 'svårt', de: 'schwerer' }, { sv: 'namn', de: 'Name' }, { sv: 'hur', de: 'wie' }, { sv: 'stavar', de: 'buchstabiert' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }], chunkIds: ['c-hurstavar'] },
  { id: 's-a1s-skriva1', level: 1, sv: 'Kan du skriva det? Jag hör dåligt.', de: 'Kannst du das schreiben? Ich höre schlecht.', decoding: [{ sv: 'kan', de: 'kannst' }, { sv: 'du', de: 'du' }, { sv: 'skriva', de: 'schreiben' }, { sv: 'det', de: 'es' }, { sv: 'jag', de: 'ich' }, { sv: 'hör', de: 'höre' }, { sv: 'dåligt', de: 'schlecht' }], chunkIds: ['c-kanduskriva'] },
  { id: 's-a1s-skriva2', level: 1, sv: 'Kan du skriva det på en lapp?', de: 'Kannst du das auf einen Zettel schreiben?', decoding: [{ sv: 'kan', de: 'kannst' }, { sv: 'du', de: 'du' }, { sv: 'skriva', de: 'schreiben' }, { sv: 'det', de: 'es' }, { sv: 'på', de: 'auf' }, { sv: 'en', de: 'einen' }, { sv: 'lapp', de: 'Zettel' }], chunkIds: ['c-kanduskriva'] },
  { id: 's-a1s-betyder1', level: 1, sv: 'Vad är det för ord? Jag förstår inte.', de: 'Was ist das für ein Wort? Ich verstehe nicht.', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'das' }, { sv: 'för', de: 'für' }, { sv: 'ord', de: 'Wort' }, { sv: 'jag', de: 'ich' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'inte', de: 'nicht' }], chunkIds: ['c-vadardetforord', 'c-forstar'] },
  { id: 's-a1s-betyder2', level: 1, sv: 'Vad är det för ord? Jag har aldrig hört det.', de: 'Was ist das für ein Wort? Ich habe es nie gehört.', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'das' }, { sv: 'för', de: 'für' }, { sv: 'ord', de: 'Wort' }, { sv: 'jag', de: 'ich' }, { sv: 'har', de: 'habe' }, { sv: 'aldrig', de: 'nie' }, { sv: 'hört', de: 'gehört' }, { sv: 'det', de: 'es' }], chunkIds: ['c-vadardetforord'] },
  { id: 's-a1s-ovar1', level: 1, sv: 'Jag övar varje dag, tio minuter.', de: 'Ich übe jeden Tag, zehn Minuten.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'övar', de: 'übe' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }, { sv: 'tio', de: 'zehn' }, { sv: 'minuter', de: 'Minuten' }], chunkIds: ['c-ovarvarjedag'] },
  { id: 's-a1s-ovar2', level: 1, sv: 'Jag övar varje dag och blir bättre.', de: 'Ich übe jeden Tag und werde besser.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'övar', de: 'übe' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }, { sv: 'och', de: 'und' }, { sv: 'blir', de: 'werde' }, { sv: 'bättre', de: 'besser' }], chunkIds: ['c-ovarvarjedag'] },
  { id: 's-a1s-mix1', level: 1, sv: 'Hur uttalar man det? Hur stavar man det?', de: 'Wie spricht man das aus? Wie schreibt man das?', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'uttalar', de: 'spricht aus' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }, { sv: 'hur', de: 'wie' }, { sv: 'stavar', de: 'buchstabiert' }, { sv: 'man', de: 'man' }, { sv: 'det', de: 'es' }], chunkIds: ['c-hururtalar', 'c-hurstavar'] },
  { id: 's-a1s-mix2', level: 1, sv: 'Vad är det för ord? Kan du skriva det?', de: 'Was ist das für ein Wort? Kannst du das schreiben?', decoding: [{ sv: 'vad', de: 'was' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'das' }, { sv: 'för', de: 'für' }, { sv: 'ord', de: 'Wort' }, { sv: 'kan', de: 'kannst' }, { sv: 'du', de: 'du' }, { sv: 'skriva', de: 'schreiben' }, { sv: 'det', de: 'es' }], chunkIds: ['c-vadardetforord', 'c-kanduskriva'] },
  { id: 's-a1s-mix3', level: 1, sv: 'Jag pratar lite svenska och jag övar varje dag.', de: 'Ich spreche ein bisschen Schwedisch und ich übe jeden Tag.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'pratar', de: 'spreche' }, { sv: 'lite', de: 'wenig' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'och', de: 'und' }, { sv: 'jag', de: 'ich' }, { sv: 'övar', de: 'übe' }, { sv: 'varje', de: 'jeden' }, { sv: 'dag', de: 'Tag' }], chunkIds: ['c-pratarlite', 'c-ovarvarjedag'] },
  { id: 's-a1s-mix4', level: 1, sv: 'Jag är nybörjare. Jag lär mig svenska.', de: 'Ich bin Anfänger. Ich lerne Schwedisch.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'är', de: 'bin' }, { sv: 'nybörjare', de: 'Anfänger' }, { sv: 'jag', de: 'ich' }, { sv: 'lär', de: 'lehre' }, { sv: 'mig', de: 'mich' }, { sv: 'svenska', de: 'Schwedisch' }], chunkIds: ['c-jagarnyborjare', 'c-larmigsvenska'] },

  // ── Small Talk ────────────────────────────────────────────────────────────
  { id: 's-a1p-gar1', level: 1, sv: 'Hej! Hur går det med jobbet?', de: 'Hallo! Wie läuft es mit der Arbeit?', decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'hur', de: 'wie' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }, { sv: 'med', de: 'mit' }, { sv: 'jobbet', de: 'der Arbeit' }], chunkIds: ['c-hurgardet'] },
  { id: 's-a1p-gar2', level: 1, sv: 'Hur går det? Vi har inte setts på länge.', de: 'Wie läuft es? Wir haben uns lange nicht gesehen.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }, { sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'inte', de: 'nicht' }, { sv: 'setts', de: 'uns gesehen' }, { sv: 'på', de: 'seit' }, { sv: 'länge', de: 'lange' }], chunkIds: ['c-hurgardet'] },
  { id: 's-a1p-bra1', level: 1, sv: 'Det går bra, tack. Och du?', de: 'Es läuft gut, danke. Und du?', decoding: [{ sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'bra', de: 'gut' }, { sv: 'tack', de: 'danke' }, { sv: 'och', de: 'und' }, { sv: 'du', de: 'du' }], chunkIds: ['c-detgarbra'] },
  { id: 's-a1p-bra2', level: 1, sv: 'Det går bra, tack, jag har mycket att göra.', de: 'Es läuft gut, danke, ich habe viel zu tun.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'bra', de: 'gut' }, { sv: 'tack', de: 'danke' }, { sv: 'jag', de: 'ich' }, { sv: 'har', de: 'habe' }, { sv: 'mycket', de: 'viel' }, { sv: 'att', de: 'zu' }, { sv: 'göra', de: 'machen' }], chunkIds: ['c-detgarbra'] },
  { id: 's-a1p-roligt1', level: 1, sv: 'Vad roligt! Grattis till dig.', de: 'Wie schön! Herzlichen Glückwunsch.', decoding: [{ sv: 'vad', de: 'wie' }, { sv: 'roligt', de: 'lustig' }, { sv: 'grattis', de: 'Glückwunsch' }, { sv: 'till', de: 'zu' }, { sv: 'dig', de: 'dir' }], chunkIds: ['c-vadroligt'] },
  { id: 's-a1p-roligt2', level: 1, sv: 'Ni ska resa till Spanien? Vad roligt!', de: 'Ihr fahrt nach Spanien? Wie schön!', decoding: [{ sv: 'ni', de: 'ihr' }, { sv: 'ska', de: 'werdet' }, { sv: 'resa', de: 'reisen' }, { sv: 'till', de: 'nach' }, { sv: 'Spanien', de: 'Spanien' }, { sv: 'vad', de: 'wie' }, { sv: 'roligt', de: 'lustig' }], chunkIds: ['c-vadroligt'] },
  { id: 's-a1p-synd1', level: 1, sv: 'Så synd! Vi ses en annan gång.', de: 'Wie schade! Wir sehen uns ein andermal.', decoding: [{ sv: 'så', de: 'so' }, { sv: 'synd', de: 'schade' }, { sv: 'vi', de: 'wir' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'en', de: 'ein' }, { sv: 'annan', de: 'anderes' }, { sv: 'gång', de: 'Mal' }], chunkIds: ['c-sasynd'] },
  { id: 's-a1p-synd2', level: 1, sv: 'Regnar det? Så synd, vi ville bada.', de: 'Regnet es? Wie schade, wir wollten baden.', decoding: [{ sv: 'regnar', de: 'regnet' }, { sv: 'det', de: 'es' }, { sv: 'så', de: 'so' }, { sv: 'synd', de: 'schade' }, { sv: 'vi', de: 'wir' }, { sv: 'ville', de: 'wollten' }, { sv: 'bada', de: 'baden' }], chunkIds: ['c-sasynd'] },
  { id: 's-a1p-snart1', level: 1, sv: 'Vi måste ses snart, det var länge sedan.', de: 'Wir müssen uns bald sehen, das ist lange her.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'snart', de: 'bald' }, { sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'länge', de: 'lange' }, { sv: 'sedan', de: 'her' }], chunkIds: ['c-sessnart'] },
  { id: 's-a1p-snart2', level: 1, sv: 'Vi måste ses snart, kanske i helgen.', de: 'Wir müssen uns bald sehen, vielleicht am Wochenende.', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'snart', de: 'bald' }, { sv: 'kanske', de: 'vielleicht' }, { sv: 'i', de: 'an' }, { sv: 'helgen', de: 'dem Wochenende' }], chunkIds: ['c-sessnart'] },
  { id: 's-a1p-halsa1', level: 1, sv: 'Hej då och hälsa hemma!', de: 'Tschüss und grüß zu Hause!', decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'då', de: 'dann' }, { sv: 'och', de: 'und' }, { sv: 'hälsa', de: 'grüße' }, { sv: 'hemma', de: 'daheim' }], chunkIds: ['c-halsahemma'] },
  { id: 's-a1p-halsa2', level: 1, sv: 'Hälsa hemma, jag hör av mig senare.', de: 'Grüß zu Hause, ich melde mich später.', decoding: [{ sv: 'hälsa', de: 'grüße' }, { sv: 'hemma', de: 'daheim' }, { sv: 'jag', de: 'ich' }, { sv: 'hör', de: 'höre' }, { sv: 'av', de: 'von' }, { sv: 'mig', de: 'mir' }, { sv: 'senare', de: 'später' }], chunkIds: ['c-halsahemma'] },
  { id: 's-a1p-ga1', level: 1, sv: 'Jag måste gå nu, bussen kommer.', de: 'Ich muss jetzt gehen, der Bus kommt.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'gå', de: 'gehen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'bussen', de: 'der Bus' }, { sv: 'kommer', de: 'kommt' }], chunkIds: ['c-mastega'] },
  { id: 's-a1p-ga2', level: 1, sv: 'Tyvärr, jag måste gå nu. Hej då!', de: 'Leider muss ich jetzt gehen. Tschüss!', decoding: [{ sv: 'tyvärr', de: 'leider' }, { sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'gå', de: 'gehen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'hej', de: 'hallo' }, { sv: 'då', de: 'dann' }], chunkIds: ['c-mastega'] },
  { id: 's-a1p-trevligt1', level: 1, sv: 'Det var trevligt, tack för i kväll.', de: 'Das war nett, danke für den Abend.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'trevligt', de: 'nett' }, { sv: 'tack', de: 'danke' }, { sv: 'för', de: 'für' }, { sv: 'i', de: 'am' }, { sv: 'kväll', de: 'Abend' }], chunkIds: ['c-vartrevligt'] },
  { id: 's-a1p-trevligt2', level: 1, sv: 'Det var trevligt att träffa dig igen.', de: 'Es war nett, dich wiederzusehen.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'var', de: 'war' }, { sv: 'trevligt', de: 'nett' }, { sv: 'att', de: 'zu' }, { sv: 'träffa', de: 'treffen' }, { sv: 'dig', de: 'dich' }, { sv: 'igen', de: 'wieder' }], chunkIds: ['c-vartrevligt'] },
  { id: 's-a1p-mix1', level: 1, sv: 'Hur går det? Det går bra, tack.', de: 'Wie läuft es? Es läuft gut, danke.', decoding: [{ sv: 'hur', de: 'wie' }, { sv: 'går', de: 'geht' }, { sv: 'det', de: 'es' }, { sv: 'det', de: 'es' }, { sv: 'går', de: 'geht' }, { sv: 'bra', de: 'gut' }, { sv: 'tack', de: 'danke' }], chunkIds: ['c-hurgardet', 'c-detgarbra'] },
  { id: 's-a1p-mix2', level: 1, sv: 'Jag måste gå nu, men vi måste ses snart.', de: 'Ich muss jetzt gehen, aber wir müssen uns bald sehen.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'måste', de: 'muss' }, { sv: 'gå', de: 'gehen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'men', de: 'aber' }, { sv: 'vi', de: 'wir' }, { sv: 'måste', de: 'müssen' }, { sv: 'ses', de: 'sehen uns' }, { sv: 'snart', de: 'bald' }], chunkIds: ['c-mastega', 'c-sessnart'] },
  { id: 's-a1p-mix3', level: 1, sv: 'Det var trevligt! Hälsa hemma.', de: 'Das war nett! Grüß zu Hause.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'var', de: 'war' }, { sv: 'trevligt', de: 'nett' }, { sv: 'hälsa', de: 'grüße' }, { sv: 'hemma', de: 'daheim' }], chunkIds: ['c-vartrevligt', 'c-halsahemma'] },
  { id: 's-a1p-mix4', level: 1, sv: 'Så synd! Men vad roligt för dig.', de: 'Wie schade! Aber wie schön für dich.', decoding: [{ sv: 'så', de: 'so' }, { sv: 'synd', de: 'schade' }, { sv: 'men', de: 'aber' }, { sv: 'vad', de: 'wie' }, { sv: 'roligt', de: 'lustig' }, { sv: 'för', de: 'für' }, { sv: 'dig', de: 'dich' }], chunkIds: ['c-sasynd', 'c-vadroligt'] },
];
