// Gespräche zu Allergien, Tierarzt, Reparieren und Kino (Ausbau 5).

import type { Dialog } from '../../domain/dialog';

export const dialogs: Dialog[] = [
  {
    id: 'dlg-allergy',
    categoryId: 'cat-allergy',
    title: 'Im Lokal: sagen, was du nicht verträgst',
    blurb: 'Das einzige Gespräch dieser App, bei dem Missverstehen wehtut.',
    scene: 'cafe',
    partnerName: 'Kellnerin',
    turns: [
      { id: 'al1', speaker: 'partner', sv: 'Hej {name}! Har ni bestämt er?', de: 'Hallo {name}! Habt ihr euch entschieden?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'har', de: 'habt' }, { sv: 'ni', de: 'ihr' }, { sv: 'bestämt', de: 'bestimmt' }, { sv: 'er', de: 'euch' }] },
      { id: 'al2', speaker: 'you', sv: 'jag är allergisk mot nötter', de: 'ich bin allergisch gegen Nüsse', chunkId: 'c-al-allergisk' },
      { id: 'al3', speaker: 'partner', sv: 'Tack för att du säger till. Jag frågar köket.', de: 'Danke, dass du Bescheid sagst. Ich frage die Küche.', decoding: [{ sv: 'tack', de: 'danke' }, { sv: 'för', de: 'für' }, { sv: 'att', de: 'dass' }, { sv: 'du', de: 'du' }, { sv: 'säger', de: 'sagst' }, { sv: 'till', de: 'zu' }, { sv: 'jag', de: 'ich' }, { sv: 'frågar', de: 'frage' }, { sv: 'köket', de: 'die Küche' }] },
      { id: 'al4', speaker: 'you', sv: 'det är viktigt för mig', de: 'das ist wichtig für mich', chunkId: 'c-al-viktigt' },
      { id: 'al5', speaker: 'partner', sv: 'Naturligtvis. Vi tar det på allvar.', de: 'Natürlich. Wir nehmen das ernst.', decoding: [{ sv: 'naturligtvis', de: 'natürlich' }, { sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'det', de: 'es' }, { sv: 'på', de: 'auf' }, { sv: 'allvar', de: 'Ernst' }] },
      { id: 'al6', speaker: 'partner', sv: 'Salladen då? Den har en dressing.', de: 'Der Salat dann? Der hat ein Dressing.', decoding: [{ sv: 'salladen', de: 'der Salat' }, { sv: 'då', de: 'denn' }, { sv: 'den', de: 'er' }, { sv: 'har', de: 'hat' }, { sv: 'en', de: 'ein' }, { sv: 'dressing', de: 'Dressing' }] },
      { id: 'al7', speaker: 'you', sv: 'vad innehåller den?', de: 'was ist da drin?', chunkId: 'c-al-innehaller' },
      { id: 'al8', speaker: 'partner', sv: 'Olja, senap och lite honung. Inga nötter.', de: 'Öl, Senf und etwas Honig. Keine Nüsse.', decoding: [{ sv: 'olja', de: 'Öl' }, { sv: 'senap', de: 'Senf' }, { sv: 'och', de: 'und' }, { sv: 'lite', de: 'wenig' }, { sv: 'honung', de: 'Honig' }, { sv: 'inga', de: 'keine' }, { sv: 'nötter', de: 'Nüsse' }] },
      { id: 'al9', speaker: 'you', sv: 'kan ni göra den utan ost?', de: 'könnt ihr die ohne Käse machen?', chunkId: 'c-al-utan' },
      { id: 'al10', speaker: 'partner', sv: 'Visst. Är det laktosen?', de: 'Klar. Ist es die Laktose?', decoding: [{ sv: 'visst', de: 'klar' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'laktosen', de: 'die Laktose' }] },
      { id: 'al11', speaker: 'you', sv: 'jag tål inte laktos', de: 'ich vertrage keine Laktose', chunkId: 'c-al-laktos' },
      { id: 'al12', speaker: 'partner', sv: 'Då noterar jag det. Och till din vän?', de: 'Dann notiere ich das. Und für deine Freundin?', decoding: [{ sv: 'då', de: 'dann' }, { sv: 'noterar', de: 'notiere' }, { sv: 'jag', de: 'ich' }, { sv: 'det', de: 'es' }, { sv: 'och', de: 'und' }, { sv: 'till', de: 'für' }, { sv: 'din', de: 'deine' }, { sv: 'vän', de: 'Freundin' }] },
      { id: 'al13', speaker: 'you', sv: 'jag äter inget kött', de: 'ich esse kein Fleisch', chunkId: 'c-al-vegetarian' },
      { id: 'al14', speaker: 'partner', sv: 'Vi har två rätter utan. Något mer?', de: 'Wir haben zwei Gerichte ohne. Noch etwas?', decoding: [{ sv: 'vi', de: 'wir' }, { sv: 'har', de: 'haben' }, { sv: 'två', de: 'zwei' }, { sv: 'rätter', de: 'Gerichte' }, { sv: 'utan', de: 'ohne' }, { sv: 'något', de: 'etwas' }, { sv: 'mer', de: 'mehr' }] },
      { id: 'al15', speaker: 'you', sv: 'finns det något glutenfritt?', de: 'gibt es etwas Glutenfreies?', chunkId: 'c-al-glutenfri' },
      { id: 'al16', speaker: 'partner', sv: 'Ja, brödet till vänster på menyn.', de: 'Ja, das Brot links auf der Karte.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'brödet', de: 'das Brot' }, { sv: 'till', de: 'zu' }, { sv: 'vänster', de: 'links' }, { sv: 'på', de: 'auf' }, { sv: 'menyn', de: 'der Karte' }] },
    ],
  },
  {
    id: 'dlg-vet',
    categoryId: 'cat-vet',
    title: 'Beim Tierarzt: erklären, was los ist',
    blurb: 'Der Hund frisst nicht — und du musst es genau beschreiben.',
    scene: 'clinic',
    partnerName: 'Tierärztin',
    turns: [
      { id: 'vt1', speaker: 'partner', sv: 'Hej {name}, kom in. Vad har hänt?', de: 'Hallo {name}, komm rein. Was ist passiert?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'kom', de: 'komm' }, { sv: 'in', de: 'rein' }, { sv: 'vad', de: 'was' }, { sv: 'har', de: 'ist' }, { sv: 'hänt', de: 'geschehen' }] },
      { id: 'vt2', speaker: 'you', sv: 'min hund är sjuk', de: 'mein Hund ist krank', chunkId: 'c-vt-sjuk' },
      { id: 'vt3', speaker: 'partner', sv: 'Berätta mer. Hur märks det?', de: 'Erzähl mehr. Woran merkt man das?', decoding: [{ sv: 'berätta', de: 'erzähle' }, { sv: 'mer', de: 'mehr' }, { sv: 'hur', de: 'wie' }, { sv: 'märks', de: 'merkt man' }, { sv: 'det', de: 'es' }] },
      { id: 'vt4', speaker: 'you', sv: 'den äter inget', de: 'er frisst nichts', chunkId: 'c-vt-ater' },
      { id: 'vt5', speaker: 'partner', sv: 'Sedan när?', de: 'Seit wann?', decoding: [{ sv: 'sedan', de: 'seit' }, { sv: 'när', de: 'wann' }] },
      { id: 'vt6', speaker: 'you', sv: 'det har varit så i två dagar', de: 'das ist seit zwei Tagen so', chunkId: 'c-vt-sedan' },
      { id: 'vt7', speaker: 'partner', sv: 'Rör den sig som vanligt?', de: 'Bewegt er sich wie sonst?', decoding: [{ sv: 'rör', de: 'bewegt' }, { sv: 'den', de: 'er' }, { sv: 'sig', de: 'sich' }, { sv: 'som', de: 'wie' }, { sv: 'vanligt', de: 'gewöhnlich' }] },
      { id: 'vt8', speaker: 'you', sv: 'den haltar på bakbenet', de: 'er humpelt auf dem Hinterbein', chunkId: 'c-vt-halta' },
      { id: 'vt9', speaker: 'partner', sv: 'Jag känner efter. Var lugn, det gör inte ont.', de: 'Ich taste ab. Sei ruhig, es tut nicht weh.', decoding: [{ sv: 'jag', de: 'ich' }, { sv: 'känner', de: 'fühle' }, { sv: 'efter', de: 'nach' }, { sv: 'var', de: 'sei' }, { sv: 'lugn', de: 'ruhig' }, { sv: 'det', de: 'es' }, { sv: 'gör', de: 'macht' }, { sv: 'inte', de: 'nicht' }, { sv: 'ont', de: 'Schmerz' }] },
      { id: 'vt10', speaker: 'you', sv: 'jag är orolig för den', de: 'ich mache mir Sorgen um ihn', chunkId: 'c-vt-orolig' },
      { id: 'vt11', speaker: 'partner', sv: 'Det förstår jag. Men det ser inte allvarligt ut.', de: 'Das verstehe ich. Aber es sieht nicht ernst aus.', decoding: [{ sv: 'det', de: 'das' }, { sv: 'förstår', de: 'verstehe' }, { sv: 'jag', de: 'ich' }, { sv: 'men', de: 'aber' }, { sv: 'det', de: 'es' }, { sv: 'ser', de: 'sieht' }, { sv: 'inte', de: 'nicht' }, { sv: 'allvarligt', de: 'ernst' }, { sv: 'ut', de: 'aus' }] },
      { id: 'vt12', speaker: 'partner', sv: 'Den får tabletter i en vecka.', de: 'Er bekommt eine Woche lang Tabletten.', decoding: [{ sv: 'den', de: 'er' }, { sv: 'får', de: 'bekommt' }, { sv: 'tabletter', de: 'Tabletten' }, { sv: 'i', de: 'in' }, { sv: 'en', de: 'einer' }, { sv: 'vecka', de: 'Woche' }] },
      { id: 'vt13', speaker: 'you', sv: 'hur ofta ska den ha medicinen?', de: 'wie oft soll er das Medikament bekommen?', chunkId: 'c-vt-medicin' },
      { id: 'vt14', speaker: 'partner', sv: 'Morgon och kväll, med maten.', de: 'Morgens und abends, mit dem Futter.', decoding: [{ sv: 'morgon', de: 'Morgen' }, { sv: 'och', de: 'und' }, { sv: 'kväll', de: 'Abend' }, { sv: 'med', de: 'mit' }, { sv: 'maten', de: 'dem Essen' }] },
      { id: 'vt15', speaker: 'you', sv: 'behöver den vaccin?', de: 'braucht er eine Impfung?', chunkId: 'c-vt-vaccin' },
      { id: 'vt16', speaker: 'partner', sv: 'Inte idag. Vi tar det när den mår bra igen.', de: 'Heute nicht. Wir machen das, wenn es ihm wieder gut geht.', decoding: [{ sv: 'inte', de: 'nicht' }, { sv: 'idag', de: 'heute' }, { sv: 'vi', de: 'wir' }, { sv: 'tar', de: 'nehmen' }, { sv: 'det', de: 'es' }, { sv: 'när', de: 'wenn' }, { sv: 'den', de: 'er' }, { sv: 'mår', de: 'befindet sich' }, { sv: 'bra', de: 'gut' }, { sv: 'igen', de: 'wieder' }] },
    ],
  },
  {
    id: 'dlg-repair',
    categoryId: 'cat-repair',
    title: 'Zu Hause: was tropft, klemmt und nicht leuchtet',
    blurb: 'Drei kleine Schäden — und die Frage, wer sie richtet.',
    scene: 'home',
    partnerName: 'Mitbewohner',
    turns: [
      { id: 'rp1', speaker: 'partner', sv: 'Hej {name}, sov du dåligt i natt?', de: 'Hallo {name}, hast du heute Nacht schlecht geschlafen?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'sov', de: 'schliefst' }, { sv: 'du', de: 'du' }, { sv: 'dåligt', de: 'schlecht' }, { sv: 'i', de: 'in' }, { sv: 'natt', de: 'Nacht' }] },
      { id: 'rp2', speaker: 'you', sv: 'kranen droppar', de: 'der Hahn tropft', chunkId: 'c-rp-droppar' },
      { id: 'rp3', speaker: 'partner', sv: 'Just det. Det märks mest på natten.', de: 'Genau. Nachts merkt man es am meisten.', decoding: [{ sv: 'just', de: 'gerade' }, { sv: 'det', de: 'das' }, { sv: 'det', de: 'es' }, { sv: 'märks', de: 'merkt man' }, { sv: 'mest', de: 'am meisten' }, { sv: 'på', de: 'in' }, { sv: 'natten', de: 'der Nacht' }] },
      { id: 'rp4', speaker: 'partner', sv: 'Och i hallen är det mörkt.', de: 'Und im Flur ist es dunkel.', decoding: [{ sv: 'och', de: 'und' }, { sv: 'i', de: 'in' }, { sv: 'hallen', de: 'dem Flur' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'mörkt', de: 'dunkel' }] },
      { id: 'rp5', speaker: 'you', sv: 'lampan fungerar inte', de: 'die Lampe geht nicht', chunkId: 'c-rp-lampan' },
      { id: 'rp6', speaker: 'partner', sv: 'Och badrumsdörren?', de: 'Und die Badezimmertür?', decoding: [{ sv: 'och', de: 'und' }, { sv: 'badrumsdörren', de: 'die Badezimmertür' }] },
      { id: 'rp7', speaker: 'you', sv: 'dörren går inte att stänga', de: 'die Tür lässt sich nicht schließen', chunkId: 'c-rp-dorren' },
      { id: 'rp8', speaker: 'partner', sv: 'Tre saker alltså. Vad gör vi?', de: 'Also drei Sachen. Was machen wir?', decoding: [{ sv: 'tre', de: 'drei' }, { sv: 'saker', de: 'Sachen' }, { sv: 'alltså', de: 'also' }, { sv: 'vad', de: 'was' }, { sv: 'gör', de: 'machen' }, { sv: 'vi', de: 'wir' }] },
      { id: 'rp9', speaker: 'you', sv: 'jag fixar det själv', de: 'ich mache das selbst', chunkId: 'c-rp-sjalv' },
      { id: 'rp10', speaker: 'partner', sv: 'Har du allt du behöver?', de: 'Hast du alles, was du brauchst?', decoding: [{ sv: 'har', de: 'hast' }, { sv: 'du', de: 'du' }, { sv: 'allt', de: 'alles' }, { sv: 'du', de: 'du' }, { sv: 'behöver', de: 'brauchst' }] },
      { id: 'rp11', speaker: 'you', sv: 'jag behöver verktyg', de: 'ich brauche Werkzeug', chunkId: 'c-rp-verktyg' },
      { id: 'rp12', speaker: 'partner', sv: 'Grannen har en låda. Och kranen?', de: 'Der Nachbar hat einen Kasten. Und der Hahn?', decoding: [{ sv: 'grannen', de: 'der Nachbar' }, { sv: 'har', de: 'hat' }, { sv: 'en', de: 'einen' }, { sv: 'låda', de: 'Kiste' }, { sv: 'och', de: 'und' }, { sv: 'kranen', de: 'der Hahn' }] },
      { id: 'rp13', speaker: 'you', sv: 'vi får ringa en hantverkare', de: 'wir müssen einen Handwerker rufen', chunkId: 'c-rp-ringa' },
      { id: 'rp14', speaker: 'partner', sv: 'Ska jag ringa nu på en gång?', de: 'Soll ich sofort anrufen?', decoding: [{ sv: 'ska', de: 'soll' }, { sv: 'jag', de: 'ich' }, { sv: 'ringa', de: 'anrufen' }, { sv: 'nu', de: 'jetzt' }, { sv: 'på', de: 'auf' }, { sv: 'en', de: 'ein' }, { sv: 'gång', de: 'Mal' }] },
      { id: 'rp15', speaker: 'you', sv: 'det kan vänta till helgen', de: 'das kann bis zum Wochenende warten', chunkId: 'c-rp-vantar' },
      { id: 'rp16', speaker: 'partner', sv: 'Okej. Jag skriver upp allt så vi inte glömmer.', de: 'Okay. Ich schreibe alles auf, damit wir nichts vergessen.', decoding: [{ sv: 'okej', de: 'okay' }, { sv: 'jag', de: 'ich' }, { sv: 'skriver', de: 'schreibe' }, { sv: 'upp', de: 'auf' }, { sv: 'allt', de: 'alles' }, { sv: 'så', de: 'so' }, { sv: 'vi', de: 'wir' }, { sv: 'inte', de: 'nicht' }, { sv: 'glömmer', de: 'vergessen' }] },
    ],
  },
  {
    id: 'dlg-cinema',
    categoryId: 'cat-cinema',
    title: 'Im Kino: Karten, Platz, Untertitel',
    blurb: 'Von der Kasse bis zum Gespräch danach.',
    scene: 'shop',
    partnerName: 'Freund',
    turns: [
      { id: 'ki1', speaker: 'partner', sv: 'Hej {name}! Köpte du redan?', de: 'Hallo {name}! Hast du schon gekauft?', listenFirst: true, decoding: [{ sv: 'hej', de: 'hallo' }, { sv: 'köpte', de: 'kauftest' }, { sv: 'du', de: 'du' }, { sv: 'redan', de: 'schon' }] },
      { id: 'ki2', speaker: 'you', sv: 'två biljetter, tack', de: 'zwei Karten, bitte', chunkId: 'c-ki-tvabiljetter' },
      { id: 'ki3', speaker: 'partner', sv: 'Perfekt. Vet du var vi ska sitta?', de: 'Perfekt. Weißt du, wo wir sitzen sollen?', decoding: [{ sv: 'perfekt', de: 'perfekt' }, { sv: 'vet', de: 'weißt' }, { sv: 'du', de: 'du' }, { sv: 'var', de: 'wo' }, { sv: 'vi', de: 'wir' }, { sv: 'ska', de: 'sollen' }, { sv: 'sitta', de: 'sitzen' }] },
      { id: 'ki4', speaker: 'you', sv: 'vilken salong är det?', de: 'welcher Saal ist es?', chunkId: 'c-ki-vilkensalong' },
      { id: 'ki5', speaker: 'partner', sv: 'Salong två, rad fem. En sak till.', de: 'Saal zwei, Reihe fünf. Noch eine Sache.', decoding: [{ sv: 'salong', de: 'Saal' }, { sv: 'två', de: 'zwei' }, { sv: 'rad', de: 'Reihe' }, { sv: 'fem', de: 'fünf' }, { sv: 'en', de: 'eine' }, { sv: 'sak', de: 'Sache' }, { sv: 'till', de: 'noch' }] },
      { id: 'ki6', speaker: 'you', sv: 'är filmen textad?', de: 'hat der Film Untertitel?', chunkId: 'c-ki-textad' },
      { id: 'ki7', speaker: 'partner', sv: 'Ja, på svenska. Bra för dig.', de: 'Ja, auf Schwedisch. Gut für dich.', decoding: [{ sv: 'ja', de: 'ja' }, { sv: 'på', de: 'auf' }, { sv: 'svenska', de: 'Schwedisch' }, { sv: 'bra', de: 'gut' }, { sv: 'för', de: 'für' }, { sv: 'dig', de: 'dich' }] },
      { id: 'ki8', speaker: 'partner', sv: 'Någon sitter på våra platser.', de: 'Jemand sitzt auf unseren Plätzen.', decoding: [{ sv: 'någon', de: 'jemand' }, { sv: 'sitter', de: 'sitzt' }, { sv: 'på', de: 'auf' }, { sv: 'våra', de: 'unseren' }, { sv: 'platser', de: 'Plätzen' }] },
      { id: 'ki9', speaker: 'you', sv: 'ursäkta, det är min plats', de: 'Entschuldigung, das ist mein Platz', chunkId: 'c-ki-plats' },
      { id: 'ki10', speaker: 'partner', sv: 'Det löste sig snabbt. Bra sagt.', de: 'Das hat sich schnell geklärt. Gut gesagt.', decoding: [{ sv: 'det', de: 'es' }, { sv: 'löste', de: 'löste' }, { sv: 'sig', de: 'sich' }, { sv: 'snabbt', de: 'schnell' }, { sv: 'bra', de: 'gut' }, { sv: 'sagt', de: 'gesagt' }] },
      { id: 'ki11', speaker: 'you', sv: 'när är pausen?', de: 'wann ist die Pause?', chunkId: 'c-ki-paus' },
      { id: 'ki12', speaker: 'partner', sv: 'På bio är det ingen paus här.', de: 'Im Kino gibt es hier keine Pause.', decoding: [{ sv: 'på', de: 'im' }, { sv: 'bio', de: 'Kino' }, { sv: 'är', de: 'ist' }, { sv: 'det', de: 'es' }, { sv: 'ingen', de: 'keine' }, { sv: 'paus', de: 'Pause' }, { sv: 'här', de: 'hier' }] },
      { id: 'ki13', speaker: 'partner', sv: 'Så, den var slut. Nå?', de: 'So, er war zu Ende. Na?', decoding: [{ sv: 'så', de: 'so' }, { sv: 'den', de: 'er' }, { sv: 'var', de: 'war' }, { sv: 'slut', de: 'Schluss' }, { sv: 'nå', de: 'na' }] },
      { id: 'ki14', speaker: 'you', sv: 'vad tyckte du om den?', de: 'wie fandest du ihn?', chunkId: 'c-ki-tyckte' },
      { id: 'ki15', speaker: 'partner', sv: 'Långsam i mitten, men slutet var starkt.', de: 'In der Mitte langsam, aber das Ende war stark.', decoding: [{ sv: 'långsam', de: 'langsam' }, { sv: 'i', de: 'in' }, { sv: 'mitten', de: 'der Mitte' }, { sv: 'men', de: 'aber' }, { sv: 'slutet', de: 'das Ende' }, { sv: 'var', de: 'war' }, { sv: 'starkt', de: 'stark' }] },
      { id: 'ki16', speaker: 'you', sv: 'den var värd att se', de: 'er war sehenswert', chunkId: 'c-ki-vardvart' },
    ],
  },
];
