// ERZEUGT — nicht von Hand ändern. Quelle: `npm run verify:build`
// (tools/build-verification.ts, gespeist aus tools/check-swedish.py).
// Ändert sich der Inhalt, muss diese Datei neu erzeugt werden; ein Test in
// seedContent.test.ts schlägt sonst fehl.
//
// 'machine'   = jedes Wort der Wendung ist belegtes Schwedisch (Wörterbuch +
//               Korpushäufigkeit). NICHT geprüft: Wortstellung, Idiomatik,
//               Register — dafür braucht es einen Menschen.
// 'unchecked' = mindestens ein Wort ist selten oder unbelegt.
// 'native'    = kommt hier nie vor. Es gibt bislang keine muttersprachliche
//               Gegenlesung — das zu behaupten wäre die Lüge, gegen die dieses
//               Projekt gebaut ist.

export type VerificationLevel = 'native' | 'machine' | 'unchecked';

export const VERIFICATION_META = {
  machine: 146,
  unchecked: 3,
  native: 0,
  dictionaryEntries: 152719,
} as const;

export const VERIFICATION: Record<string, VerificationLevel> = {
  'c-allergisk': 'machine',
  'c-ambulans': 'machine',
  'c-apoteket': 'machine',
  'c-betyder': 'machine',
  'c-biljett': 'machine',
  'c-blirdet': 'machine',
  'c-bokatrum': 'machine',
  'c-bordtva': 'machine',
  'c-bordu': 'machine',
  'c-braformad': 'machine',
  'c-braspelat': 'machine',
  'c-bror': 'machine',
  'c-centrum': 'machine',
  'c-engangtill': 'machine',
  'c-engelska': 'machine',
  'c-enrundatill': 'machine',
  'c-entill': 'machine',
  'c-entimme': 'machine',
  'c-familj': 'machine',
  'c-finnsmjolk': 'machine',
  'c-fiskar': 'machine',
  'c-fixardet': 'machine',
  'c-flygplatsen': 'machine',
  'c-fordyrt': 'machine',
  'c-forlat': 'machine',
  'c-forstar': 'machine',
  'c-frantyskland': 'machine',
  'c-gammal': 'machine',
  'c-gillar': 'machine',
  'c-hadetbra': 'machine',
  'c-hallden': 'machine',
  'c-hallerpa': 'machine',
  'c-hallplats': 'machine',
  'c-harbarn': 'machine',
  'c-harbrod': 'machine',
  'c-hej': 'machine',
  'c-heja': 'machine',
  'c-hejda': 'machine',
  'c-heter': 'machine',
  'c-hjalp': 'machine',
  'c-hjalpa': 'machine',
  'c-hoger': 'machine',
  'c-horduemig': 'machine',
  'c-hungrig': 'machine',
  'c-hurfort': 'machine',
  'c-hurstardet': 'machine',
  'c-huvudvark': 'machine',
  'c-iblatt': 'machine',
  'c-ingenfara': 'machine',
  'c-jagarmed': 'machine',
  'c-jagartrott': 'machine',
  'c-jagtranar': 'machine',
  'c-jatack': 'machine',
  'c-jobbar': 'machine',
  'c-kallt': 'machine',
  'c-kanintekomma': 'machine',
  'c-kassan': 'machine',
  'c-kiloapplen': 'machine',
  'c-klockan': 'machine',
  'c-klockantre': 'machine',
  'c-kontant': 'machine',
  'c-korderbra': 'machine',
  'c-kostar': 'machine',
  'c-kvitto': 'machine',
  'c-lakare': 'machine',
  'c-langsam': 'machine',
  'c-latarkonstigt': 'machine',
  'c-lateskul': 'machine',
  'c-ledigtrum': 'machine',
  'c-loppet': 'machine',
  'c-lugntvatten': 'machine',
  'c-lyckatill': 'machine',
  'c-mal': 'machine',
  'c-marbra': 'machine',
  'c-matchen': 'machine',
  'c-matt': 'machine',
  'c-medkort': 'machine',
  'c-menyn': 'machine',
  'c-motorn': 'machine',
  'c-nappar': 'machine',
  'c-narbuss': 'machine',
  'c-narfrukost': 'machine',
  'c-nartag': 'machine',
  'c-nejtack': 'machine',
  'c-nodsituation': 'machine',
  'c-notan': 'machine',
  'c-nyckeln': 'machine',
  'c-nytt-rekord': 'machine',
  'c-onthär': 'machine',
  'c-pase': 'machine',
  'c-pasvenska': 'machine',
  'c-pavag': 'machine',
  'c-prova': 'machine',
  'c-provrum': 'unchecked',
  'c-punkterat': 'unchecked',
  'c-raktfram': 'machine',
  'c-regnar': 'machine',
  'c-rekommenderar': 'machine',
  'c-ringerdig': 'machine',
  'c-ringpolis': 'machine',
  'c-sesses': 'machine',
  'c-sjuk': 'machine',
  'c-skavispringa': 'machine',
  'c-skickalank': 'machine',
  'c-smaklig': 'unchecked',
  'c-solenskiner': 'machine',
  'c-sovaute': 'machine',
  'c-spar': 'machine',
  'c-startarinte': 'machine',
  'c-stationen': 'machine',
  'c-storfisk': 'machine',
  'c-storlek': 'machine',
  'c-strax': 'machine',
  'c-tack': 'machine',
  'c-tappatvaska': 'machine',
  'c-tarden': 'machine',
  'c-tardenhar': 'machine',
  'c-tiominuter': 'machine',
  'c-tittarbara': 'machine',
  'c-torstig': 'machine',
  'c-trevligt': 'machine',
  'c-upprepa': 'machine',
  'c-ursaktamig': 'machine',
  'c-utanmjolk': 'machine',
  'c-vackerutsikt': 'machine',
  'c-vaddatum': 'machine',
  'c-vader': 'machine',
  'c-vadgordu': 'machine',
  'c-vadnatt': 'machine',
  'c-vandra': 'machine',
  'c-vanster': 'machine',
  'c-vantalite': 'machine',
  'c-var-toa': 'machine',
  'c-vargott': 'machine',
  'c-varifran': 'machine',
  'c-varrummet': 'machine',
  'c-varsagod': 'machine',
  'c-vemspelar': 'machine',
  'c-vemvann': 'machine',
  'c-verktyg': 'machine',
  'c-vihalleross': 'machine',
  'c-vihors': 'machine',
  'c-vilkenbil': 'machine',
  'c-vilkendag': 'machine',
  'c-vilkenfisk': 'machine',
  'c-vilketspel': 'machine',
  'c-vill-ha': 'machine',
  'c-vilse': 'machine',
  'c-vises': 'machine',
};

/** Warum eine Wendung als ungeprüft geführt wird (nur für die auffälligen). */
export const VERIFICATION_REASON: Record<string, string> = {
  'c-provrum': "selten belegt: provrummet",
  'c-punkterat': "selten belegt: punkterat",
  'c-smaklig': "selten belegt: smaklig",
};
